### ISSUE TITLE
 CUDA Error: out of memory on multiple GPU's

### ISSUE THREAD

**Issue by Barelos** [pjreddie/darknet#1000]
I am training a YOLO net on a computer with two GPU's but I only want to use one.
One of the GPU's is at full capacity and the other is unused.
When trying to train darknet to try and use the unavailable one and get the error: " CUDA Error: out of memory".

How can I force it to use the unused GPU?

Edit:
I am sorry, I found the answer.
If someone else encounter this problem just add `-gpu <gpu id>` to the variables of your run

**Comment by TheMikeyR** [comment]
Glad you found an answer on your issue, please close your issue if you no longer have anything regarding this topic.
