### ISSUE TITLE
How to save a trained model as a protobuf file (.pb)?

### ISSUE THREAD

**Issue by Aqsa-K** [pjreddie/darknet#1014]
I want to save my trained model as a protobuf (.pb) file. I know that weights are saved in the backup folder but how can i save the model as .pb?

**Comment by TheMikeyR** [comment]
you can't

**Comment by timombre** [comment]
You can use dark flow but it does not work with yolo v3 yet (only v2)
https://github.com/thtrieu/darkflow

**Comment by Aqsa-K** [comment]
@TheMikeyR  Is there any way to save the model in some other format maybe, if not .pb?

**Comment by TheMikeyR** [comment]
It's not implemented in this repository and I don't know others.

**Comment by Aqsa-K** [comment]
okay thank you.

**Comment by timombre** [comment]
You may found a way by following this 
https://itnext.io/implementing-yolo-v3-in-tensorflow-tf-slim-c3c55ff59dbe
and modify a bit the code.
Let me know if you try and succeed.
