### ISSUE TITLE
Wrong Annotation

### ISSUE THREAD

**Issue by Clintonium1979** [pjreddie/darknet#1023]
I am trying to train a custom model based on yolov2 and I'm hitting a snag I cannot figure out and Google hasn't helped me on this one. I am running Windows 10, downloaded all the prerequisites, edited config files according to instructions and still get this. I want only one class (person) and using coco. I am running this command:
darknet.exe detector train cfg/coco.data cfg/yolov2.cfg darknet19_448.conv.23 -dont_show
And this is what I see:
![capture](https://user-images.githubusercontent.com/32343568/43671238-0ea09486-974b-11e8-87f7-99b304aea5bd.JPG)
Anybody have any idea what this means? I ran through the get coco script a couple times to make sure everything populated correctly but still get " Wrong annotation: class_id = 9. But class_id should be [from 0 to 1]
The process cannot access the file because it is being used by another process." I have also restarted to make sure I was starting clean.

Thanks for any suggestions!

**Comment by Clintonium1979** [comment]
Apparently, I'm the only fuggin dummy that didn't know what this meant. Well, finally had a revelation today, wrote a script to do what I wanted and solved it on my own. Case closed.

**Comment by marrabld** [comment]
@Clintonium1979 What was the solution?!?!

https://xkcd.com/979/

**Comment by Clintonium1979** [comment]
In short, all of the text files for all of the pictures had other classes in them. I just wanted person (which is 0) but all the text files had 0-82 (or whatever the biggest number is) for all of the original classes but I assume if you want certain classes then the text files need to reflect that. So, I removed all reference to other classes from the text files and, if 0 wasn't in the pictures, I removed those pictures and text files. 

I used the original coco set, which had a lot of pictures and classes but wrote a VBA script to analyze each text file, I did this with MS Excel, wrote VBA to get a list of text files in the directory, VBA to get the contents of each text file, then wrote VBA to find if 0 was in the file (each class is on a different line so not hard to filter on that with VBA). After all other classes were removed I wrote VBA to write the text back to the original text files if my class was in the text file. If not, deleted the text file and the associated picture. I did it this way so I could see step-by-step how well the text manipulation but you can use any programming language.

Training was a breeze after doing this and my person detector is as reliable as it was with the original coco set but just a bit faster since it is only focused on person.

**Comment by clydebailey** [comment]
@Clintonium1979 
Could you share the code snippet you used ?

**Comment by yll1** [comment]
修改.cfg文件。你的cfg文件里面的class和filter需要修改成你的数据对应的。

**Comment by haiderasad** [comment]
> In short, all of the text files for all of the pictures had other classes in them. I just wanted person (which is 0) but all the text files had 0-82 (or whatever the biggest number is) for all of the original classes but I assume if you want certain classes then the text files need to reflect that. So, I removed all reference to other classes from the text files and, if 0 wasn't in the pictures, I removed those pictures and text files.
> 
> I used the original coco set, which had a lot of pictures and classes but wrote a VBA script to analyze each text file, I did this with MS Excel, wrote VBA to get a list of text files in the directory, VBA to get the contents of each text file, then wrote VBA to find if 0 was in the file (each class is on a different line so not hard to filter on that with VBA). After all other classes were removed I wrote VBA to write the text back to the original text files if my class was in the text file. If not, deleted the text file and the associated picture. I did it this way so I could see step-by-step how well the text manipulation but you can use any programming language.
> 
> Training was a breeze after doing this and my person detector is as reliable as it was with the original coco set but just a bit faster since it is only focused on person.

thanks this resolved my problem by modifying dataset txt files
