### ISSUE TITLE
How do I set the grid size when I use yolo v3?

### ISSUE THREAD

**Issue by developer0hye** [pjreddie/darknet#1042]
I can`t find a way to set the grid size in "yolov3.cfg".

**Comment by dukeeagle** [comment]
Any news on this?

**Comment by developer0hye** [comment]
I solved this problem and have a example for this.
Do you need it?

I just modified cfg file.

**Comment by Favi0** [comment]
> I solved this problem and have a example for this.
> Do you need it?
> 
> I just modified cfg file.

im interested , which parameter of the cfg file did you modify?

**Comment by developer0hye** [comment]
If you give me your email address, I will send you some examples for that. It depends on your input size and the position of yolo layer in cfg file.

**Comment by Favi0** [comment]
> If you give me your email address, I will send you some examples for that. It depends on your input size and the position of yolo layer in cfg file. But the grid size cannot be contorlled freely. It has some constraints.

sure, auconti@hotmail.com

**Comment by Favi0** [comment]
> If you give me your email address, I will send you some examples for that. It depends on your input size and the position of yolo layer in cfg file. But the grid size cannot be contorlled freely. It has some constraints.

hey man i received your message, could you explain it a little more? i cant get to conclusion of what you did , i see you have 3 detection layers

**Comment by dukeeagle** [comment]
> If you give me your email address, I will send you some examples for that. It depends on your input size and the position of yolo layer in cfg file. But the grid size cannot be contorlled freely. It has some constraints.

Hi there. My email is luke.igel@gmail.com. Could you reach out to me as well? I really appreciate it.

**Comment by saksham789** [comment]
> If you give me your email address, I will send you some examples for that. It depends on your input size and the position of yolo layer in cfg file. But the grid size cannot be contorlled freely. It has some constraints.

Hi there. My email is saksham.vikram12@gmail.com.Could you please share the code with me as well.

**Comment by newforrestgump001** [comment]
> I solved this problem and have a example for this.
> Do you need it?
> 
> I just modified cfg file.

Could you send me a copy of modification of cfg and source code, my e-mail is: newforrestgump@163.com, thanks a lot!

**Comment by dkendall100** [comment]
> If you give me your email address, I will send you some examples for that. It depends on your input size and the position of yolo layer in cfg file. But the grid size cannot be contorlled freely. It has some constraints.

Could you send the file to me as well? dustink.ftw@gmail.com

**Comment by riyaj8888** [comment]
please send me also what change has to be done in cfg file.
my email id is r.i.attar8@gmail.com ..help appreciated

**Comment by yuval-s** [comment]
I'll be happy if you could send me as well an example on how to do that.
[yuval.s@campus.technion.ac.il](yuval.s@campus.technion.ac.il)

**Comment by ilyes-hm** [comment]
Did anyone has found a solution to this? please, I need to change the grid size to visualize its effect.
Thank you

**Comment by ayush11shivali** [comment]
@developer0hye Hey, kindly share the changes to .cfg file with me as well at ayush11shivali@gmail.com

**Comment by developer0hye** [comment]
grid size depends on input image size and feature map size downsampled by convolution with stride or pooling.

**Comment by barzan-hayati** [comment]
Hey man. Please send your .cfg to barzanhayati@gmail.com
Are you able to control maximum number of bounding box for each cell via .cfg file?

**Comment by vietnamican** [comment]
@developer0hye. Can you send me tour .cfg file to vietnamican@gmail.com? Thank you!!

**Comment by MSJawad** [comment]
Hey, can i get a copy of your cfg file to solaimanjawad@gmail.com? thanks!

**Comment by barzan-hayati** [comment]
It's Completely easy. Just by changing width and height of input size, you could change grid size. For example in **`YOLO-Lite`** by chnaging default grid size is `7*7` for input size `224*224`. Now by changing input size to `160*224`, grid size will be `5*7`. I have tested a sample here: 

**Grid size: 7*7**
```
 compute_capability = 750, cudnn_half = 1 
   layer   filters  size/strd(dil)      input                output
   0 conv     16       3 x 3/ 1    224 x 224 x   3 ->  224 x 224 x  16 0.043 BF
   1 max                2x 2/ 2    224 x 224 x  16 ->  112 x 112 x  16 0.001 BF
   2 conv     32       3 x 3/ 1    112 x 112 x  16 ->  112 x 112 x  32 0.116 BF
   3 max                2x 2/ 2    112 x 112 x  32 ->   56 x  56 x  32 0.000 BF
   4 conv     64       3 x 3/ 1     56 x  56 x  32 ->   56 x  56 x  64 0.116 BF
   5 max                2x 2/ 2     56 x  56 x  64 ->   28 x  28 x  64 0.000 BF
   6 conv    128       3 x 3/ 1     28 x  28 x  64 ->   28 x  28 x 128 0.116 BF
   7 max                2x 2/ 2     28 x  28 x 128 ->   14 x  14 x 128 0.000 BF
   8 conv    128       3 x 3/ 1     14 x  14 x 128 ->   14 x  14 x 128 0.058 BF
   9 max                2x 2/ 2     14 x  14 x 128 ->    7 x   7 x 128 0.000 BF
  10 conv    256       3 x 3/ 1      7 x   7 x 128 ->    7 x   7 x 256 0.029 BF
  11 conv     35       1 x 1/ 1      7 x   7 x 256 ->    7 x   7 x  35 0.001 BF
  12 detection

```

**Grid size: 5*7**
```
 compute_capability = 750, cudnn_half = 1 
   layer   filters  size/strd(dil)      input                output
   0 conv     16       3 x 3/ 1    160 x 224 x   3 ->  160 x 224 x  16 0.031 BF
   1 max                2x 2/ 2    160 x 224 x  16 ->   80 x 112 x  16 0.001 BF
   2 conv     32       3 x 3/ 1     80 x 112 x  16 ->   80 x 112 x  32 0.083 BF
   3 max                2x 2/ 2     80 x 112 x  32 ->   40 x  56 x  32 0.000 BF
   4 conv     64       3 x 3/ 1     40 x  56 x  32 ->   40 x  56 x  64 0.083 BF
   5 max                2x 2/ 2     40 x  56 x  64 ->   20 x  28 x  64 0.000 BF
   6 conv    128       3 x 3/ 1     20 x  28 x  64 ->   20 x  28 x 128 0.083 BF
   7 max                2x 2/ 2     20 x  28 x 128 ->   10 x  14 x 128 0.000 BF
   8 conv    128       3 x 3/ 1     10 x  14 x 128 ->   10 x  14 x 128 0.041 BF
   9 max                2x 2/ 2     10 x  14 x 128 ->    5 x   7 x 128 0.000 BF
  10 conv    256       3 x 3/ 1      5 x   7 x 128 ->    5 x   7 x 256 0.021 BF
  11 conv     35       1 x 1/ 1      5 x   7 x 256 ->    5 x   7 x  35 0.001 BF
  12 detection
```

As you see, 11th layer shows grid size and 0 layer shows size  of input to network.

**Comment by blackCmd** [comment]
> It's Completely easy. Just by changing width and height of input size, you could change grid size. For example in **`YOLO-Lite`** by chnaging default grid size is `7*7` for input size `224*224`. Now by changing input size to `160*224`, grid size will be `5*7`. I have tested a sample here:
> 
> **Grid size: 7*7**
> 
> ```
>  compute_capability = 750, cudnn_half = 1 
>    layer   filters  size/strd(dil)      input                output
>    0 conv     16       3 x 3/ 1    224 x 224 x   3 ->  224 x 224 x  16 0.043 BF
>    1 max                2x 2/ 2    224 x 224 x  16 ->  112 x 112 x  16 0.001 BF
>    2 conv     32       3 x 3/ 1    112 x 112 x  16 ->  112 x 112 x  32 0.116 BF
>    3 max                2x 2/ 2    112 x 112 x  32 ->   56 x  56 x  32 0.000 BF
>    4 conv     64       3 x 3/ 1     56 x  56 x  32 ->   56 x  56 x  64 0.116 BF
>    5 max                2x 2/ 2     56 x  56 x  64 ->   28 x  28 x  64 0.000 BF
>    6 conv    128       3 x 3/ 1     28 x  28 x  64 ->   28 x  28 x 128 0.116 BF
>    7 max                2x 2/ 2     28 x  28 x 128 ->   14 x  14 x 128 0.000 BF
>    8 conv    128       3 x 3/ 1     14 x  14 x 128 ->   14 x  14 x 128 0.058 BF
>    9 max                2x 2/ 2     14 x  14 x 128 ->    7 x   7 x 128 0.000 BF
>   10 conv    256       3 x 3/ 1      7 x   7 x 128 ->    7 x   7 x 256 0.029 BF
>   11 conv     35       1 x 1/ 1      7 x   7 x 256 ->    7 x   7 x  35 0.001 BF
>   12 detection
> ```
> 
> **Grid size: 5*7**
> 
> ```
>  compute_capability = 750, cudnn_half = 1 
>    layer   filters  size/strd(dil)      input                output
>    0 conv     16       3 x 3/ 1    160 x 224 x   3 ->  160 x 224 x  16 0.031 BF
>    1 max                2x 2/ 2    160 x 224 x  16 ->   80 x 112 x  16 0.001 BF
>    2 conv     32       3 x 3/ 1     80 x 112 x  16 ->   80 x 112 x  32 0.083 BF
>    3 max                2x 2/ 2     80 x 112 x  32 ->   40 x  56 x  32 0.000 BF
>    4 conv     64       3 x 3/ 1     40 x  56 x  32 ->   40 x  56 x  64 0.083 BF
>    5 max                2x 2/ 2     40 x  56 x  64 ->   20 x  28 x  64 0.000 BF
>    6 conv    128       3 x 3/ 1     20 x  28 x  64 ->   20 x  28 x 128 0.083 BF
>    7 max                2x 2/ 2     20 x  28 x 128 ->   10 x  14 x 128 0.000 BF
>    8 conv    128       3 x 3/ 1     10 x  14 x 128 ->   10 x  14 x 128 0.041 BF
>    9 max                2x 2/ 2     10 x  14 x 128 ->    5 x   7 x 128 0.000 BF
>   10 conv    256       3 x 3/ 1      5 x   7 x 128 ->    5 x   7 x 256 0.021 BF
>   11 conv     35       1 x 1/ 1      5 x   7 x 256 ->    5 x   7 x  35 0.001 BF
>   12 detection
> ```
> 
> As you see, 11th layer shows grid size and 0 layer shows size of input to network.

Thank you, u save me 👍  🙋🏻‍♂️

**Comment by vietnamican** [comment]
@blackCmd After i investigate, i relize that a cell has size 32x32, so if you want to change the grid cell, you have to change the size of input.

**Comment by FrancescoRossi1987** [comment]
just set input size and  it will automatically scale based on magic number 32

**Comment by dkendall100** [comment]
The way I solved this was to use YoloV3 tiny configuration.
With the tiny configuration, I was able to detect smaller objects.
 
https://github.com/pjreddie/darknet/blob/master/cfg/yolov3-tiny.cfg

I believe that the grid size is indirectly sized by your anchor boxes on the yolo layer in conjunction with the size of your input layer.

**Comment by sanjulsharma** [comment]
> I solved this problem and have a example for this.
> Do you need it?
> 
> I just modified cfg file.

Please send it
