### ISSUE TITLE
v2 anchors vs v3 anchors 

### ISSUE THREAD

**Issue by TheHidden1** [pjreddie/darknet#1060]
**dumb question**
i mean why do they look so different  (ones in in the hundred yet the others are  very small )?

**Comment by chenxu93** [comment]
yeah,i also finde this problem,does anyone can make it sense?

**Comment by AlexeyAB** [comment]
v2 - for size of the last layer (size of final feature map)
v3 - for size of the first layer (size of neural network)

**Comment by TheHidden1** [comment]
ah , thank you @AlexeyAB
