### ISSUE TITLE
Fine tune car class with VOC weights

### ISSUE THREAD

**Issue by memon-aliraza** [pjreddie/darknet#1075]
We have our custom dataset related to cars. We want to use pre-trained model (yolov2-voc.weights) and tune only the car class. Could somebody point me to the settings. Thanks!

**Comment by memon-aliraza** [comment]
Any suggestions please!

**Comment by timombre** [comment]
That is not an issue, for questions related to implementation, you should have a look here: https://groups.google.com/forum/?nomobile=true#!forum/darknet

**Comment by memon-aliraza** [comment]
Thanks for pointing me to the right forum.
