### ISSUE TITLE
YOLO batch size for test speed

### ISSUE THREAD

**Issue by ShoufaChen** [pjreddie/darknet#1085]
Hi,

What is the batch size when test YOLOv2 and YOLOv3  detect speed?

**Comment by jingtianyilong** [comment]
for training you could set batch=64, subdivision=4 for example, it really depends on what graphic card you are using. For testing just set both with 1 will be good.

**Comment by srhtyldz** [comment]
> for training you could set batch=64, subdivision=4 for example, it really depends on what graphic card you are using. For testing just set both with 1 will be good.

Are you sure about testing ? should we set 1 for subdivision and batch size to test/valid data ?

**Comment by srhtyldz** [comment]
> Hi,
> 
> What is the batch size when test YOLOv2 and YOLOv3 detect speed?

Did you get exact answer ?

**Comment by RTalha** [comment]
hi can anyone tell me about batch size that i am trainin yolov3 for custom data with 6 classes 20000 images what will be the batch size and why?
any help will be appreciated.
thanks

**Comment by lo-pan** [comment]
> for training you could set batch=64, subdivision=4 for example, it really depends on what graphic card you are using. For testing just set both with 1 will be good.

Can i adjust the batchsize in test? Is this means i can test multiple pictures at the same time? However, when I set the batchszie =4/8, the detection results are obviously different from the detection results with batchsize =1, Could you tell me why? Please, thanks!!!

**Comment by ujsyehao** [comment]
@lo-pan I encounter the problem too, different batchsize setting affects detection results.
