### ISSUE TITLE
How can I add custom new class labels, lets say-x classes to a Yolo trained model( which is already trained on y classes). So I do not replace those y classes and in total I have x+y class labels.

### ISSUE THREAD

**Issue by visshvesh** [pjreddie/darknet#1088]
Lets say:
Yolo model is trained to detect : dog and cat.
Custom object labels(to train): car, bike.
Final o/p: YoloV2 model detecting: dog, cat, car & bike.

**Comment by leekwunfung817** [comment]
```
cls
cd /d <path>\darknet\alexey_darknet\darknet-master\build\darknet\x64
darknet.exe ^
detector train ^
<object>.data ^
cfg\<structure>.cfg
```

<object>.data
```
classes= 2
train  = train.txt  
valid  = test.txt  
names = obj.names
backup = cpos
```


obj.names
```
dog
cat
```

**Comment by PeterQuinn925** [comment]
You also need to change the number of classes and the filters in the cfg file. See https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects

These instructions are for yolov3.cfg, you'll need to do something similar, but not exactly the same if you're using a tiny variant.

**Comment by Tuskio** [comment]
@visshvesh Is this problem solved?

**Comment by visshvesh** [comment]
@Tuskio  yup, turns out we need images of previous and new labels to train the model. Closing this issue.

**Comment by sidharthskumar** [comment]
please help me too.. i have this yolov3 model trained on coco dataset i want to detect more classes how should i go ahead?

**Comment by kuldeepmehta79** [comment]
@visshvesh Do we need to the train the old objects +new objects again?or is there a way to train for only new labels

**Comment by Sushmitha041** [comment]
Hey, even I'm having the same doubt I have weights and configuration file of pretrained yolov3 model on coco dataset but now I need to add a few more classes how do I proceed
