### ISSUE TITLE
What mem size in GPU is recommended for YOLO?

### ISSUE THREAD

**Issue by minertom** [pjreddie/darknet#1094]
Hi,

I have just installed CUDA, OpenCV and Darknet. I was only capable of running the model with tiny weights. My graphics card, supposedly, has 2G available (gtx960) as opposed to the newer models with 11G. 

Typing nvidia-smi shows that I am not really using all that much GPU memory.

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.77                 Driver Version: 390.77                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 960     Off  | 00000000:01:00.0  On |                  N/A |
| 32%   40C    P8    11W / 120W |    475MiB /  2000MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0       978      G   /usr/lib/xorg/Xorg                           322MiB |
|    0      1590      G   compiz                                        71MiB |
|    0      5485      G   ...-token=08C2FB9A63B9208A8F14582B39AC59E6    76MiB |
+-----------------------------------------------------------------------------+

So, if my card is not really capable, with 2G, then how much is recommended? 

Also, would full sized YOLO 3 work on a laptop Graphics card?

Thank You
Tom

**Comment by HareshMiriyala** [comment]
8gb recommended. My yolo v3 takes up 7300mb on the 1080 GPU
