### ISSUE TITLE
Is there a pretrain model provided for YOLOV3-tiny ?

### ISSUE THREAD

**Issue by zhangjinsong3** [pjreddie/darknet#1115]
I have trained my data on yoloV3-tiny but it does not perform well.So If author has a pre-training model like darknet 53? Thank you very much!

**Comment by AlexeyAB** [comment]
You can get pre-trained weights file `yolov3-tiny.conv.15` for yolov3-tiny.cfg by using this command:

`./darknet partial cfg/yolov3-tiny.cfg yolov3-tiny.weights yolov3-tiny.conv.15 15`

More: https://github.com/AlexeyAB/darknet/blob/57e878b4f9512cf9995ff6b5cd6e0d7dc1da9eaf/build/darknet/x64/partial.cmd#L24

**Comment by zhangjinsong3** [comment]
@AlexeyAB  Thanks very much！
