### ISSUE TITLE
 Feature map visualization 

### ISSUE THREAD

**Issue by nsantavas** [pjreddie/darknet#1124]
Hi

Is there any way to visualize feature map of a model and how?

Thank you

**Comment by vinjn** [comment]
Do you want sth. like this?
https://github.com/jing-vision/lightnet/tree/master/feature-viz

**Comment by nsantavas** [comment]
yes but is there any version for linux?

**Comment by vinjn** [comment]
Nope, but it should be trivial to port to Linux.
