### ISSUE TITLE
Custom object training converges but no detections on training set!

### ISSUE THREAD

**Issue by AimiHat** [pjreddie/darknet#1132]
Hi! I have been training some custom objects with yolov3. Had success with a complicated object and am now trying to train another object which is simpler, however the results are very weird.

I am suspecting that something is wrong in the way I train or test but cannot figure out what that is.

Some information:
- 1 class with about 600 images
- logs seem to show training set convergence after a few thousand iterations (obj close to 1 and no obj close to 0)

```
Region 106 Avg IOU: 0.578357, Class: 0.000000, Obj: 0.449091, No Obj: 0.000147, .5R: 0.500000, .75R: 0.000000,  count: 2
Region 82 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000003, .5R: -nan, .75R: -nan,  count: 0
Region 94 Avg IOU: 0.617976, Class: 0.000000, Obj: 0.928068, No Obj: 0.000224, .5R: 1.000000, .75R: 0.000000,  count: 1
Region 106 Avg IOU: 0.833563, Class: 0.000000, Obj: 0.999533, No Obj: 0.000107, .5R: 1.000000, .75R: 1.000000,  count: 1
Region 82 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000002, .5R: -nan, .75R: -nan,  count: 0
Region 94 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000001, .5R: -nan, .75R: -nan,  count: 0
Region 106 Avg IOU: 0.779995, Class: 0.000000, Obj: 0.985702, No Obj: 0.000172, .5R: 1.000000, .75R: 1.000000,  count: 2
```
However when I test (even on training images!) I get no predictions whatsoever and with threshold of 0, I get many many 0% detections.
```
./darknet detector test cfg/siren.data cfg/siren.cfg backup/siren.weights image.jpg

  105 conv     18  1 x 1 / 1    76 x  76 x 256   ->    76 x  76 x  18  0.053 BFLOPs
  106 yolo
Loading weights from backup/siren.weights...Done!
image.jpg: Predicted in 0.080925 seconds.
**** No predictions
```

If someone could suggest a potential cause for this issue i would be extremely grateful!
Also, what does 'count' correspond to? (all my training images have a single bounding box, so a count of 2 does not make sense to me)

Thanks a lot!

**Comment by amusi** [comment]
i think you can modify the train.cfg to the test.cfg. For example, reduce batch value and subdivisions value.

**Comment by AimiHat** [comment]
> i think you can modify the train.cfg to the test.cfg. For example, reduce batch value and subdivisions value.

Thanks for the reply! I have tried setting both to 1 and the output remains the same :/

**Comment by AimiHat** [comment]
The class index in the labels was incorrect (1 instead of 0).
