### ISSUE TITLE
Magic Numbers need comments

### ISSUE THREAD

**Issue by fogonthedowns** [pjreddie/darknet#1139]
As a user I would like to read your code and contribute but there are magic numbers that need comments. For example what does `-1` mean, how about the significance of `256`? This is a big task but it would make the code more readable. 

```void *display_in_thread(void *ptr)
{
    int c = show_image(buff[(buff_index + 1)%3], "Demo", 1);
    if (c != -1) c = c%256;
    if (c == 27) {
        demo_done = 1;
        return 0;
    } else if (c == 82) {
        demo_thresh += .02;
    } else if (c == 84) {
        demo_thresh -= .02;
        if(demo_thresh <= .02) demo_thresh = .02;
    } else if (c == 83) {
        demo_hier += .02;
    } else if (c == 81) {
        demo_hier -= .02;
        if(demo_hier <= .0) demo_hier = .0;
    }
    return 0;
}```

**Comment by DesBurak** [comment]
OpenCV waitKey might be buggy in some systems, so %256 is for getting a value between 0-255 for key. -1 means there was no key input while listening.
