### ISSUE TITLE
problem occur when i run video detection

### ISSUE THREAD

**Issue by Metal-joker** [pjreddie/darknet#114]
here is command i use 
`./darknet detector demo cfg/voc.data cfg/test.cfg tiny-yolo-voc.weights ~/python_workspace/test/test2.mp4 `
i changed my config file to this to make detection faster
` [net]                                                                       
  batch=64
  subdivisions=4
  width=320
  height=160
`
it seems work, output fps is over 15

but the video output sometimes very fast even look like 30fps, sometimes very slow looks like 1fps

and the terminal output still 15 fps

did i do something wrong?

help me fix it plz.

Thanks.

**Comment by reinaldomaslim** [comment]
for inferencing set batch=1 and subdivisions=1 for lower memory
