### ISSUE TITLE
Compile with GPU=1, curand.h: No such file or directory

### ISSUE THREAD

**Issue by mmmfarrell** [pjreddie/darknet#1149]
I am trying to compile darknet with GPU on Ubuntu 16.04. I have cuda-9.0 installed on my machine and I created a symlink in /usr/local/cuda that points to /usr/local/cuda-9.0 so that the default paths in the make file are correct. Darknet compiles fine without GPU but when I set GPU=1 I get the error:

```
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -Wall -Wno-unused-result -Wno-unknown-pragmas -Wfatal-errors -fPIC -Ofast -DGPU -c ./src/gemm.c -o obj/gemm.o
In file included from ./src/utils.h:5:0,
                 from ./src/gemm.c:2:
include/darknet.h:12:24: fatal error: curand.h: No such file or directory
compilation terminated.
Makefile:89: recipe for target 'obj/gemm.o' failed
make: *** [obj/gemm.o] Error 1
```

My initial guess is that for some reason the CURAND Library is not properly installed or something?

**Comment by PeterQuinn925** [comment]
Does curand.h exist on your system? Make sure the path is right.

**Comment by mmmfarrell** [comment]
@PeterQuinn925 haha ok that is a good place to start. I just ran `sudo find / -type f -name "curand.h"` and nothing came up. 

in `/usr/local/cuda/lib64` I do have `libcurand.so.9.0` though...

**Comment by PeterQuinn925** [comment]
I find curand.h in the same directory that cudnn.h is in: ...\NVIDA GPU Computing Toolkit\CUDA\v9.1\include
My laptop with a GPU uses windows. I don't have the CUDA stuff installed on a Linux box so I don't know where it would go.

**Comment by erivera1802** [comment]
@PeterQuinn925 Did you find what was the problem? I got the exact same issue

**Comment by mmmfarrell** [comment]
@erivera1802 I got it working yesterday. 

The first time I installed CUDA I followed the tensorflow documentation [Install CUDA with apt](https://www.tensorflow.org/install/gpu). This only installs the necessary dependency to run cuda programs, but does not give you some of the development dependencies (i.e. .h files). After blowing away my CUDA install and reinstalling following the [Linux CUDA install guide](http://developer.download.nvidia.com/compute/cuda/9.0/Prod/docs/sidebar/CUDA_Installation_Guide_Linux.pdf). It worked! I think the missing dependency was the 'cuda-libraries-dev-9.0' (see section 3.7.3 Meta Packages of the install guide).

Hope this helps!

**Comment by aswin-raghavan** [comment]
I just solved the exact same issue.
It happens because you only have the CUDA runtime and not the dev version. 
You can try installing `libcudnn7-dev`, or starting from the `devel` tag in `nvidia/cuda` dockerhub. The dev package has the include files. From `https://hub.docker.com/r/nvidia/cuda`
```devel: extends the runtime image by adding the compiler toolchain, the debugging tools, the headers and the static libraries.
Use this image to compile a CUDA application from sources.```

**Comment by JakBio** [comment]
Note for the people that are using / have multiple cuda versions installed on Ubuntu (20.04). I have currently active cuda 11.4.3 because of the dependencies for TensorRT. I also have newer versions of cuda on my pc (for other dependencies). But, because there are newer versions of libcu* available apt autoremove decided that the older are useless and they got accidentally purged during updating.
