### ISSUE TITLE
Running detection on multiple images with Python - Memory leak?

### ISSUE THREAD

**Issue by jonathangranskog** [pjreddie/darknet#116]
I am testing the Python API to run detection on thousands of images after each other and I've found that the memory keeps increasing over time until filling it. I haven't experienced similar problems using the C code directly. I am on Ubuntu 14.04. 

Here's the python script I am running:
```
import python.darknet
import os, sys

net = python.darknet.load_net("cfg/yolo.cfg", "weights/yolo.weights", 0)
meta = python.darknet.load_meta("cfg/coco.data")

folder = sys.argv[1]
files = os.listdir(folder)

for f in files:
    if f.endswith(".jpg") or f.endswith(".jpeg") or f.endswith(".png"):
        print f
        path = os.path.join(folder, f)
        im = python.darknet.load_image(path, 0, 0)
        res = python.darknet.detect(net, meta, im)
	print res[:3]
```
Is it a memory leak? Or is there something else I should consider when running on multiple images in a row?

**Comment by jonathangranskog** [comment]
Ok I solved this by adding a function which takes as input the byte array of an image from python and then creating an image object from it and freeing it when detection is completed.

**Comment by tmsd2001** [comment]
How do you do that?

**Comment by ManivannanMurugavel** [comment]
Use this link for import python.darknet
Link:https://github.com/pjreddie/darknet and open python folder see the darknet.py

**Comment by sayanmutd** [comment]
@ManivannanMurugavel  How do i give an image array as input in darknet.py?

**Comment by ManivannanMurugavel** [comment]
Go to the https://github.com/pjreddie/darknet/blob/master/python/darknet.py python file and see detect function line no 119. You can pass your image array as the second argument of that network_detect function

Example

network_detect(net,**Pass your Image array**, thresh, hier_thresh, nms, boxes, probs)

**Comment by mhusseinsh** [comment]
@ManivannanMurugavel but this script prints out only values, it doesn't save the output image with a bounding box
