### ISSUE TITLE
Getting make error while compiling with cuDNN 

### ISSUE THREAD

**Issue by Feywell** [pjreddie/darknet#117]
![2017-08-03 12 23 05](https://user-images.githubusercontent.com/24384298/28905982-d671dcf6-7846-11e7-993e-84e0fd215e9f.png)

I have a trouble when I make darknet with GPU =1 ,OPENCV =1 ,cuDNN = 1(I have installed CUDA8.0 and cuDNN V4)
I don't know how to deal with it.Any help appreciated!

**Comment by AlexeyAB** [comment]
@Feywell There is not cuDNN v4 for CUDA 8.0: https://developer.nvidia.com/rdp/cudnn-archive
Use cuDNN v5 for CUDA 8.0.

**Comment by Feywell** [comment]
@AlexeyAB Thank you! I have tried another version of cuDNN,It's okay.
