### ISSUE TITLE
Would it be helpful to train on images without target?

### ISSUE THREAD

**Issue by ZedYeung** [pjreddie/darknet#1178]
Sorry to ask this stupid question. I am new to object detection and curious about that.
For example, I want to detect dog in images with dog or wolf or both. And the training set only annotate the dogs' box and whether there are dogs in the image. Could I train yolo on images without dogs and tell yolo there are no dogs in images, would it be helpful? 
If so, how should I edit the lables file? <object-class> <x> <y> <width> <height>
use 0 as object-class to represent no object in it? and then x, y, width, height to cover the whold image?

Or I should firstly use a plain CNN to classify whether there are some dogs in it.  And only use the yolo when the CNN believes there are some dogs in the image?

Thanks for help

**Comment by mathieuorhan** [comment]
Use an empty .txt file for this

**Comment by ZedYeung** [comment]
thanks
