### ISSUE TITLE
When the  classification model is learned, I don't want to use crop augmentation.

### ISSUE THREAD

**Issue by developer0hye** [pjreddie/darknet#1185]
When the  classification model is learned, I don't want to use crop augmentation.
cropping destroy my dataset. so I want to not use crop augmentation. but your code always works on crop augmentation. Is there any way to off crop augmentation without modify the original code?

**Comment by developer0hye** [comment]
I solved that issue, sorry.

**Comment by BogoK** [comment]
How?

**Comment by developer0hye** [comment]
you must modified the code
