### ISSUE TITLE
OpenCV GpuMat and forward_network_gpu, bypass cudaMemcpyHostToDevice

### ISSUE THREAD

**Issue by sberryman** [pjreddie/darknet#1186]
I'm wondering if anyone has taken the time to step through the code and make minor changes to `forward_network_gpu` to support a GpuMat as input and bypass `cuda_make_array` followed by `cuda_push_array`. I would like to avoid the round-trip Device->Host memory copy and back.

I'm using NVidia Codec SDK to read and decode H264/H265 video using OpenCV which gives me a GpuMat where I'm resizing and running a few kernels BEFORE doing a forward pass. I would like to avoid device->host copy, converting to a float[]/255.0, resize and host->device copy.

Based on an initial scan of the code (first time really looking at it) it doesn't look overly difficult but my C/C++ experience is almost non-existent.

**Comment by AlexeyAB** [comment]
Use `GpuMat::ptr()` function: https://docs.opencv.org/3.4/d0/d60/classcv_1_1cuda_1_1GpuMat.html#aa83fa0825c60eb22a11a87a98c3cd5ed


Try to add custom function in separate C++ file - something like this:
```cpp
void forward_network_gpu_custom(network *netp, cv::cuda::GpuMat mat)
{
    network net = *netp;
    cuda_set_device(net.gpu_index);
    //cuda_push_array(net.input_gpu, net.input, net.inputs*net.batch);
    net.input_gpu = mat.ptr();
    if(net.truth){
        cuda_push_array(net.truth_gpu, net.truth, net.truths*net.batch);
    }

    int i;
    for(i = 0; i < net.n; ++i){
        net.index = i;
        layer l = net.layers[i];
        if(l.delta_gpu){
            fill_gpu(l.outputs * l.batch, 0, l.delta_gpu, 1);
        }
        l.forward_gpu(l, net);
        net.input_gpu = l.output_gpu;
        net.input = l.output;
        if(l.truth) {
            net.truth_gpu = l.output_gpu;
            net.truth = l.output;
        }
    }
    pull_network_output(netp);
    calc_network_cost(netp);
}
```

**Comment by sberryman** [comment]
@AlexeyAB thank you so much for your quick response, I won't have a chance to test until tomorrow morning but I can't believe it could be that easy! I'm honestly more excited about your fork and specifically the yolo2_light implementation.

I'll wait to close until after testing tomorrow.

**Comment by pawan9** [comment]
@sberryman were to able to test it and did it work ?

**Comment by sberryman** [comment]
Yes, I was able to get it working. I’ll try and remember to post a sample on Monday. Feel free to remind me if I forget.

**Comment by pawan9** [comment]
@sberryman  reminding you to post a sample.

**Comment by sberryman** [comment]
Sorry but I've been swamped so I don't have time to pull out the code and make an example but this is what I did.

inputMat is an OpenCV GpuMat
```cpp
  IplImage imgTmp = inputMat;
  IplImage *ipl_img = cvCloneImage(&imgTmp);
  image out = ipl_to_image(ipl_img);
  cvReleaseImage(&ipl_img);
  rgbgr_image(out);
  image floatMat = resize_image(out, net.w, net.h);
```

Then to run a forward pass in the network I just pass in a float pointer as below (my c and c++ skills are non-existent)
```c
network_predict_gpu_cudnn_custom(net, (float*)floatMat.data);
```

cvCloneImage:
https://docs.opencv.org/2.4/modules/core/doc/old_basic_structures.html?#IplImage*%20cvCloneImage(const%20IplImage*%20image)

ipl_to_image:
https://github.com/pjreddie/darknet/blob/master/src/image_opencv.cpp#L28

rgbgr_image:
https://github.com/pjreddie/darknet/blob/61c9d02ec461e30d55762ec7669d6a1d3c356fb2/src/image.c#L527

resize_image:
https://github.com/pjreddie/darknet/blob/61c9d02ec461e30d55762ec7669d6a1d3c356fb2/src/image.c#L1199

Hope this is enough to get you going.

**Comment by kooscode** [comment]
very interested to see any if anyone got this working and if you have any code to share.

we're doing the same thing, getting raw image data and using  opencv to demosiac with gpu.

would be great if we dont have to do a bunch of gpu -> cpu -> gpu mem copies back and forth..  wastes a lot of time..
