### ISSUE TITLE
Is it possiable to train a multi-label classification on darknet ?

### ISSUE THREAD

**Issue by Casxt** [pjreddie/darknet#1195]
I have already train yolov3  as a multi-label classification in a dirty way and it works very nice. 

But I still want to train a multi-label classifier with some classification net like Resnet. Sadly I have totally no idea how to do that.

thanks for helping.

**Comment by PhillipHuang2017** [comment]
I want to konw that too, does anyone know it ?

**Comment by Casxt** [comment]
I use mobilenet instead finally
