### ISSUE TITLE
parallizing using OpenMP problem

### ISSUE THREAD

**Issue by makefile** [pjreddie/darknet#120]
I clone the code at 2017/07/17 and compiled for windows 64bit using @AlexeyAB 's porting method.
The darknet works fine without OpenMP option,if compiled with OpenMP ,the program will have memory access problem sometimes.

**Comment by AlexeyAB** [comment]
@makefile 
1. Did you use this original fork or https://github.com/AlexeyAB/darknet fork?
2. Support for OpenMP in AlexeyAB fork appeared only from the 2017/07/25 : https://github.com/AlexeyAB/darknet/commit/51477ab274bbb40be259844bdaab9685f693b028

**Comment by makefile** [comment]
@AlexeyAB 
I used the original fork as the base, and also forked your code from the 2017/07/25 that support the OpenMP: AlexeyAB/darknet@51477ab 
then I merged part of your code onto the original fork, and the compiled exe runs well using your code.
The original fork also support OpenMP now, but the code is a little different from yours.

**Comment by AlexeyAB** [comment]
@makefile
There are a lot of pitfalls here when you try to port a Darknet on Windows by yourself.

About OpenMP, you should use only one of two ways in `gemm.c`:
* or only this - accelerates on both Linux & Windows: https://github.com/AlexeyAB/darknet/commit/51477ab#diff-ee485e80dbd4792e05ef21a4b7436b6b
* or only this - accelerates on Linux, but slows down on Windows (when used OpenMP - then MSVC uses many threads, but in this case MSVC can't vectorize gemm functions to use SIMD instructions): https://github.com/pjreddie/darknet/commit/616e6305e232c1bfa76bc70c2f48e31489807b52#diff-ee485e80dbd4792e05ef21a4b7436b6b

You should not use both ways at the same time.
Which way did you use?

**Comment by makefile** [comment]
@AlexyAB
Thanks for your detailed comment.
I tried both ways separately,the first way(in your way) of accelerating runs normally, and the second way (https://github.com/pjreddie/darknet/commit/616e6305e232c1bfa76bc70c2f48e31489807b52#diff-ee485e80dbd4792e05ef21a4b7436b6b) 's running process is uncertain,sometimes runs ok,sometimes corrupt.

**Comment by makefile** [comment]
@AlexeyAB 
Thanks for your detailed comment.
I tried both ways separately,the first way(in your way) of accelerating runs normally, and the second way (https://github.com/pjreddie/darknet/commit/616e6305e232c1bfa76bc70c2f48e31489807b52#diff-ee485e80dbd4792e05ef21a4b7436b6b) 's running process is uncertain,sometimes runs ok,sometimes corrupt.
