### ISSUE TITLE
Demo needs OpenCV for webcam images

### ISSUE THREAD

**Issue by TheNoobOne007** [pjreddie/darknet#1202]
hi, am trying to run YOLO on a video using the command "./darknet detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights data/abcd.mp4" ( name of the video is abcd and it's on the /data folder ) on Linux ( kubuntu to be precise ) and it shows "Demo needs OpenCV for webcam images" right after executing the command
i tried setting opencv = 1 in Makefile but that didn't seem to do anything, am i doing something wrong?

**Comment by pedrobagatin** [comment]
Did you solve it? Is there another issue already opened?

**Comment by dreistheman** [comment]
Me too, I changed the Makefile, we are supposed to do something with cmake-gui (Windows) afterwards right for this update to be in effect?

**Comment by Kiki9832** [comment]
Emmm,I don not know but maybe we should give opencv a configuration...
