### ISSUE TITLE
A trouble while I train a model with my own dataset

### ISSUE THREAD

**Issue by Feywell** [pjreddie/darknet#121]
![default](https://user-images.githubusercontent.com/24384298/28961822-43dd8318-7936-11e7-92ae-da39816a449e.png)

I prepared a dataset to train by yolo2.But there is a trouble.I can use yolo2 to train VOC dataset.
Is it said my GPU memory is not enough?
Anyone can help me ? Thank you! 

PS: I change the classes of cfg/yolo-voc.cfg to 5.

**Comment by AlexeyAB** [comment]
@Feywell You should change filter param to `filters=125` in your cfg-file: https://github.com/AlexeyAB/darknet/blob/master/cfg/yolo-voc.2.0.cfg#L224

I.e. filters=(classes + 5)*5
More details: https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects

**Comment by Feywell** [comment]
@AlexeyAB Thank you very much!
