### ISSUE TITLE
Segmentation fault in get_region_box

### ISSUE THREAD

**Issue by zacharynevin** [pjreddie/darknet#122]
I am using darknet to train a face detector on the WIDER dataset (formatted correctly for Darknet).

I get to step ~140-150 before I start seeing a segmentation fault pop up.

### System info

- Amazon p2.xlarge instance running the AWS machine learning AMI (https://aws.amazon.com/marketplace/pp/B01M0AXXQB)
- Compiled (`make`) with `GPU=1`, `CUDNN=1`, `OPENCV=0`, `OPENMP=1`, and `DEBUG=1`.
- Command used:
````
gdb -ex=r --args ./darknet detector train ./cfg/face/train.data ./cfg/face/yolo-face.2.0.train.cfg ./backup/yolo-face.backup -gpus 0 # I was able to get to at least 100 iterations, hence the ./backup/yolo-face.backup file
````

### Description

When I try to train the dataset, I get a segmentation fault in `./src/region_layer.c:79`, which is the `get_region_box` function.

To debug this, I just put in some logging statements and found that at the moment the segfault appears, the `index`, `i`, and `j` parameters are suddenly massively increased:

```
stride=169, index=35658, i=12, j=12, w=13, h=13
stride=169, index=35658, i=12, j=12, w=13, h=13
stride=169, index=36672, i=12, j=12, w=13, h=13
stride=169, index=36672, i=12, j=12, w=13, h=13
stride=169, index=37686, i=12, j=12, w=13, h=13
stride=169, index=37686, i=12, j=12, w=13, h=13
stride=169, index=38700, i=12, j=12, w=13, h=13
stride=169, index=38700, i=12, j=12, w=13, h=13
stride=169, index=39714, i=12, j=12, w=13, h=13
stride=169, index=39714, i=12, j=12, w=13, h=13
stride=169, index=1092034398, i=12999987, j=12999987, w=13, h=13
```

**Comment by zacharynevin** [comment]
I think this has to do with my dataset, after looking at this line:

```
i = (truth.x * l.w);
j = (truth.y * l.h);
```

**Comment by zacharynevin** [comment]
Ok so I fixed my dataset so that `x`, `y`, `w` and `h` were all between `0` and `1`. Some values were _slightly_ above `1`, causing this issue

**Comment by zacharynevin** [comment]
Nevermind, still getting this issue

**Comment by zacharynevin** [comment]
I tried updating my dataset so that any instances where the bounding box is exactly at the image boundary (e.g. `x2 = image width`), I would subtract `1` pixel. However, this didn't work and I'm still getting the segmentation fault.

**Comment by violivei** [comment]
I am having a similar issue. Maybe something related to the dataset, as you said?
Is there a way to catch that exception? Maybe if i, j and index explode, we could set them to default values? I am still trying to figure that out.

**Comment by jremillard** [comment]
The function fill_truth_detection, is lettings 999999 into the truth table. 

               if ((w < .01 || h < .01)) 
			continue;
		if (x > 999990)
			continue;
Add the 999999 check.

**Comment by xiuyangleiasp** [comment]
I met the similar issue. Because I have some x=0.00 y=0.00 labels

**Comment by dhiren-hamal** [comment]
> 
Finally, this solution helped me. Thanks man!

**Comment by dhiren-hamal** [comment]
> Finally, this solution helped me. Thanks man!



>
