### ISSUE TITLE
About the implementation of deconvolution(Compared caffe)

### ISSUE THREAD

**Issue by maxuehao** [pjreddie/darknet#1225]
I used deconvolution instead of the Upsampling layer , then train the YOLOV3 model. However, I found that the detection effect of the model transplanted onto caffe is slightly different from that on darknet, such as the lower the confidence.So I want to know if the implementation of the deconvolution layer on darknet is different from caffe?Thanks.

**Comment by maxuehao** [comment]
Beacuse different detection result with and without CUDNN7

**Comment by Francis-Xia** [comment]
@maxuehao Could you give a example how to use the layer, thanks in advance.
