### ISSUE TITLE
detect nothing 

### ISSUE THREAD

**Issue by Aurora11111** [pjreddie/darknet#1226]
![error1](https://user-images.githubusercontent.com/39044868/47843635-36293480-ddfb-11e8-979f-a06668d87945.png)
![error2](https://user-images.githubusercontent.com/39044868/47843653-4214f680-ddfb-11e8-8414-91feaf30d02e.png)
I'm using my own datasets to trian,but it seems strange.

**Comment by kate-kate** [comment]
in your log there are a lot of "nan". Check your configuration
