### ISSUE TITLE
Issue compiling Darknet with GPU

### ISSUE THREAD

**Issue by cadip92** [pjreddie/darknet#1234]
I have installed Cuda10.0 and cudnn on Ubuntu 18.04 and also updated my PATH and LD_LIBRARY_PATH as per the path specified in the Installation Guide. However, as i run the Makefile to compile darknet on GPU; it gives me the below error. I am unable to understand where the exact issue is.

/usr/bin/x86_64-linux-gnu-ld: -lcuda kann nicht gefunden werden(cannot be found)
collect2: error: ld returned 1 exit status
Makefile:83: recipe for target 'libdarknet.so' failed
make: *** [libdarknet.so] Error 1

Have i done something wrong with the installation?

_Originally posted by @cadip92 in https://github.com/pjreddie/darknet/issues/200#issuecomment-436262986_

**Comment by cadip92** [comment]
Hello Khumayun

I don't know the root cause of the problem but running the below command resolved the problem for me:
sudo ln -s /usr/lib/x86_64-linux-gnu/libcuda.so.1 /usr/lib/x86_64-linux-gnu/libcuda.so

The command creates a symbolic link for the file. The reference for the same can be found in this Wikipedia link : https://en.wikipedia.org/wiki/Ln_(Unix)

**Comment by dhaval18k** [comment]
I'm stuck at same problem and i won't be able to create symbolic link 

ln: failed to create symbolic link '/usr/lib/x86_64-linux-gnu/libcuda.so': File exists
