### ISSUE TITLE
no boxes is shown in predictions.jpg

### ISSUE THREAD

**Issue by loveBBZ** [pjreddie/darknet#1247]
Hi, i have trained my dataset in YOLO v3 and i have test some images, the output is very good expect no boxes in predictions.jpg.

**Comment by loveBBZ** [comment]
here is my output and predictions.jpg
![hj x60a i9 v iue daz3](https://user-images.githubusercontent.com/33919786/48325066-ce7eaf00-e66e-11e8-920e-22f6cb66dab5.png)
![predictions](https://user-images.githubusercontent.com/33919786/48325115-0a197900-e66f-11e8-84ec-c2657003e15b.jpg)

**Comment by zh7117** [comment]
maybe the thickness of the box is zero. try to change  the thickness and test again.
it's in image.c/draw_detections() / int width = ?
remember remake it after change the value.

**Comment by loveBBZ** [comment]
@zh7117 ，thanks a lot! you are right, i have tried your solution, it works!
