### ISSUE TITLE
How to save the results ??

### ISSUE THREAD

**Issue by ChangkiSung** [pjreddie/darknet#1249]
Hi, I am trying to save the results of image recognition using darknet demo and test.

I tried ">result.txt" but I only get "Loading weights from /home/ras-pjb/darknet/backup/yolov3-tiny_10000.weights...Done!" this message and prediction image.

 So, it does not save result and time in the result.txt file.

Is there any code or commands to save result?

Thank you!

**Comment by ChangkiSung** [comment]
Hi, Thanks for reply.
I tried that but, I only get these 
.................................................
   22 conv    255  1 x 1 / 1    26 x  26 x 256   ->    26 x  26 x 255  0.088 BFLOPs
   23 yolo
Loading weights from /home/ras-pjb/darknet/backup/yolov3-tiny_10000.weights...Done!

on result.txt file and prediction image.

There is no result on result.txt file

**Comment by liuhuiCNN** [comment]
Maybe the code does not print the result. You can change the code on examples/detector.c test_detexctor function

**Comment by ChangkiSung** [comment]
But, I get result without the ">result.txt" like  DOG:100%.
Any idea?
