### ISSUE TITLE
Recognizing text within object detection bounding box

### ISSUE THREAD

**Issue by joshterrill** [pjreddie/darknet#1259]
I'm working on training a model to recognize a specific label that is on a number of bottles. The label is always the same, with a barcode on the top left, sku on the top right, and date on the bottom left. I've been able to get darknet to recognize the label on the bottle, but I would like it to be able to read to me the sku and the date on the label as well so that it can give me some output where it draws the bounding boxes around the objects, but then also prints out in plain text the value of the sku and date. What is the best way to go about something like this?

**Comment by YunYang1994** [comment]
https://github.com/YunYang1994/tensorflow-yolov3 hope it helps you

**Comment by joshterrill** [comment]
Thanks, that's exactly what I needed.
