### ISSUE TITLE
Erro:Loading weights from yolov31.weights...Couldn't open file: yolov31.weights

### ISSUE THREAD

**Issue by xiaotongnii** [pjreddie/darknet#1271]
Rrecently,study object detection,hope to use to arrange Yolov3 on Ubuntu1604 in the   virtual machine.
However,appear some Erro, make me  in troble,hope to give some tips!

 Envirnment :PC configure：Core（TM）i5-4200 CPU
 Running Env:               virtual machine14 、Ubuntu1604、
Aim  :arrange Yolov3 on Ubuntu1604 in the   virtual machine.
Time:20181123:17:20

step:
```
1、git clone https://github.com/pjreddie/darknet
2、cd darknet
      make
3、wget https://pjreddie.com/media/files/yolov3.weights
4、./darknet detect cfg/yolov3.cfg yolov3.weights data/dog.jpg
```

ERRO：
```
xt001@ubuntu:/opt/darknet$ ./darknet detect cfg/yolov3.cfg yolov31.weights data/dog.jpg
layer     filters    size              input                output
    0 conv     32  3 x 3 / 1   608 x 608 x   3   ->   608 x 608 x  32  0.639 BFLOPs
    1 conv     64  3 x 3 / 2   608 x 608 x  32   ->   304 x 304 x  64  3.407 BFLOPs
    2 conv     32  1 x 1 / 1   304 x 304 x  64   ->   304 x 304 x  32  0.379 BFLOPs
    3 conv     64  3 x 3 / 1   304 x 304 x  32   ->   304 x 304 x  64  3.407 BFLOPs
    4 res    1                 304 x 304 x  64   ->   304 x 304 x  64
    5 conv    128  3 x 3 / 2   304 x 304 x  64   ->   152 x 152 x 128  3.407 BFLOPs
    6 conv     64  1 x 1 / 1   152 x 152 x 128   ->   152 x 152 x  64  0.379 BFLOPs
    7 conv    128  3 x 3 / 1   152 x 152 x  64   ->   152 x 152 x 128  3.407 BFLOPs

   98 route  97 36
   99 conv    128  1 x 1 / 1    76 x  76 x 384   ->    76 x  76 x 128  0.568 BFLOPs
  100 conv    256  3 x 3 / 1    76 x  76 x 128   ->    76 x  76 x 256  3.407 BFLOPs
  101 conv    128  1 x 1 / 1    76 x  76 x 256   ->    76 x  76 x 128  0.379 BFLOPs
  102 conv    256  3 x 3 / 1    76 x  76 x 128   ->    76 x  76 x 256  3.407 BFLOPs
  103 conv    128  1 x 1 / 1    76 x  76 x 256   ->    76 x  76 x 128  0.379 BFLOPs
  104 conv    256  3 x 3 / 1    76 x  76 x 128   ->    76 x  76 x 256  3.407 BFLOPs
  105 conv    255  1 x 1 / 1    76 x  76 x 256   ->    76 x  76 x 255  0.754 BFLOPs
  106 yolo
```
Loading weights from yolov31.weights...Couldn't open file: yolov31.weights

Ps:
1、001@ubuntu:/opt/darknet$ ls
backup  darknet  examples  libdarknet.a   LICENSE       LICENSE.gen  LICENSE.meta  LICENSE.v1  obj     README.md  scripts
cfg     data     include   libdarknet.so  LICENSE.fuck  LICENSE.gpl  LICENSE.mit   Makefile    python  results    src
2、
```
001@ubuntu:/opt/darknet/cfg$ ls
 yolov3.cfg
yolov3.weights  
```
3、 vim Makefile  (no modify)
```
GPU=0
CUDNN=0
OPENCV=0
OPENMP=0
DEBUG=0
```

```
ARCH= -gencode arch=compute_30,code=sm_30 \
      -gencode arch=compute_35,code=sm_35 \
      -gencode arch=compute_50,code=[sm_50,compute_50] \
      -gencode arch=compute_52,code=[sm_52,compute_52]
#      -gencode arch=compute_20,code=[sm_20,sm_21] \ This one is deprecated?

# This is what I use, uncomment if you know your arch and want to specify
# ARCH= -gencode arch=compute_52,code=compute_52

VPATH=./src/:./examples
SLIB=libdarknet.so
ALIB=libdarknet.a
EXEC=darknet
OBJDIR=./obj/

CC=gcc
CPP=g++
NVCC=nvcc
AR=ar
ARFLAGS=rcs
OPTS=-Ofast
LDFLAGS= -lm -pthread
COMMON= -Iinclude/ -Isrc/
CFLAGS=-Wall -Wno-unused-result -Wno-unknown-pragmas -Wfatal-errors -fPIC
```

**Comment by PeterQuinn925** [comment]
The error msg says it can't open yolov31.weights. Do you have this file? The command line shows 
 you're using yolov3.weights. Something's not right here.

**Comment by xiaotongnii** [comment]
> The error msg says it can't open yolov31.weights. Do you have this file? The command line shows
> you're using yolov3.weights. Something's not right here.

Frist,thanks for your rely. In fact, this file(yolov3.weights) exist in the /opt/darknet/cfg 
```
xt001@ubuntu:/opt/darknet/cfg$ ls
yolov3.cfg
yolov3.weights 
```

**Comment by PeterQuinn925** [comment]
Yeah, but the error msg you posted says it's looking for yolov31.cfg. That's kind of odd.

**Comment by Niuxiaotong** [comment]
> Yeah, but the error msg you posted says it's looking for yolov31.cfg. That's kind of odd.

yea,I  try to take some ways to solve it

**Comment by Niuxiaotong** [comment]
> I have meet same problem. But its easy to solve.
> I think you should make same mistake with me,just put yolov3.weights file into /cfg.
> You should put weights file in /darknet, and you can solve it!
yea,it is a same mistake with you, , according to you ,be solved,thanke you

**Comment by ottovotto** [comment]
same problem here --> solved by putting yolov3.weights in /darknet

**Comment by orcund** [comment]
Be sure about the path of your weights file, had the same problem and in my case reason was the path to weights.

**Comment by Aaayue** [comment]
same problem here!
I changed the running command to :
`./darknet detect cfg/yolov3.cfg cfg/yolov3.weights data/dog.jpg`
add `/cfg` in front of `yolov3.weights`, everything fine!

**Comment by saangaa** [comment]
Error path can't lead to this problem.

**Comment by saangaa** [comment]
can

**Comment by saangaa** [comment]
Incorrect path can lead to this problem.

**Comment by vkrytpo** [comment]
> > The error msg says it can't open yolov31.weights. Do you have this file? The command line shows
> > you're using yolov3.weights. Something's not right here.
> 
> Frist,thanks for your rely. In fact, this file(yolov3.weights) exist in the /opt/darknet/cfg
> nxt001@ubuntu:/opt/darknet/cfg$ ls
> .... yolov3.cfg
> yolov3.weights ....

actually  yolov3.weights  must be within folder, in your case it's outside the folder....yeahh i did same mistake too.

**Comment by puttapraneeth** [comment]
Have placed weights in right path but issue persists in windows 10. Please help

Command: darknet_no_gpu.exe detector test cfg\coco.data cfg\yolov3.cfg yolov3.weights data\test-image.jpg

Loading weights from yolov3.weights...Couldn't open file: yolov3.weights

**Comment by ammu-007** [comment]
Download it from here:
https://pjreddie.com/media/files/yolov3.weights
Then move it to /darknet

**Comment by sandheepgopinath** [comment]
> 
> 
> Have placed weights in right path but issue persists in windows 10. Please help
> 
> Command: darknet_no_gpu.exe detector test cfg\coco.data cfg\yolov3.cfg yolov3.weights data\test-image.jpg
> 
> Loading weights from yolov3.weights...Couldn't open file: yolov3.weights



> 
> 
> Have placed weights in right path but issue persists in windows 10. Please help
> 
> Command: darknet_no_gpu.exe detector test cfg\coco.data cfg\yolov3.cfg yolov3.weights data\test-image.jpg
> 
> Loading weights from yolov3.weights...Couldn't open file: yolov3.weights



Hi,

I was also facing the same issue. There are two darknet folders which might be causing the confusion. 
I was placing the images and weights inside /darknet initially and i was getting the error. 
It should be placed inside darknet/build/darknet/x64/weights. 

And it worked for me.

**Comment by koushik2001** [comment]
@sandheepgopinath This actually worked for me

**Comment by chenxy1988** [comment]
> Download it from here: https://pjreddie.com/media/files/yolov3.weights Then move it to /darknet

Thanks a lot, this is working for me.  ;)

**Comment by thanishap** [comment]
I have face same problem , add the yolov3.weights to ./cfg then run the syntax ./darknet detect cfg/yolov3.cfg cfg/yolov3.weights data/dog.jpg error will be resolved.

**Comment by xiaotongnii** [comment]
good
