### ISSUE TITLE
Data are load, but training won't starting

### ISSUE THREAD

**Issue by fidor555** [pjreddie/darknet#1285]
Hello!

I'm trying to train yolov3 with my own data according to this (https://timebutt.github.io/static/how-to-train-yolov2-to-detect-custom-objects/) tutorial.

After a few troubles with labeling and loading datasets I've came to this moment. According to the tutorial, training should now start, but... it won't. 

I can't see any errors nor messages, so... I even don't know where should I be looking for mistakes.

Please, help :)
Any clues what can be wrong?

![screen](https://user-images.githubusercontent.com/33042773/49109932-575f3280-f28c-11e8-99ec-768c5566686f.png)

**Comment by PeterQuinn925** [comment]
Can you post the command line and cfg file?

**Comment by fidor555** [comment]
Thanks for reply!

Command line:
./darknet detector train cfg/obj.data cfg/mojeyolov3.cfg yolov3.weights

- weights from pjreddie website, for yolov3

About cfg...  You mean "mojeyolov3.cfg" ?

It's very... long file

Here is header:
batch=64
subdivisions=8
width=608
height=608
channels=3
momentum=0.9
decay=0.0005
angle=0
saturation = 1.5
exposure = 1.5
hue=.1

learning_rate=0.001
burn_in=1000
max_batches = 500200
policy=steps
steps=400000,450000
scales=.1,.1

Except that I had changed every "classes" to = 1 and "filters" for every layer above "yolo layer" according to equation: num/3*(classes+5) -> 18 in my case

**Comment by fidor555** [comment]
It seems to work. Thanks you! :)
