### ISSUE TITLE
How can I get class and coordinates of output bounding box(es)?

### ISSUE THREAD

**Issue by daylanc** [pjreddie/darknet#1299]
After training a model, I'm able to test an image and get a result with visual bounding boxes. How can I get the coordinates of that bounding box as well as the class names in a text or csv file?

Example:
"Class 1", X, Y, width, height
"Class 2", X, Y, width, height
...

**Comment by daylanc** [comment]
Thanks @zh7117 I got it to output with some minor tweaks. I'm not too sure what it's calculating with:
b.x*im.w
b.y*im.y
b.w*im.w
b.h*im.h
I was expecting something like: bottom left, bottom right, top left, top right or mid left, mid right, mid top, mid bottom. Do you know what that code you recommended is calculating?

**Comment by zh7117** [comment]
in the above code.
(b.x*im.w, b.y*im.h) is the center of the predicted bounding box
b.w*im.w is the width of the predicted bounding box
b.h*im.h is the width of the predicted bounding box
you can calculate out whatever you want from them.

**Comment by daylanc** [comment]
Ahhh got it. Thanks @zh7117 !

**Comment by qqish** [comment]
> 
> 
> Ahhh got it. Thanks @zh7117 !

Sorry to disturb, but what I should input at command line with the new 'image.c' for coordination?

**Comment by Mididou** [comment]
@zh7117  but , when i make the modifications above and the go to the terminal and use ''make'' command , i get this error  : fopen , invalid initializer
