### ISSUE TITLE
Can not make in Linux Mint

### ISSUE THREAD

**Issue by fotmaiden** [pjreddie/darknet#1326]
I downloaded darknet and tried to run make but i have this problem.

fantom@fantom-HP:~/darknet$ make
gcc -Iinclude/ -Isrc/ -Wall -Wno-unused-result -Wno-unknown-pragmas -Wfatal-errors -fPIC -Ofast -c ./src/gemm.c -o obj/gemm.o
In file included from ./src/gemm.c:2:0:
./src/utils.h:3:10: fatal error: stdio.h: No such file or directory
 #include <stdio.h>
          ^~~~~~~~~
compilation terminated.
Makefile:89: recipe for target 'obj/gemm.o' failed
make: *** [obj/gemm.o] Error 1

Any suggestions?

**Comment by rishucoding** [comment]
Maybe, can you try to clone the repository again and re-run make.? 
Also, did you edit the makefile?

**Comment by fotmaiden** [comment]
wil try....
edi the makefile?
what do you mean?

**Comment by YeniSu** [comment]
Hi, did you manage to solve it?
May I know how did you do it?
I have got the same issue as you did.

![github error](https://user-images.githubusercontent.com/42023349/104770420-82c67380-57ab-11eb-8960-2fbd686e8b8a.JPG)
