### ISSUE TITLE
Not able to detect multiple objects in single image

### ISSUE THREAD

**Issue by sunyi199374** [pjreddie/darknet#1327]
Hi, 
I am using YOLO to train my own weights. I have two classes which are screwdriver and wrenches.
I record around 2000 Photos for each object, filtering the background and label it with the bounding box (Each training image have only one object, not sure if that is the issue) and train in yolo tiny v3 with random = 1. 
This is the train data example, I mask the background with black and generate bounding box around object.
![screwdriver0](https://user-images.githubusercontent.com/2645110/50115308-f7b5d080-0214-11e9-971b-b0e5ebfbf879.jpg)
![wrenches206](https://user-images.githubusercontent.com/2645110/50115329-04d2bf80-0215-11e9-9bb8-04e2d95388df.jpg)

The average loss converges to around 0.06 and detection for a single object is perfect. 
However, If I use a test image that has more than one object, 
eg.
![r](https://user-images.githubusercontent.com/2645110/50115667-17012d80-0216-11e9-8d31-4e0b6dec20a9.jpg)
yolo can only detect the objects as a whole or detect nothing. 
If I split it into two images
![r1](https://user-images.githubusercontent.com/2645110/50115690-25e7e000-0216-11e9-8974-fb42638fe1d0.jpg)
![r2](https://user-images.githubusercontent.com/2645110/50115694-284a3a00-0216-11e9-9358-301514509fb9.jpg)
The result is good with 90%+ confidence. 

There are some problems I can think of:
1. The black background within the bounding box is taken as a feature by yolo. In this case, am I suppose to record data in the natural background or generate a random background for each training image? 
2. I should include the training image with two objects. I dont think this is the problem because COCO dataset does not have every combination for 80 categories. In my understanding, YOLO just collects the features for each object in the box. Please correct me if I am wrong. 

Can someone please tell me what I did wrong in this process and how to fix this issue?

**Comment by theshawnz** [comment]
I'd have to agree with your thoughts on point 1; I found that I was able to get more reliable results (detecting objects that weren't there as well as minimize false positives) by training with many backgrounds AND also training with objects partially obstructed (for example if someone was holding the wrench). 

I had a similar problem as the first image (two items are classified as a single class) and found that I made an error when manually identifying the objects. I was using a 3rd party labeling software and found that it wasn't saving the bounding box coordinates to the proper convention for yolo and thus making a much larger box that included additional data.

**Comment by sunyi199374** [comment]
Hi theshawnz, Thank you so much for sharing your idea and your experience with me. I will try to change the background and shape to train and see how the results are.

**Comment by sssmost** [comment]
Hello sunyi199374,

Have you checked to change the background and train again?

**Comment by sunyi199374** [comment]
Hi sssmost,

Yes, I did created different backgrounds for same image and that made it work. I could feed images 
of one object with different backgrounds to train and successfully detect multiple objects on one image in detection.

**Comment by fareed05** [comment]
hi sunyi199

> Hi sssmost,
> 
> Yes, I did created different backgrounds for same image and that made it work. I could feed images
> of one object with different backgrounds to train and successfully detect multiple objects on one image in detection.

hi dear hope u will fine.. i am facing the same problem kindly guide me how i do annotation and how to remove background

**Comment by YamanSinghal** [comment]
I have tried to make the yolo object detection for custom data. Everything went well but the problem i am facing is the result is showing around 200 bounding boxes for a single image with a single mask.Please help me to solve this issue.Thank you!!!
