### ISSUE TITLE
How to change checkpoint interval? 

### ISSUE THREAD

**Issue by Goldit** [pjreddie/darknet#136]
Hi all,

Do you know how to change checkpoint interval? 
YOLO saves checkpoint every 100 iterations. I want to increase the interval to, for example 5000.

Thank you and best regards,
Nhan.

**Comment by gan-lin** [comment]
Currently it seems that checkpoint intervals are hard-coded in source files (eg. `train_detector` in examples\detector.c).

**Comment by Goldit** [comment]
Thanks @gan-lin!

**Comment by songwendong** [comment]
@Goldit   How to change checkpoint interval?  Did you teach me?

**Comment by Goldit** [comment]
Hi @songwendong,

You can change checkpoint interval here: 
https://github.com/pjreddie/darknet/blob/1e729804f61c8627eb257fba8b83f74e04945db7/examples/detector.c#L136

Replace **if(i%10000==0 || (i < 1000 && i%100 == 0)){**
With, for example,  **if(i%5000){**  to change the checkpoint interval to 5000.

Remember to remake the source code.
