### ISSUE TITLE
Activation function of tiny darknet.

### ISSUE THREAD

**Issue by 92jisuk** [pjreddie/darknet#1366]
Hi. 
I have a question.
I am working image classification using tiny darknet.
I can figure out that the tiny network model uses leaky relu as activation function.
But I want to classify an image with relu activation function.

Is there any specific reasons to use leaky relu instead of relu?
If I change activation function of tiny.cfg from leaky relu to relu, is it give me low accuracy or strange result for image classification?

Please share your knowledge.
Thank you.

**Comment by adityajhanwar** [comment]
A bit late of a response.. the answer is that it depends on the network/data and nobody really knows for certain why.  Leaky ReLU fixes the dead neuron issue in backpropagation, which may help especially with models containing a large number of layers.

**Comment by AlexeyAB** [comment]
@adityajhanwar Yes. You are right.

Leaky-RELU === parametric-RELU(PReLU) with slope=0.1.

Leaky-RELU gives higher accuracy: https://arxiv.org/abs/1502.01852

If you have the same accuracy with RELU and Leaky-RELU, then your model is disbalanced - width, depth and resolution are not optimal, so dead neurons don't affect on accuracy.

![relures](https://user-images.githubusercontent.com/4096485/59873674-30418d00-93a5-11e9-92b6-c4832d5cb3bf.png)

**Comment by linchpin-k** [comment]
> A bit late of a response.. the answer is that it depends on the network/data and nobody really knows for certain why. Leaky ReLU fixes the dead neuron issue in backpropagation, which may help especially with models containing a large number of layers.

Thank you for your reply^^
Your answer is very helpful to me^^

**Comment by linchpin-k** [comment]
Thank you for replies^^
Your answers are very helpful for me^^

**Comment by Sudhakar17** [comment]
@AlexeyAB : How to set the new value of slope in leaky RELU?
