### ISSUE TITLE
How to train small object with limited training data?

### ISSUE THREAD

**Issue by blake-ding** [pjreddie/darknet#1379]
Hi Sir,

I try to train a small object (only one class) detector, but I only have limited data (1x images).
Each image has thousands objects.
My question as below :
1. If a image includes 1000 objects.
    1.1 should I label all 1000 objects?
    1.2 or cutting the image to several small size image. 
          e.g. 20 images, 50 label per image; even 1000 images, 1 label per image.   
    Does the above methods affect the training results or the convergence speed?

2. For one class object detector, should I add negative data(background image without labeling).
    If yes, what proportion between positive and negative data?

3. If our training data are high resolution (e.g. 1080P), should we do some pre-process before training? 

BR

**Comment by Chida15** [comment]
> Hi Sir,
> 
> I try to train a small object (only one class) detector, but I only have limited data (1x images).
> Each image has thousands objects.
> My question as below :
> 
> 1. If a image includes 1000 objects.
>    1.1 should I label all 1000 objects?
>    1.2 or cutting the image to several small size image.
>    e.g. 20 images, 50 label per image; even 1000 images, 1 label per image.
>    Does the above methods affect the training results or the convergence speed?
> 2. For one class object detector, should I add negative data(background image without labeling).
>    If yes, what proportion between positive and negative data?
> 3. If our training data are high resolution (e.g. 1080P), should we do some pre-process before training?
> 
> BR

Hello, did you solve it? I also met this problem.
