### ISSUE TITLE
How to extract just boxes without image

### ISSUE THREAD

**Issue by ezubnat** [pjreddie/darknet#1412]
Hi guys! 
I am just going through whole code and I see where bounding boxes dimensions are calculated and done, I can extract those normalized dimensions of the boxes, but  I cant find a way how to save an image (in predictions.png) so it displays just for example black background / white background and the original boxes. 

Can anyone help me what should I comment or what to change to get this result?
Thank you!

**Comment by zh7117** [comment]
try this, in examples/detector.c/test_detector()
``if (nms) do_nms_sort(dets, nboxes, l.classes, nms);
        //draw_detections(im, dets, nboxes, thresh, names, alphabet, l.classes);
        image img = make_image(im.w,im.h,im.c);
        draw_detections(im,dets,nboxes,thresh,names,alphabet,l.classes);
        free_detections(dets, nboxes);
        if(outfile){
            //save_image(im, outfile);
            save_image(img,outfile);
        }
        else{
            //save_image(im, "predictions");
            save_image(img,"predictions");
#ifdef OPENCV
            make_window("predictions", 512, 512, 0);
            //show_image(im, "predictions", 0);
            make_window(img,"predictions",0);
#endif
        }

**Comment by ezubnat** [comment]
thanks
