### ISSUE TITLE
make error for yolo v3 on linux

### ISSUE THREAD

**Issue by spaul13** [pjreddie/darknet#1429]
While make the darknet yolov3 (without any support like GPU or openCV) still I am getting the following error can anyone tell me how to resolve this?

_libdarknet.a(image.o): In function `load_image':
image.c:(.text+0x3043c): undefined reference to `load_image_cv'
libdarknet.a(image.o): In function `show_image':
image.c:(.text+0x27db1): undefined reference to `show_image_cv'
libdarknet.a(demo.o): In function `fetch_in_thread':
demo.c:(.text+0x58): undefined reference to `get_image_from_stream'
libdarknet.a(demo.o): In function `demo':
demo.c:(.text+0x98a): undefined reference to `open_video_stream'
demo.c:(.text+0x9aa): undefined reference to `get_image_from_stream'
demo.c:(.text+0xd14): undefined reference to `open_video_stream'
demo.c:(.text+0xd59): undefined reference to `make_window'
collect2: error: ld returned 1 exit status
Makefile:77: recipe for target 'darknet' failed_

**Comment by nkalupahana** [comment]
Can you paste your Makefile here?

**Comment by spaul13** [comment]
Its got solved. Thanks a lot.

**Comment by dingxihao1991** [comment]
@spaul13  hello ，How did you solve it
