### ISSUE TITLE
Segmentation fault (core dumped) with libdarknet.so

### ISSUE THREAD

**Issue by legend-k** [pjreddie/darknet#1441]
- When running darknet with python i get a Segmentation fault (core dumped) error after Starting the YOLO loop...

- I don't get this error when running the darknet file in c

What is causing this error?
CUDA: 10
CUDNN: v7.4.2.24
OPENCV: 3.4.0
OS: Ubuntu 18
Graphics Card: NVIDIA GTX1060

**Comment by yojayc** [comment]
I 've met the same problem, have you fixed it?
