### ISSUE TITLE
[Training Issue]only 0 0 0 0 0 can be seen on the prediction

### ISSUE THREAD

**Issue by numuhwana** [pjreddie/darknet#1442]
hello 
i tried to trained with 500 pictures of cars (the sizes of all the pictures are different)
when I got 800 weights, I executed with detection command, but only 0 0 0 0 0 could be seen on the prediction. I don't know why is that.. do somebody know this issue..?

**Comment by elfpattern** [comment]
I also encountered this questions, Have you saved it ?

**Comment by numuhwana** [comment]
@elfpattern i solved it, and it was a weight problem. For training, i changed the yolov3.cfg into my own one.
