### ISSUE TITLE
Fatal Errors when running make to compile darknet

### ISSUE THREAD

**Issue by moshah786** [pjreddie/darknet#1443]
Hi All,
Please can someone help with the following issue.
I'm really new to GitHub, darknet and a few areas of the Linux environment. So I apologise if it turns out to be something really simple and thought of as basic knowledge. 
When I run "`make`" or "`sudo make`" within the darknet folder cloned following instructions available at https://pjreddie.com/darknet/install/ , I get error messages like the following and the attached screenshot captures most of them:

`gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -Wall -Wno-unused-result -Wno-unknown-pragmas -Wfatal-errors -fPIC -Ofast -DGPU -c ./examples/captcha.c -o obj/captcha.o`

Checks that I have made are as follows:

1. I've checked the links to Cuda(mentioned in the errors and the Makefile) and they seem to work fine when accessing them in the terminal and Cuda is working on other applications like Matlab and Tensorflow. I have also tried to change it to cuda-10-0 and I still get the same result(as the cuda folder 
 seems to be a symlink and the actual link is cuda-10-0). 
Also, please note cudaThreadSynchronize function has been updated in the time_gpu function to cudaDeviceSynchronize as the former seems to have been deprecated.

2. I've also entered the path to the nvcc, as mentioned on other posts to:
`NVCC=/usr/local/cuda/bin/nvcc`

3. I have tried all of the above with Cuda 9.2 and get the same result

4. If I create a docker container with Cuda 8 it works fine but I need access to the GUI to process images in openCV and also need Cuda to run for Matlab and Tensorflow on the host OS rather than a container.

Software and versions I'm using:
Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial

Cuda Version 10.0.130
CuDNN Version: 7.4
Nvidia Driver: 410:78
I haven't yet installed OpenCV
GPU is Nvidia GTX 1080 TI - please see attached for nvidia-smi report

Many Thanks for reading and if you require further information from me to help resolve the issue, then please do not hesitate to ask.

Regards,
Mo
![darknet make error](https://user-images.githubusercontent.com/11562436/53067573-b2d83f80-34cc-11e9-94a5-6642e218ea97.png)
![nvidia-smi-report](https://user-images.githubusercontent.com/11562436/53067574-b2d83f80-34cc-11e9-85ea-2e2affe436d6.png)

**Comment by nkalupahana** [comment]
I'm not seeing any errors in that screenshot -- just all of the commands `make` is running. Could you run `make` and then `./darknet`, and paste the output to that here? If it's what I'm thinking, everything should be working!

**Comment by nkalupahana** [comment]
FYI: -Wfatal-errors, etc. are all compiler flags, not errors.

**Comment by moshah786** [comment]
Thank you so much [nkalupahana](/nkalupahana) . 
I've just reloaded and tested it again and you were right, all is working great.
I've also started reading a bit more on compiler flags(lol). 
Regards,
Moshah786
