### ISSUE TITLE
Build Error with win10,cuda9.2,opencv3.0,vs2013

### ISSUE THREAD

**Issue by xunhen** [pjreddie/darknet#1448]
Hi!
When I build this project, the error has been occurred.
![image](https://user-images.githubusercontent.com/26379410/53243653-96622000-36e3-11e9-8a03-8f88dd7d5a62.png)
How to fix it?

**Comment by PeterQuinn925** [comment]
look at https://github.com/AlexeyAB/darknet/issues/2433

**Comment by xunhen** [comment]
When I remove the im2col_kernels.cu, the error is another:
![image](https://user-images.githubusercontent.com/26379410/53254187-d3d3a700-36fd-11e9-983d-f924d5933a0a.png)

GPU is RTX2060
