### ISSUE TITLE
Couldn't open file issue when cfg or data directories are not in the same place from where darknet is launched

### ISSUE THREAD

**Issue by RanaOsamaAsif** [pjreddie/darknet#1452]
I have written a simple javascript wrapper to call darknet for detection function in a child process. I placed darknet binary, cfg and data folder in my project directory. However, if I try to run my JS wrapper from somewhere else in the file system even though I have given absolute paths to the child process spawn method(which is in Node.js) for cfg dir I get the errors

> Couldn't open file: data/coco.names

> Couldn't open file: cfg/coco.data

I think the darknet binary ignores the paths in the command and looks for the cfg and data folder in the 
same directory from where it is executed. 

How can I change this behavior(like before building) or a workaround maybe?
Thanks!

**Comment by soswow** [comment]
@RanaOsamaAsif why did you close it?
