### ISSUE TITLE
Update weights for new *.cfg

### ISSUE THREAD

**Issue by weixu000** [pjreddie/darknet#1456]
The commit f86901f6177dfc6116360a13cc06ab680e0c86b0 changed yolov3.cfg and yolov3-tiny.cfg.

However, as far as I can tell the weights files available at https://pjreddie.com have not updated accordingly.

For example, the new yolov3-tiny.cfg uses smaller anchor boxes. With the incompatible weights, the predictions tends to be smaller, which is not good.

**Comment by AlexeyAB** [comment]
yolov3-tiny.weights file was updated.


But the minor modification in the yolov3.cfg doesn't require updating of yolov3.weights.
