### ISSUE TITLE
How to train continuously for the latest weight that i made?

### ISSUE THREAD

**Issue by numuhwana** [pjreddie/darknet#1458]
I trained about 2000 iteration, and stopped it, then I want to train it more.
How to train continuously with the weight that already exist?
and is it possible to train existing weight after changing of learning rate?

**Comment by AlexeyAB** [comment]
https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects

After each 100 iterations you can stop and later start training from this point. For example, after 2000 iterations you can stop training, and later continue training  
`./darknet detector train data/obj.data yolo-obj.cfg backup/yolo-obj_last.weights`

**Comment by numuhwana** [comment]
Oh thank you so much~😊😊

**Comment by sebasegovia01** [comment]
@AlexeyAB i have a question. Can I pause a training, add more dataset and then train again ?. Would the new datset be taken into account?

Regards!!

**Comment by NABDroid** [comment]
Hi, Is this possible to resume training after changing height width in cfg?

**Comment by RedFlaged** [comment]
> https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects
> 
> After each 100 iterations you can stop and later start training from this point. For example, after 2000 iterations you can stop training, and later continue training `./darknet detector train data/obj.data yolo-obj.cfg backup/yolo-obj_last.weights`

How can I continue training and keep writing to the old log file and chart continuously without deleting old log.
