### ISSUE TITLE
about the classification funetuning(not detection)

### ISSUE THREAD

**Issue by yanchao12122** [pjreddie/darknet#146]
I want to train a classification using my own data, but I don't want to train from scratch.
Can you give an example of how to fune-tune the classifcation ,using the weights trained on imagenet?  thks~!

**Comment by jinyu121** [comment]
1. Make image set. The filename should contains the object's class. For example, `123_dog_456.png`,`dog`is the class label.
1. Make train/test list. Please use absolute path.
1. Decide which network to use.
1. Download weighs file from [this page](https://pjreddie.com/darknet/imagenet/)
1. Use layers in weights file by `darknet partial CFG_FILE WEIGHTS.weights RESULT.weights HOW_MANY_LAYERS`
1. Edit the DATA_CFG file (xxx.data), replace the train/test file with your own.
1. Start training with `darknet classifier DATA_CFG NET_CFG RESULT.weights`
1. Have a cup of cafe~

**Comment by yanchao12122** [comment]
that's great, thanks a lot

**Comment by yanchao12122** [comment]
that's great, thanks a lot

**Comment by bayesianio** [comment]
How can i print Accuracy and Loss during classification training?

**Comment by EtheneXiang** [comment]
> 1. Make class name list.
> 2. Make image set. The filename should contains the object's class. For example, `dog`is the class labelof file `123_dog_456.png`.
> 3. Make train/test list. Please use absolute path.
> 4. Decide which network to use.
> 5. Download weighs file from [this page](https://pjreddie.com/darknet/imagenet/).
> 6. Use layers in weights file by `darknet partial CFG_FILE WEIGHTS.weights RESULT.weights HOW_MANY_LAYERS`.
> 7. Edit the DATA_CFG file (xxx.data), replace the train/test file with your own.
> 8. Start training with `darknet classifier DATA_CFG NET_CFG RESULT.weights`
> 9. Have a cup of cafe~

朋友，请问darknet53能做多标签分类任务吗，它的标签该怎么制作，还是和多属性分类一样吗：
1_属性1_属性2_属性n.png
或者用txt文件来装载标签
@jinyu121
