### ISSUE TITLE
nan, nan avg loss, 0.000000 rate, 99.519571 seconds, 1920 images Resizing 512 x 512,getting tis error.how to solve this?

### ISSUE THREAD

**Issue by thusharanambiar** [pjreddie/darknet#1461]

**Comment by thusharanambiar** [comment]
Getting this issue.i am using windows os and using own data set. I have only 52 datas. when it reach at 50th iteration getting nan values for avg loss. How to solve this issue.

**Comment by fiorano10** [comment]
How did you solve it?

**Comment by xzessmedia** [comment]
why don't people just understand that **sharing the results gives issues and threads a sense..**
how can you do your job if you don't understand this simple thing which didn't change since 20 years
