### ISSUE TITLE
Error with when OPENCV=1 ,

### ISSUE THREAD

**Issue by dingxihao1991** [pjreddie/darknet#1492]
`g++ -Iinclude/ -Isrc/ -DOPENCV pkg-config --cflags opencv -DGPU -I/usr/local/cuda/include/ -Wall -Wno-unused-result -Wno-unknown-pragmas -Wfatal-errors -fPIC -Ofast -DOPENCV -DGPU -c ./src/image_opencv.cpp -o obj/image_opencv.o Package opencv was not found in the pkg-config search path. Perhaps you should add the directory containingopencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found
./src/image_opencv.cpp:5:30: fatal error: opencv2/opencv.hpp: No such file or directory
compilation terminated.
Makefile:86: recipe for target 'obj/image_opencv.o' failed
make: *** [obj/image_opencv.o] Error 1`

我的conda 环境里已经conda install opencv=3.4.1 , 但是仍然报opencv 找不到。why?

**Comment by Eralien** [comment]
你解决了吗？是怎么解决的啊

**Comment by dingxihao1991** [comment]
> 你解决了吗？是怎么解决的啊

我解决了，我用pip 安装了opencv ， 反正就是opencv 库的问题
