### ISSUE TITLE
Add new attribute to yolov3

### ISSUE THREAD

**Issue by Choco83** [pjreddie/darknet#1495]
I want to modify yolo in a way that it is able to predict depth/distance of bounding box as well. I have modified data.c to read depth as well. My question is what changes I need to make in network to get desired results?
Do I just need to change yolo layer to also account for depth, or does any other layer needs to be changed too?

**Comment by ted8201** [comment]
yolo can not predict box position precisely.

**Comment by Choco83** [comment]
@ted8201 I know, but what I want is to add extra attribute. So Yolo would output:

1. Class
2. Bounding box (x, y, w, h)
3. Distance of bounding box (from Camera)

**Comment by abhigoku10** [comment]
@Choco83  where you successful in getting this integrated and make it work so that it would be helpful if you could givesome pointers

**Comment by Choco83** [comment]
@abhigoku10 yes I was able to do so, you can find the code [here](https://github.com/Choco83/darknet).

**Comment by hongquang9** [comment]
hi Choco83,
Could you please provide pre-trained model + config file for you demo?

**Comment by hongquang9** [comment]
@Choco83 
It is very kind if you can share your demo.
Thank in advance!

**Comment by abhigoku10** [comment]
@Choco83 did u test it on any open source dataset ??

**Comment by Choco83** [comment]
@hongquang9 I can share a config file, will look if I have a pre-trained model (been a while since I looked at it), but might take a couple of days.
@abhigoku10 getting distance of humans from open source datasets is a bit of hassle, and requires extra work (at least from datasets I looked into), for testing and training I had in-house simulation data generated for this purpose.

**Comment by hongquang9** [comment]
Hi @Choco83,
Could you please share your demo?
Thank so much.

**Comment by Choco83** [comment]
Hey @hongquang9 
https://drive.google.com/open?id=1F83jSWbGJhR1mTz5h-1XQw2oZLGaMigt
A small demo on simulation as I trained on simulation, generalization on real-world data wasn't very impressive

**Comment by hongquang9** [comment]
Thank @Choco83  for your sharing.

**Comment by abhigoku10** [comment]
@Choco83  thanks for sharing the code base the results are very impressive, i have a few queries 
1. which dataset did u use for training 
2. the distance parameter was already there with the dataset or u annotated it if so with what reference point
