### ISSUE TITLE
Ryzen vs Intel ?

### ISSUE THREAD

**Issue by bertalanimre** [pjreddie/darknet#1510]
Which CPU would you Lads recommend for the application to recognize animals mainly from images ? I mean, is there any actual benefit from choosing one over the other?

**Comment by vadash** [comment]
cpu doesnt matter. GPU depends on model u need. Second hand GTX1060/70/80 or new RTX 2060

**Comment by bertalanimre** [comment]
Cheers! I was expecting it. I guess RX 580 and other AMD graphic cards are out of the question because of the lack of CUDA cores?

**Comment by vadash** [comment]
> Cheers! I was expecting it. I guess RX 580 and other AMD graphic cards are out of the question because of the lack of CUDA cores?
yep even bad 1050 is better for yolo than 580

**Comment by bertalanimre** [comment]
Thanks for the info! We love your work. :) We only miss wild animal recognition but we are working on it. ;)
