### ISSUE TITLE
Floating point exception (core dumped) while using Deconvolutional layer

### ISSUE THREAD

**Issue by mangohurricane** [pjreddie/darknet#1515]
I changed the upsample layer into Deconvolution layer, training is ok. When I test the model, it got the following error:
 51 conv     64  1 x 1 / 1    13 x  13 x  64   ->    13 x  13 x  64  0.001 BFLOPs
   52 activation: Using default 'logistic'
deconv  128  2 x 2 / 2    13 x  13 x  64   ->    26 x  26 x 128
   53 route  52 31
   54 conv     64  1 x 1 / 1    26 x  26 x 192   ->    26 x  26 x  64  0.017 BFLOPs
   55 conv     64  3 x 3 / 1    26 x  26 x  64   ->    26 x  26 x  64  0.050 BFLOPs
   56 conv     64  1 x 1 / 1    26 x  26 x  64   ->    26 x  26 x  64  0.006 BFLOPs
   57 conv     64  3 x 3 / 1    26 x  26 x  64   ->    26 x  26 x  64  0.050 BFLOPs
   58 conv     64  1 x 1 / 1    26 x  26 x  64   ->    26 x  26 x  64  0.006 BFLOPs
   59 conv     64  3 x 3 / 1    26 x  26 x  64   ->    26 x  26 x  64  0.050 BFLOPs
   60 conv     18  1 x 1 / 1    26 x  26 x  64   ->    26 x  26 x  18  0.002 BFLOPs
   61 yolo
Loading weights from /home/yjx/darknet/backup321DE/yolov3tinyDE.backup...Floating point exception (core dumped)

[deconvolutional]
batch_normalize=1
filters = 128
size = 2
stride = 2
pad = 0
activation=leaky

this is what I changed in cfg file

Any help would be appreciated  :)

**Comment by GYC1996** [comment]
I meet the same problem with you

**Comment by mangohurricane** [comment]
> I meet the same problem with you

It works now, something wrong with l.groups. check 'yolo layer.c' in src file.

**Comment by GYC1996** [comment]
> > I meet the same problem with you
> 
> It works now, something wrong with l.groups. check 'yolo layer.c' in src file.

the problem is in yolo_layer ? where is l.groups?

**Comment by mangohurricane** [comment]
> > > I meet the same problem with you
> > 
> > 
> > It works now, something wrong with l.groups. check 'yolo layer.c' in src file.
> 
> the problem is in yolo_layer ? where is l.groups?

Sorry  I mean the deconvolutional_layer.c.  l.groups is missing while making the layer.

**Comment by SugarMasuo** [comment]
Hi, I don't understand the methdos of upsample_kernel, is it just multiplication，but what's the "scale"？whether this method is not "bilinear interpolation" ？ Thanks a lot !!! @mangohurricane @GYC1996 @pjreddie 
![image](https://user-images.githubusercontent.com/15923907/56043347-a4d9c900-5d6f-11e9-8405-78af57ba73cd.png)

**Comment by beHappy666** [comment]
@mangohurricane how do you debug this error? 3q

**Comment by beHappy666** [comment]
edit the parser.c load_convolutional_weights, add if (l.type == DECONVLUTIONAL) l.groups =1;

**Comment by hanouel** [comment]
I have the same error but I didn't change anything, I juste using my custom dataset:
![yolotraining2](https://user-images.githubusercontent.com/30502665/66212383-b9ab6f80-e6b5-11e9-93b2-8e149f645a82.png)
Any idea how to fix this? thanks :)

**Comment by Rahn80643** [comment]
I have the same problem when I change upsample layer to deconvolution layer. I have edited parser.c load_convolutional_weights() by adding `if (l.type == DECONVLUTIONAL) l.groups =1;`. 

But I'm not sure where to add l.groups in `deconvolutional_layer.c`.

Is there other files required to be modified and which part in `deconvolutional_layer.c` should I modify ?
