### ISSUE TITLE
test example on main page does not work

### ISSUE THREAD

**Issue by salos1982** [pjreddie/darknet#159]
Hi

I've compiled darknet and trying to start to test it. I'm using command line like on testpage
./darknet yolo test cfg/yolo.cfg yolo.weights data/dog.jpg
but it founds nothing. I assume because something changed in cfg/yolo.cfg. The last layer is region layer and it has no **side** parameter. So it initialized to zero. but when array for boxes is allocated in test_yolo function it uses layer.side member that is zero. So it does not allocate anything. And as a consequence it cannot find anything.

**Comment by AlexeyAB** [comment]
Hi, `./darknet yolo test ...` is command for old Yolo v1.

For current Yolo v2 use one of the following command lines: https://github.com/AlexeyAB/darknet#how-to-use-on-the-command-line
1. `./darknet detector test ./cfg/coco.data ./cfg/yolo.cfg ./yolo.weights`
2. `./darknet detector demo ./cfg/voc.data ./cfg/yolo-voc.cfg ./yolo-voc.weights test50.mp4 -i 0 -thresh 0.2`
3. `./darknet detector demo ./cfg/voc.data ./cfg/yolo-voc.cfg ./yolo-voc.weights http://192.168.0.80:8080/video?dummy=param.mjpg -i 0`

**Comment by salos1982** [comment]
Could you modify documentation to describe differences

**Comment by jacob7182** [comment]
when running the command ./darknet detector test ./cfg/coco.data ./cfg/yolo.cfg ./yolo.weight on Windows machine and using cygwin, it gives the error  Couldn't open file: data/coco.names

**Comment by AlexeyAB** [comment]
@jacob7182 You can use this fork on Windows without cygwin and this will work: https://github.com/AlexeyAB/darknet

**Comment by jacob7182** [comment]
ok, does it require VS2015 to build the solution?  I used make using cygwin to build the solution on https://github.com/pjreddie/darknet

**Comment by AlexeyAB** [comment]
@jacob7182 Yes, it can be successfully compiled by using VS2015.
Also it can be compiled using `make` on Linux, but I didn't test it to compile using Cygwin.

**Comment by salos1982** [comment]
I"ve created my own port to Visual Studio 2015. You can use from my repository

**Comment by jacob7182** [comment]
@AlexeyAB , i was able to run https://github.com/AlexeyAB/darknet using CYGWIN and the command ./darknet detector test ./cfg/coco.data ./cfg/yolo.cfg ./yolo.weights  and the detection worked fine.
thanks.

**Comment by nathan-c** [comment]
If you are running Ubuntu Bash on Windows check your line endings are UNIX (\n) and not WINDOWS (\r\n).
