### ISSUE TITLE
No package 'opencv' found - opencv@3 (3.4.5)

### ISSUE THREAD

**Issue by chaitanyabhardwaj** [pjreddie/darknet#1597]
I've been trying to compile darknet with opencv and running `sudo make` gives the following error:

    gcc -Iinclude/ -Isrc/ -DOPENCV `pkg-config --cflags opencv`  -Wall -Wno-unused-result -Wno-unknown-pragmas -Wfatal-errors -fPIC -Ofast -DOPENCV obj/captcha.o obj/lsd.o obj/super.o obj/art.o obj/tag.o obj/cifar.o obj/go.o obj/rnn.o obj/segmenter.o obj/regressor.o obj/classifier.o obj/coco.o obj/yolo.o obj/detector.o obj/nightmare.o obj/instance-segmenter.o obj/darknet.o libdarknet.a -o darknet -lm -pthread  `pkg-config --libs opencv` -lstdc++ libdarknet.a
    Package opencv was not found in the pkg-config search path.
    Perhaps you should add the directory containing `opencv.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'opencv' found

opencv@3 is installed with homebrew and added to the `PATH`
`/usr/local/opt/opencv@3/bin`

`PKG_CONFIG_PATH` is also added
`/usr/local/opt/opencv@3/lib/pkgconfig: is a directory`

The weird part is, running `pkg-config --cflags --libs opencv` displays the libs and all the files correctly and `pkg-config --list-all` also displays `opencv` in the list, but the `Makefile` can't find it.

Also, I'm _getting another error_ in the aftermath of the above(probably)

    Undefined symbols for architecture x86_64:
        "cvIplImage(cv::Mat const&)", referenced from:
            _mat_to_image in libdarknet.a(image_opencv.o)
        "cv::cvarrToMat(void const*, bool, bool, int, cv::AutoBuffer<double, 136ul>*)", referenced from:
            _image_to_mat in libdarknet.a(image_opencv.o)
        "cv::moveWindow(cv::String const&, int, int)", referenced from:
            _make_window in libdarknet.a(image_opencv.o)

**Comment by raytron** [comment]
I was able to get this working on Arch 5.0.10

-Built Opencv3 from source.
cmake ..
make 
sudo make install

-Copied opencv.pc located in build/unix-install into /usr/share/pkgconfig

I needed PATH=$PATH:/opt/cuda/bin' for nvcc as well.

Compiled darknet with gpu=1 and opencv=1 without issue.
