### ISSUE TITLE
a little question about the argv[]

### ISSUE THREAD

**Issue by FourierTransform** [pjreddie/darknet#1599]
I can compile correctly and when I run the program via cmd,For examplt I type "darknet.exe detector demo data/coco.data yolov3.cfg yolov3.weights",it worked well.But when I start to debug it(I assign value to argv via project properties),it can't work.I found There is a piece of code to open the file via argv[],and the argv[3] is data\coco.data,so fopen() can't find right path,but I also found when it works normally(when it can open the file) the filename is the same as former.
I don't why the they have the same filename,but when I assign value to argv[] via project properties it can't find the right path.I hope someone who understands this can help me....

![QQ图片20190504090816](https://user-images.githubusercontent.com/31101482/57172115-5ee3c280-6e4e-11e9-96cf-0e2cf36363ef.png)
![QQ图片20190504090821](https://user-images.githubusercontent.com/31101482/57172116-5ee3c280-6e4e-11e9-8fd5-ddadbf414c7a.png)
![QQ图片20190504090824](https://user-images.githubusercontent.com/31101482/57172117-5f7c5900-6e4e-11e9-928a-6c171bd1d2e5.png)

**Comment by ustcxiayu** [comment]
maybe because of the absolute path and relative path?

**Comment by FourierTransform** [comment]
> maybe because of the absolute path and relative path?

yeah...I found the location of fopen changed because of the version of the compiler,any way,thanks
