### ISSUE TITLE
ShowImage in Compiled Darknet

### ISSUE THREAD

**Issue by ServerSideClient** [pjreddie/darknet#1601]
I'm working on a personal project with darknet running on a server.
The problem is that it crashes every time it's finished with the predictions, because it can't open the file. 
Is there anything in the config I can change so that the "predictions.jpg" doesn't open after the process has completed?

**Comment by Liedermaus** [comment]
Did you check with OPENCV switched off in the Makefile ?

OPENCV=0

**Comment by ServerSideClient** [comment]
Ah, no.
I completely forgot about that, but it works now.
Thank you very much.
