### ISSUE TITLE
darknet.h compile error

### ISSUE THREAD

**Issue by suoyita** [pjreddie/darknet#1602]
Hi, I am trying to use yolov3 in my own project and I included darknet.h. When I try to compile the project, it reported error in darknet.h:

`darknet/include/darknet.h:605:1: error: reference to ‘list’ is ambiguous
 list *read_data_cfg(char *filename);`

I don't know why it happens, could you help me fix this error?
I am using Ubuntu 16.04, cuda 9.0 and opencv 3.4.0.
Thank you!

**Comment by thxmxx** [comment]
Did you solve this without using a custom wrapper?

**Comment by Chuck-Yu** [comment]
I got the same error in my project. Could you tell me how you solved this issue? 

Thanks.

**Comment by dmg206** [comment]
Namespace pollution. std::list conflict with struct list in darknet. the solution is not using namespace std in code
