### ISSUE TITLE
What are the differences between upsample layer and deconvolution layer

### ISSUE THREAD

**Issue by BDHU** [pjreddie/darknet#1607]
I'm trying to understand what both layers are trying to achieve, but I found it a bit hard to understand them. A lot of tutorials also mixed the meaning of upsample and deconvolution together. What are their differences in darket's implementation?

**Comment by Francis-Xia** [comment]
@BDHU The  function is same, and deconv has trainable para, but upsample dose not have.

**Comment by spaul13** [comment]
Are deconvolution and transposeconvolution same thing? 
For upsample, is there any way to specify the output upsampled size directly? (is it just like enhancing the resolution of the input image via interpolation?)
