### ISSUE TITLE
Train Yolov3 for more than 80 classes?

### ISSUE THREAD

**Issue by KLiFF2606** [pjreddie/darknet#1617]
Hi,

I am trying to retrain yolov3 on a dataset with 120 classes.

Is it enough to just put classess=120 in the coco.data file? Or do I need to make other changes?

The training itself is running but when I try to make a prediction with 120 as the number of classes I get this error:
`python: malloc.c:2401: sysmalloc: Assertion '(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.`

**Comment by AlexeyAB** [comment]
@KLiFF2606 Hi,

Read this manual: https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects

**Comment by KLiFF2606** [comment]
Thank you @AlexeyAB that was indeed the things to do.
