### ISSUE TITLE
Training speed (FPS) dropped sharply during training

### ISSUE THREAD

**Issue by mushan09** [pjreddie/darknet#1628]
train yolov3 with batch=64 gpu=8, the speed will go down after a fixed step(in my server is 178k steps). In order to make the results intuitive, i draw a picture to show the speed as follows.
![time](https://user-images.githubusercontent.com/15165958/58308770-0e4ffb80-7e35-11e9-966f-7652b1823e6a.jpg)
The average gpu utilization is about 80% in first 178k steps and 20% after 178k steps.
This problem did not occur when the gpu was 4.
Anybody knows the reason?

**Comment by Liedermaus** [comment]
Yes, that is normal.
After a fixed number of steps the network is resizing and ifthe size is big it gets slow ...

**Comment by mushan09** [comment]
@Liedermaus Thank you for your reply, but I don't think this is the right reason.
