### ISSUE TITLE
Can't find src/yolo.c after clone from git

### ISSUE THREAD

**Issue by gitDawn** [pjreddie/darknet#163]
Instructions for retraining at [https://github.com/pjreddie/darknet/wiki/YOLO:-Real-Time-Object-Detection] says "Edit src/yolo.c", and I can't find this file in the repository cloned from github.

I'm using  git clone https://github.com/pjreddie/darknet.git for cloning.
Any help on this?

Thanks,
Shahar

**Comment by ni9elf** [comment]
The documentation might me outdated. The file is in the directory `examples`.

**Comment by AlexeyAB** [comment]
@gitDawn Use this manual to train Yolo for your custom objects: https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects

**Comment by gitDawn** [comment]
@AlexeyAB Thanks, the tutorial you've sent is far better for different number of classes. Now waiting for the results.
