### ISSUE TITLE
can yolov3 detect tiny objects

### ISSUE THREAD

**Issue by mohamadian123-Sadegh** [pjreddie/darknet#1644]
[Hi])

I've got a question in the term of tiny objects. 
Can yolov3 detect small objects?? I studied some articles in this regard but I'm not sure whether it works for small objects less than 30*30 pixels or not??? if it can how should I change parameters for anchor box and aspect ratios to implement this???????? 
thanks

**Comment by springkim** [comment]
Of course it is possible.
Change the anchor box to a smaller size and detect it after learning. Changing only the anchor box for a network that has already been learned may not work well.

The input resolution of the neural network should be such that the size of the object is at least 10px when resized.

For example, if you want to detect objects of 50x50 size from 1920x1080 to 1024x576, you can change the input resolution to 1024x576, and you can get good results.

**Comment by Vinod-Koli** [comment]
@springkim 

> Change the anchor box to a smaller size and detect it after learning. **Changing only the anchor box for a network that has already been learned may not work well.**

So after changing anchor boxes, the network should be retrained using transfer learning, Am I right ?

**Comment by zhangcong2019** [comment]
I think so.

> 
> 
> @springkim
> 
> > Change the anchor box to a smaller size and detect it after learning. **Changing only the anchor box for a network that has already been learned may not work well.**
> 
> So after changing anchor boxes, the network should be retrained using transfer learning, Am I right ?
