### ISSUE TITLE
yolov3 tiny inaccurate object coordinates

### ISSUE THREAD

**Issue by kingjam3s** [pjreddie/darknet#1654]
I have low loss and high mAP and the recognition is fine but the object coordinates that returned from the network is inaccurate.

Exmaple:
I have the RED, I want the GREEN.
![image](https://user-images.githubusercontent.com/49540138/59152104-516db980-8a46-11e9-940e-a00a79a1f88f.png)

The network is only predicting the red area and because of that It is sometimes gets wrong results. Why is that happening?

**Comment by ghasemabdi** [comment]
The problem is because of the nominated image size in "cv2.dnn.blobFromImage" line. Based on your net, choose the best size. Hope to be solved the problem.

**Comment by kingjam3s** [comment]
The problem was the annotations.
