### ISSUE TITLE
object_scale and noobj_scale in YOLO v3?

### ISSUE THREAD

**Issue by duanzhiihao** [pjreddie/darknet#1669]
Hi, could you share your training process of YOLO v3?

I can't reproduce the mAP when I training my own YOLO v3. My mAP[iou=50] is like 30 on COCO. If anyone can reproduce the results(mAP[iou=50] 50~60 on COCO), could you share your settings of `object_scale, noobject_scale, class_scale, coord_scale`, and data augmentations?

I can't find them in the [yolov3.cfg](https://github.com/pjreddie/darknet/blob/master/cfg/yolov3.cfg) and [yolov3 report](https://pjreddie.com/media/files/papers/YOLOv3.pdf).

**Comment by ethanyanjiali** [comment]
I don't see these scales in forward_yolo_layer any more. My guess is that the author realized that these scales are useless but didn't want to mention it in the paper.
