### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by brizey02** [pjreddie/darknet#167]
Trying to train on cifar_small
./darknet classifier train cfg/cifar.data cfg/cifar_small.cfg backup/cifar_small.backup
cifar_small
1
layer     filters    size              input                output
    0 conv     32  3 x 3 / 1    28 x  28 x   3   ->    28 x  28 x  32
    1 max          2 x 2 / 2    28 x  28 x  32   ->    14 x  14 x  32
    2 conv     64  3 x 3 / 1    14 x  14 x  32   ->    14 x  14 x  64
    3 max          2 x 2 / 2    14 x  14 x  64   ->     7 x   7 x  64
    4 conv    128  3 x 3 / 1     7 x   7 x  64   ->     7 x   7 x 128
    5 conv     10  1 x 1 / 1     7 x   7 x 128   ->     7 x   7 x  10
    6 avg                        7 x   7 x  10   ->    10
    7 softmax                                          10
    8 cost                                             10
Loading weights from backup/cifar_small.backup...Couldn't open file: backup/cifar_small.backup
briz@dlp:~/darkn

**Comment by hahazhky** [comment]
how did you solve it? I have the same problem
