### ISSUE TITLE
How to save only detected part of the image

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [pjreddie/darknet#1673]
Hello, 
         I am running the YOLO model for the single object detection in the image and it detects my target object successfully and save the output but I want to crop and save only detected part rather than full image again, How can I do this? Can anyone help me with this problem?  I am detecting LCD from a given image and I am using this github repo for YOLLO.  https://github.com/AlexeyAB/darknet

**Comment by EtheneXiang** [comment]
while you got the coordinates of your  target object, u can use C/OPENCV to crop the target from your input image. like this: this example is for c++
Mat img= imread（image）；
Rect rect(50,20, 200, 50);
Mat ROI = img(rect);
imshow("ROI_WIN",ROI);

**Comment by mehio** [comment]
How do you get the coordinates of the bounding box?

**Comment by MuhammadAsadJaved** [comment]
@EtheneXiang @mehio 
Thank you I found the solution.   add these lines in the image.c file after line 448.

image c1 = crop_image(im, left, top, right-left, bot-top);
save_image(c1, "99");

**Comment by ManthanJoshi26** [comment]
@MuhammadAsadJaved  it's not working for me. I have an image for 3 classes so how can I implement it???

**Comment by EtheneXiang** [comment]
> How do you get the coordinates of the bounding box?
the ouput of yourself detection CNN

**Comment by EtheneXiang** [comment]
> @MuhammadAsadJaved it's not working for me. I have an image for 3 classes so how can I implement it???



> @MuhammadAsadJaved it's not working for me. I have an image for 3 classes so how can I implement it???
It has nothing to do with classes, as long as you have the coordinates, that's fine

**Comment by harshagarg09** [comment]
In order to crop multiple objects having different labels in a single image, replace "image.c" file in "src" folder with my image.c file. It will crop the detected objects and save them in <label_name>.jpg format corresponding to different labels. 

[image.zip](https://github.com/pjreddie/darknet/files/4895891/image.zip)

**Comment by dancassin** [comment]
> In order to crop multiple objects having different labels in a single image, replace "image.c" file in "src" folder with my image.c file. It will crop the detected objects and save them in <label_name>.jpg format corresponding to different labels.
> 
> [image.zip](https://github.com/pjreddie/darknet/files/4895891/image.zip)

FYI - after downloading this file, and running "make" again I received this error
gcc -Iinclude/ -Isrc/ -Wall -Wno-unused-result -Wno-unknown-pragmas -Wfatal-errors -fPIC -Ofast -c ./src/image.c -o obj/image.o
./src/image.c:7:10: fatal error: 'dark_cuda.h' file not found
#include "dark_cuda.h"
         ^~~~~~~~~~~~~
1 error generated.
make: *** [obj/image.o] Error 1
