### ISSUE TITLE
Transfer learning in classification

### ISSUE THREAD

**Issue by cansozbir** [pjreddie/darknet#1687]
Hello,
I did a model with the same config of darknet-19 (except the last layer for class output number) and trained it. Now, what I want to do is it should be start with the darknet19's original weights and I just want to train it's last few layers. But I can't find any resource about that. Can someone help me ?

Also, I have 10 classes in the dataset for example and let's say the original darknet19 is 50 classes. I don't want to lose the 50 classes also. I want to get a output from 60 classes. Is it possible with just 10 classes dataset or should i download 60 classes dataset for that ?

**Comment by shebna12** [comment]
@cansozbir were you able to figure this out? i'm stuck with the same problem.  :(

**Comment by cansozbir** [comment]
For the first question, there was a way to freeze some layers and train the rest. The second, I couldn't and also I don't think it is possible. And sorry, I don't remember how did I solve the first, it's been a while.
