### ISSUE TITLE
Multiple images in one Darknet process

### ISSUE THREAD

**Issue by martisaju** [pjreddie/darknet#1694]
Hello,
There is any manner to just execute one Darknet process and test multiple images (one at each iteration)?

I have a loop iteration where at each iteration a new image is taken. I just want to test each image avoiding to re-run Darknet.

Thank you so much!

**Comment by harsh52** [comment]
You need to make a python/bash script to do that.
just google it you will find plenty of results.
early i have the same issue.
Thanks.

**Comment by martisaju** [comment]
Hi @harsh52 I finally achieved it by using ‘pexpect’ library. This library allows running an external process from a python script and then send commands to that process.

**Comment by AjayBhat29** [comment]
> Hello, There is any manner to just execute one Darknet process and test multiple images (one at each iteration)?
> 
> I have a loop iteration where at each iteration a new image is taken. I just want to test each image avoiding to re-run Darknet.
> 
> Thank you so much!



> Hello, There is any manner to just execute one Darknet process and test multiple images (one at each iteration)?
> 
> I have a loop iteration where at each iteration a new image is taken. I just want to test each image avoiding to re-run Darknet.
> 
> Thank you so much!

Can you please show a snapshot of the for loop to run darknet on multiple images?

**Comment by martisaju** [comment]
Hi @AjayBhat29 
![darknet_ex](https://user-images.githubusercontent.com/29142274/160362567-edbd0ce2-c6bc-46e7-8c63-8b088f0885fd.jpg)
