### ISSUE TITLE
Resume training COCO 2014 using yolov3.weights

### ISSUE THREAD

**Issue by herleeyandi** [pjreddie/darknet#1696]
Hello, everyone, 

I tried to retrain yolov3 using my own dataset which contains 80 classes similar to coco. However when I try to initialize the weights using the pretrained yolov3 model in coco with filename `yolov3.weights` it just stops the process after initialize the weights. So anyone can resume the training from yolov3 coco model? or anyone has the author @pjreddie `yolov3.backup` file for resuming coco training?

-Thanks-

```
OPs
  100 conv    256  3 x 3 / 1    52 x  52 x 128   ->    52 x  52 x 256  1.595 BFLOPs
  101 conv    128  1 x 1 / 1    52 x  52 x 256   ->    52 x  52 x 128  0.177 BFLOPs
  102 conv    256  3 x 3 / 1    52 x  52 x 128   ->    52 x  52 x 256  1.595 BFLOPs
  103 conv    128  1 x 1 / 1    52 x  52 x 256   ->    52 x  52 x 128  0.177 BFLOPs
  104 conv    256  3 x 3 / 1    52 x  52 x 128   ->    52 x  52 x 256  1.595 BFLOPs
  105 conv    258  1 x 1 / 1    52 x  52 x 256   ->    52 x  52 x 258  0.357 BFLOPs
  106 yolo
Loading weights from backup/yolov3.weights...Done!
Learning Rate: 0.001, Momentum: 0.9, Decay: 0.0005
Saving weights to coco_brocoly/yolov3_tree_final.weights
```

**Comment by DeepNoob** [comment]
Just a guess but if it exists without any error reporting it might be the issue.
The Yolo cfg file contains a parameter called max_batches.
If the seen parameter (the parameter saved into the weights file stating how many batches were already performed to achieve these weights) equals to or greater than max_batches it will exit immediately.

As a quick test you can change max_batches in the relevant cfg file to a larger number (say x10 the existing number which is ~500K by default) and see if training continues. If it does - you may also want to update the lr schedule (steps)

**Comment by herleeyandi** [comment]
Solved, thank you so much @DeepNoob .
