### ISSUE TITLE
How to use GPU model on CPU.

### ISSUE THREAD

**Issue by Michi-123** [pjreddie/darknet#1710]
I want to train Yolo V3 on GPU, and I want to use it on CPU machine. 
Is it possible?  Then, how do it?

**Comment by harsh52** [comment]
if you have GPU installed on your system with proper configuration of CUDA and cuDNN.
Then YES you can you GPU on cpu machine.

**Comment by Michi-123** [comment]
Thanks!
But I don't have GPU machine. So I trained 'YOLO' on 'Google Colab' and I want to use it on my local machine. 

Actually, I tried this method, but I got different (not trained) result. I'm afraid the logic of GPU mode is different with CPU mode.

**Comment by xzessmedia** [comment]
using gpu/cpu mode depends on your compilation of darknet after the weights has been calculated and you trained your model its not limited to gpu or cpu..
the weights will always be the same and are unrelated to your compilation of darknet no matter if its compiled for cpu or gpu
