### ISSUE TITLE
Problem running yolo+darnet with CUDA toolkit 8 on Ubuntu 17.04

### ISSUE THREAD

**Issue by frixhub** [pjreddie/darknet#172]
Good day,

I'm running ubuntu 17.04 (64-bit) on an Intel i7-3820 CPU@3.60GHz with
a GeForce GTX 650 with 1GB of DDR5.
I've cloned the latest github revision (2017/08/03, with commit 1e72980) of darknet and 
downloaded the weight files.

I can successfully build darknet for cpu using opencv (Makefile option OPENCV) and
running "./darknet detect cfg/yolo.cfg weights/yolo.weights data/dog.jpg" resulted in the
dog, bicycle and truck being identified successfully. It took 14 seconds to process. The
output is attached in: [darnet_cpu_only.txt](https://github.com/pjreddie/darknet/files/1256973/darnet_cpu_only.txt)

I would like to get the CUDA features activated. I've downloaded nvidia toolkit 8. The
Nvidia kernel module (375) that ships with the toolkit didn't compile. NVidia ver 384.69
build out of the box. I'm using Nvidia 384 on kernel 4.10.0-32
I've extracted the toolkit and samples from the installer by passing the -extract=PATH
option. The toolkit & samples installed successfully. The samples compiled after creating
a symbolic link from /usr/local/cuda/bin/gcc to /usr/bin/gcc-5. Ubuntu 17.04 by default
ships with gcc-6, which nvcc doesn't support yet. The samples runs successfully, as
can be seen in [deviceQuery.txt]
(https://github.com/pjreddie/darknet/files/1256976/deviceQuery.txt)

Software versions:
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61

$ cat /proc/driver/nvidia/version 
NVRM version: NVIDIA UNIX x86_64 Kernel Module  384.69  Wed Aug 16 19:34:54 PDT 2017
GCC version:  gcc version 6.3.0 20170406 (Ubuntu 6.3.0-12ubuntu2) 

In order to compile darknet with CUDA support, I've set the following in the
Makefile: GPU=1 and CC=gcc-5. The compilation was successful.

When running the GPU enabled darknet binary with the '-nogpu' option,
the following peculiarity happens: All models (dog, truck, etc) are matched
with a probability of higher than 4000%+ -- Clearly something has gone wrong.
The output is attached in:
[darknet_nogpu.txt](https://github.com/pjreddie/darknet/files/1256975/darknet_nogpu.txt)

When running the GPU enabled darnet binary without the '-nogpu' switch
(in order to utilise the GPU) an 'out of memory' error occurred at step 18.
The output is attached in:
[darknet_gpu.txt](https://github.com/pjreddie/darknet/files/1256974/darknet_gpu.txt)

How much RAM does darnet/yolo require to process a single image?
Does darnet+yolo support Nvidia toolkit 8 or only 7.5?

Any help in tracking this problem down will be much appreciated.

Regards,
Frikkie

**Comment by frixhub** [comment]
Good day,
I've tested with Cuda toolkit 7.5 as well, obtaining the same result as with toolkit 8
Regards,
Frikkie

**Comment by frixhub** [comment]
Good day,

The 1GB of memory on the GeForce 650 GPU is filled up pretty quickly during the initial Malloc calls.
I've printed the available memory in cuda_set_device() at startup.
  ./src/cuda.c:30: Available memory: 631 / 1022 (MB)
-- 370MB of GPU RAM is already occupied when darknet start to execute. Is this normal?

Inside cuda_make_array() I've printed the available RAM before & after each Malloc(), as well
as the size of the Malloc call. By the time that layer 18 is executed the GPU is out of memory:

  17 ./src/cuda.c:122: Available memory: 8 / 1022 (MB) before malloc()
      ./src/cuda.c:124: Malloc 0 MB
     ./src/cuda.c:134: Available memory: 7 / 1022 (MB) after malloc()

    ./src/cuda.c:122: Available memory: 7 / 1022 (MB) before malloc()
    ./src/cuda.c:124: Malloc 0 MB
   ./src/cuda.c:134: Available memory: 6 / 1022 (MB) after malloc()

   max          2 x 2 / 2    38 x  38 x 512   ->    19 x  19 x 512
   18 ./src/cuda.c:122: Available memory: 6 / 1022 (MB) before malloc()
   ./src/cuda.c:124: Malloc 18 MB
   ./src/cuda.c:126: CUDA Error: out of memory
   darknet: ./src/cuda.c:52: check_error: Assertion `0' failed.

Apart from the initial GPU memory that isn't all available, how much RAM
would normally be required to run darknet on a single image?

Regards,
Frikkie

**Comment by frixhub** [comment]
Good day,

I've altered cuda_make_array() in cuda.c to use the PC RAM via zero-copy if the
GPU memory is full. The time came down from 14 seconds to 1.08 seconds
when using the GPU+PC_RAM instead of CPU only :)
I'm not sure why the GPU reports that only 625 of 1022 MB of RAM is available
at program startup :(
This was tested successfully 

with CUDA toolkit 7.5 and 8.0

The output of the command is as follow:
./darknet detect cfg/yolo.cfg weights/yolo.weights data/dog.jpg

./src/cuda.c:33: Available memory: 625 / 1022, PC RAM used: 0 (MB)

layer     filters    size              input                output
    0 conv     32  3 x 3 / 1   608 x 608 x   3   ->   608 x 608 x  32
    1 max          2 x 2 / 2   608 x 608 x  32   ->   304 x 304 x  32
    2 conv     64  3 x 3 / 1   304 x 304 x  32   ->   304 x 304 x  64
    3 max          2 x 2 / 2   304 x 304 x  64   ->   152 x 152 x  64
    4 conv    128  3 x 3 / 1   152 x 152 x  64   ->   152 x 152 x 128
    5 conv     64  1 x 1 / 1   152 x 152 x 128   ->   152 x 152 x  64
    6 conv    128  3 x 3 / 1   152 x 152 x  64   ->   152 x 152 x 128
    7 max          2 x 2 / 2   152 x 152 x 128   ->    76 x  76 x 128
    8 conv    256  3 x 3 / 1    76 x  76 x 128   ->    76 x  76 x 256
    9 conv    128  1 x 1 / 1    76 x  76 x 256   ->    76 x  76 x 128
   10 conv    256  3 x 3 / 1    76 x  76 x 128   ->    76 x  76 x 256
   11 max          2 x 2 / 2    76 x  76 x 256   ->    38 x  38 x 256
   12 conv    512  3 x 3 / 1    38 x  38 x 256   ->    38 x  38 x 512
   13 conv    256  1 x 1 / 1    38 x  38 x 512   ->    38 x  38 x 256
   14 conv    512  3 x 3 / 1    38 x  38 x 256   ->    38 x  38 x 512
   15 conv    256  1 x 1 / 1    38 x  38 x 512   ->    38 x  38 x 256
   16 conv    512  3 x 3 / 1    38 x  38 x 256   ->    38 x  38 x 512
   17 max          2 x 2 / 2    38 x  38 x 512   ->    19 x  19 x 512
   18 conv   1024  3 x 3 / 1    19 x  19 x 512   ->    19 x  19 x1024
   19 conv    512  1 x 1 / 1    19 x  19 x1024   ->    19 x  19 x 512
   20 conv   1024  3 x 3 / 1    19 x  19 x 512   ->    19 x  19 x1024
   21 conv    512  1 x 1 / 1    19 x  19 x1024   ->    19 x  19 x 512
   22 conv   1024  3 x 3 / 1    19 x  19 x 512   ->    19 x  19 x1024
   23 conv   1024  3 x 3 / 1    19 x  19 x1024   ->    19 x  19 x1024
   24 conv   1024  3 x 3 / 1    19 x  19 x1024   ->    19 x  19 x1024
   25 route  16
   26 conv     64  1 x 1 / 1    38 x  38 x 512   ->    38 x  38 x  64
   27 reorg              / 2    38 x  38 x  64   ->    19 x  19 x 256
   28 route  27 24
   29 conv   1024  3 x 3 / 1    19 x  19 x1280   ->    19 x  19 x1024
   30 conv    425  1 x 1 / 1    19 x  19 x1024   ->    19 x  19 x 425
   31 detection
mask_scale: Using default '1.000000'
Out of GPU memory. Allocating in PC memory (slower)
./src/cuda.c:33: Available memory: 16 / 1022, PC RAM used: 555 (MB)
Loading weights from weights/yolo.weights...Done!
./src/cuda.c:33: Available memory: 16 / 1022, PC RAM used: 555 (MB)
e
data/dog.jpg: Predicted in 1.082277 seconds.
dog: 82%
truck: 64%
bicycle: 85%

The updated src/cuda.c file is attached in ZIP format [cuda.c.zip](https://github.com/pjreddie/darknet/files/1257529/cuda.c.zip)

Regards,
Frikkie

**Comment by muhammetp** [comment]
what is default value for 
void check_error(const char *pcFile, int iLine, cudaError_t status)
 
in your cuda.h

**Comment by muhammetp** [comment]
since in your usage if check_error u just use only 1 parameter so means that use the default values for the rest

**Comment by shusain** [comment]
Check the output of `nvidia-smi` if it shows other processes using the GPU or memory you can kill them if you aren't using them.  Since I'm using my server basically headless through an ssh session anyhow I just shut down the regular x interface using `sudo service lightdm stop` just like the process when installing the drivers.  This leaves `nvidia-smi` showing 0MB/6GB used on my 1060, unfortunately I'm still hitting the out of memory errors when running these config/weight combos: Extraction, Darknet19, and jnet for nightmare output (VGG works though I don't have the interface for it working yet).  I put together a web interface you can use here: http://darknet.shaunhusain.com it's pretty basic but also learning the basics of react/redux while playing with these libraries.
