### ISSUE TITLE
error while training....

### ISSUE THREAD

**Issue by sdimantsd** [pjreddie/darknet#1728]
Hi, when i training i get the following msg:

...
...
...
Loaded: 0.022302 seconds
Region 16 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.499806, .5R: -nan, .75R: -nan,  count: 0
Region 23 Avg IOU: 0.222566, Class: 0.499086, Obj: 0.499633, No Obj: 0.498671, .5R: 0.000000, .75R: 0.000000,  count: 11
Region 16 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.499806, .5R: -nan, .75R: -nan,  count: 0
Region 23 Avg IOU: 0.197150, Class: 0.499030, Obj: 0.499404, No Obj: 0.498674, .5R: 0.000000, .75R: 0.000000,  count: 11
39: 370.269501, 426.833069 avg, 0.000000 rate, 0.089274 seconds, 858 images
Loaded: 0.032525 seconds
Region 16 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.499805, .5R: -nan, .75R: -nan,  count: 0
Region 23 Avg IOU: 0.206086, Class: 0.498751, Obj: 0.499013, No Obj: 0.498672, .5R: 0.000000, .75R: 0.000000,  count: 11
Region 16 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.499805, .5R: -nan, .75R: -nan,  count: 0
Region 23 Avg IOU: 0.191005, Class: 0.498909, Obj: 0.499274, No Obj: 0.498655, .5R: 0.000000, .75R: 0.000000,  count: 11
40: 369.967102, 421.146484 avg, 0.000000 rate, 0.123250 seconds, 880 images
Resizing
576
Loaded: 0.000021 seconds
Region 16 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.499841, .5R: -nan, .75R: -nan,  count: 0
Region 23 Avg IOU: 0.251642, Class: 0.498222, Obj: 0.498088, No Obj: 0.498676, .5R: 0.000000, .75R: 0.000000,  count: 11
Region 16 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.499841, .5R: -nan, .75R: -nan,  count: 0
Region 23 Avg IOU: 0.234810, Class: 0.498649, Obj: 0.498792, No Obj: 0.498677, .5R: 0.000000, .75R: 0.000000,  count: 11
41: 608.707214, 439.902557 avg, 0.000000 rate, 0.172673 seconds, 902 images
Loaded: 0.000017 seconds
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 140) > this->size() (which is 0)
Aborted (core dumped)

can you help me solv it? Thanks!

**Comment by smallworld-network-wupeng** [comment]
me too

**Comment by sdimantsd** [comment]
It's work for me. Me .txt files was in a wrong format

**Comment by smallworld-network-wupeng** [comment]
I find the problem , a image has 0 byte, I delete it , the problem was gone.

**Comment by khiemubuntu** [comment]
you needs learning rate be 0.001 step = burn in = 200
