### ISSUE TITLE
Very low framerate with 2080ti

### ISSUE THREAD

**Issue by Adham-Elarabawy** [pjreddie/darknet#1730]
I am using a 2080ti with yolov3 and even using pretrained weights and examples for yolov3 AND yolov3-tiny, I get about 6-7 fps. I have GPU, CUDA, CUDNN enabled. Is this low framerate expected with such a powerful gpu? If it is, what can I do to improve framerate (I need at least 30 fps)?

**Comment by AntoineGerardeaux** [comment]
Hi,
what was the solution, I meet the same ?
