### ISSUE TITLE
Couldn't display YOLO result via OpenCV dnn module

### ISSUE THREAD

**Issue by barzan-hayati** [pjreddie/darknet#1757]
@pjreddie 
I'm trying to train YOLO object detection via darknet and it was great for showing object via `./darknet detector test cfg/obj.data cfg/yolo-obj.cfg yolo.weights data/test.jpg`
I used 160*30 images for train and test. Also I did it via Tiny-YOLOv2 and another model and it could detect all numbers in the images. 

But when I want to showing result for trained weight and a specific image like bellow, and by using Opencv  dnn modules, I could not display all objects correctly. 

[YOLO Object Detection with OpenCV and Python]( https://www.arunponnusamy.com/yolo-object-detection-opencv-python.html)
[Deep Learning based Object Detection using YOLOv3 with OpenCV ( Python / C++)](https://www.learnopencv.com/deep-learning-based-object-detection-using-yolov3-with-opencv-python-c/)
[YOLO object detection with OpenCV](https://www.pyimagesearch.com/2018/11/12/yolo-object-detection-with-opencv/)
[YOLO object detection using OpenCV and Python](https://pysource.com/2019/06/27/yolo-object-detection-using-opencv-with-python/)
[Exploring OpenCV’s Deep Learning Object Detection Library](https://medium.com/@franky07724_57962/exploring-opencvs-deep-learning-object-detection-library-e51fe7c82246)

But when I check it for a bigger image(1280*760), It could show results.

![Input Image](https://user-images.githubusercontent.com/7418329/62410286-006ae380-b5f9-11e9-9fad-b8b6adda11c9.jpg)

**Comment by barzan-hayati** [comment]
Correct output:
![Correct Output](https://user-images.githubusercontent.com/7418329/62410349-afa7ba80-b5f9-11e9-8c2c-043748d1e83e.jpg)

**Comment by barzan-hayati** [comment]
correct output for plate detection:
![3](https://user-images.githubusercontent.com/7418329/62410612-3f9b3380-b5fd-11e9-8f05-0352dabf99f4.jpg)

**Comment by barzan-hayati** [comment]
@AlexeyAB Thanks for your respond. 
I solved it. When we want to showing result using opencv and dnn module, we must consider ratio of resizing of original image. For example when I have a `160*30` input image, at first I convert it to `416*78`(resizing one of the width or height to 416). Now for showing results, I resize height by multiplying it to `416/78`

**Comment by JayNg17x** [comment]
@barzan-hayati Hi there, I'm new to OpenCV and I now working on the project that related to YOLO, I've tried to display image using darknet but it did not display the detected image, how can I do? Thanks.
