### ISSUE TITLE
Process killed

### ISSUE THREAD

**Issue by Ira236** [pjreddie/darknet#1771]
Can anyone help me? seems like it even doesn't start to learn. Tried everything from other comments..
![Unbenannt](https://user-images.githubusercontent.com/54095782/62999890-12a61680-be70-11e9-8dee-adb5154387fa.PNG)

:)

**Comment by Stern-Hayat** [comment]
>Loaded: 1.706600 seconds
I think that's takes time too much. I heard that 0 ~ 1 sec. is better.
So, I suppose your image size is big to resize. 
How much size is your data?

**Comment by Ira236** [comment]
just found out, that I have to do this configurations

GPU=0
CUDNN=0
OPENCV=1
OPENMP=0
DEBUG=0

in the makefile, for training on CPU and now I can't figure out what to do next:
after "make" I get this error:
![image](https://user-images.githubusercontent.com/54095782/63013070-b4872c80-be8b-11e9-8ea5-689fb6ff969d.png)

I'm sorry, I'm totally new to this and tried already everything

**Comment by Stern-Hayat** [comment]
that's good!

**Comment by teh-monad** [comment]
> just found out, that I have to do this configurations
> 
> GPU=0
> CUDNN=0
> OPENCV=1
> OPENMP=0
> DEBUG=0
> 
> in the makefile, for training on CPU and now I can't figure out what to do next:
> after "make" I get this error:
> ![image](https://user-images.githubusercontent.com/54095782/63013070-b4872c80-be8b-11e9-8ea5-689fb6ff969d.png)
> 
> I'm sorry, I'm totally new to this and tried already everything

you dont have opencv on system/or it not in $PATH, google how to install it
also compile darknet WITH OPENMP=1, it increase speed
