### ISSUE TITLE
How to run YOLO on multiple images and save predictions to a directory

### ISSUE THREAD

**Issue by teh-monad** [pjreddie/darknet#1772]
like a prediction.1 png prediction.2 png  ... prediction.n png?

image_1 -> prediction_1
image_n -> prediction_n

**Comment by rudrakshmishra04** [comment]
@teh-monad Did you find a solution for it?

**Comment by teh-monad** [comment]
@rudrakshmishra04 not with darknet

**Comment by rudrakshmishra04** [comment]
Oh okay thanks

**Comment by rudrakshmishra04** [comment]
@teh-monad  Just out of curiosity, which other method did you use?
