### ISSUE TITLE
Tried to detect object, but it seems to be failed.

### ISSUE THREAD

**Issue by Stern-Hayat** [pjreddie/darknet#1773]
hello, everyone.
I tried to detect a lamp by using models. But the console log is stopped like this picture.
It seems to be failed, but I don't know what to to do... 
How should I do?

<img width="688" alt="スクリーンショット 2019-08-15 12 31 14" src="https://user-images.githubusercontent.com/32806231/63071139-00ec6e00-bf59-11e9-8785-9cdfcd96719c.png">
(username is hidden in black)

The code I tried:

darknet % ./darknet detector test lamp.data yolov3-lamp.cfg  .../backup/yolov3-lamp.backup .../darknet/data/obj/test.jpg

**Comment by teh-monad** [comment]
There no errors in output. Just check predictions.jpg in darknet root directory 👌

**Comment by Stern-Hayat** [comment]
Thank you very much !! 
I found prediction.jpg in root darkweb.(Detection is failed )

log is following:
/Users/(my real full name)/virtual/... So, I painted it black...
