### ISSUE TITLE
counting the custom detected objects.

### ISSUE THREAD

**Issue by YeetMasterYeet** [pjreddie/darknet#1798]
hello, after training a custom dataset, is there a way to count how many objects have been detected in an image or video? as in have the number of objects detected in the cmd or elsewhere?

**Comment by ab2010do** [comment]
HI, did you fix the problem?

**Comment by YeetMasterYeet** [comment]
hi, partially yes, i can count the number of objects detected on an image using a simple linux command : grep -Rl "curl" ./ | wc -l
add this at the end of the detection and it will count how many objects got detected, its a simple line counter.

**Comment by ab2010do** [comment]
ok fine, i will try it

**Comment by ab2010do** [comment]
yeah is run with me too, but still can't see the counting object in output object detection image

**Comment by aayushag** [comment]
can you please explain exactly where to add it?

**Comment by YeetMasterYeet** [comment]
hello @aayushag , you justneed to add "grep -Rl "curl" ./ | wc -l" to  your command while you select a weights file and an image/video ;
so for example:
 ./darknet detector test data/obj.data cfg/yolov3.cfg obj_last.weights 1.jpg grep -Rl "curl" ./ | wc -l
