### ISSUE TITLE
Yolo gives everything same label.

### ISSUE THREAD

**Issue by compnaion** [pjreddie/darknet#1808]
Sorry, I know it's probably a very simple problem, but couldn't find a solution, and don't know where to look at.

I am trying to learn object detection. In a youtube tutorial, there exist this code:
`
import cv2
from darkflow.net.build import TFNet
import matplotlib.pyplot as plt

options = {
    'model': 'cfg/yolov2-tiny.cfg',
    'load': 'bin/yolov2-tiny.weights',
    'treshold': 0.8
}
tfnet = TFNet(options)

img = cv2.imread('sample_img/sample_person.jpg', cv2.IMREAD_COLOR)
result = tfnet.return_predict(img)
tl = (result[0]['topleft']['x'],result[0]['topleft']['y'])
br = (result[0]['bottomright']['x'],result[0]['bottomright']['y'])
label = result[0]['label']

img = cv2.rectangle(img,tl,br,(0,255,0), 7)   

img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

plt.imshow(img)
plt.show()
`

I was having a problem:
labels.txt and cfg/yolov2-tiny.cfg indicate inconsistent class numbers
so I changed the classes in cfg equal to 3 and wrote into labels.txt these: horse dog car

Now whatever photo I put into the script,it finds the stuff it's trained to find, such as person car etc, but it lables them "horse".
How does this label and image pairing work exactly. What am I doing wrong here?

**Comment by deepdad** [comment]
If you think the issue is with this bit of Python code, print result after result = tfnet.return_predict(img). It may be that all three labels are scoring very high. I haven't tried the TF version but in general you're doing it right: match .cfg's n classes with your classes file make sure the paths are correctly read by the program. Retrain after changes (and re-make).

**Comment by compnaion** [comment]
> If you think the issue is with this bit of Python code, print result after result = tfnet.return_predict(img). It may be that all three labels are scoring very high. I haven't tried the TF version but in general you're doing it right: match .cfg's n classes with your classes file make sure the paths are correctly read by the program. Retrain after changes (and re-make).

I have solved it. It was cfg that have 80 classes. Thank you for your answer anyway.
