### ISSUE TITLE
Darknet with OpenCV: Why IplImage instead of Mat?

### ISSUE THREAD

**Issue by MithileshHinge** [pjreddie/darknet#182]
Is there any particular reason why darknet with opencv is implemented using the old and obsolete IplImage instead of the more efficient Mat? Am I missing something here? 
If not, implementation using Mat would be more efficient and simpler (since there is no need to allocate/deallocate memory)

**Comment by pengdada** [comment]
cv::Mat is C++ interface, darknet uses C only.

**Comment by MithileshHinge** [comment]
Thanks for the clarification.
