### ISSUE TITLE
what's the meaning of the parameter "max_crop"?

### ISSUE THREAD

**Issue by yanchao12122** [pjreddie/darknet#184]
what's the meaning of the parameter "max_crop"?

[net]
batch=16
subdivisions=2
height=448
width=448
max_crop=512
channels=3
momentum=0.9
decay=0.0005

**Comment by shaleh** [comment]
`max_crop` becomes `args.max` which becomes the `max` parameter to various functions in src/data.c.

**Comment by 4F2E4A2E** [comment]
@shaleh I [theoretically understand](https://de.wikipedia.org/wiki/Arg_max) what you're stating, but how does this affect the training or recognition with darknet? It also depends on how max_crop is implemented right? Can you please explain it like i am five?

**Comment by wombat78** [comment]
It seems to be fed into the load_threads function, which eventually controls how we load data. That also seems to depend on the type of data/task we are training. For example, for the detection task (load_data_detection), the parameter a.max doesn't seem to be used for anything. For classification, it seems to be used to control the maximum amount the image is scaled by before randomly rotating and cropping to get augmented data.

**Comment by 4F2E4A2E** [comment]
Thanks @wombat78 and @shaleh !
Could this maybe mean, that by increasing the max_crop value to the size of the average dataset images being training, would improve the recognition rate?
