### ISSUE TITLE
YOLO don't detect at all.

### ISSUE THREAD

**Issue by Stern-Hayat** [pjreddie/darknet#1841]
My yolo don't detect my object.

.cfg================
- batch: 64
- subdivisions: 16
==================-

I am using Google colab, but when #900_weight comes, it usually begin freezing.
In this case, Do I have to learn more？

Do you have any idea?

**Comment by dawidjk** [comment]
In general, training is fully completed somewhere around 50,000. If it's not detecting, either you have not trained enough intervals or your training data isn't good enough

**Comment by Stern-Hayat** [comment]
thanks very much. 
I decided to try same attempt on AWS sagemaker.

**Comment by vaibhavjussspacetech** [comment]
I am training yolov3 for my dataset contains 4 classes with almost 27000 images...after 3000 iterations my avg loss becomes "-nan" and if I use the saved weights it is not detecting anything..kindly help. BTW I have changed detector.c file to save weights for every 1000 iteration.

**Comment by dawidjk** [comment]
Just let it keep running. Mine usually finishes training at 52000
iterations so you have a long way to go. This takes about 25 hours with 3
1080 Tis btw

Dawid Kluszczynski
University of Illinois - Urbana Champaign
Statistics + Computer Science, 2021
dawidjk2@illinois.edu | 732-858-5046

**Comment by Stern-Hayat** [comment]
Thanks all, In the other day, I used model that trained about 20,000 times, then it works clearly.
Thank you very much.

**Comment by vaibhavjussspacetech** [comment]
Thank you dawidjk for your kind reply...The only thing I am worried about is average loss becomes "-nan"..should I continue with that..?

**Comment by dawidjk** [comment]
Yup, nothing to be worried about

Dawid Kluszczynski
University of Illinois - Urbana Champaign
Statistics + Computer Science, 2021
dawidjk2@illinois.edu | 732-858-5046

**Comment by vaibhavjussspacetech** [comment]
Thank you for your kind response..

**Comment by Akbarmq01** [comment]
@Stern-Hayat how did you use darknet on Sagemaker? can you please help me through the procedure. thanks
