### ISSUE TITLE
Wrong output

### ISSUE THREAD

**Issue by taalaialmasova** [pjreddie/darknet#1844]
**Hi everyone! 
Please help me.**
When I tested the trained model, it gives a result of 20-30% for 24 classes.
person1: 25%
person2: 20%
person3: 21%
...
etc
Example of my dataset ı-is in the below. My dataset contains  person faces as below

1. ![Image_4_1537348920278](https://user-images.githubusercontent.com/15725824/65755701-4c7b6580-e11c-11e9-98bf-5e4d60d6a2b5.jpg)
2. ![Image_4_1537348920521](https://user-images.githubusercontent.com/15725824/65755703-4d13fc00-e11c-11e9-9067-53136a1a096e.jpg)
3. ![Image_32_1537370776299](https://user-images.githubusercontent.com/15725824/65755704-4d13fc00-e11c-11e9-9fbf-50690261c3d0.jpg)
4. ![Image_32_1537370776540](https://user-images.githubusercontent.com/15725824/65755706-4d13fc00-e11c-11e9-97b7-6fe57ba5be93.jpg)

**Comment by bamwani** [comment]
What is the issue? you need to elaborate

**Comment by taalaialmasova** [comment]
> What is the issue? you need to elaborate

I trained a model with just people's faces. A person faces cropped as oval as shown in the image below,   between the ımage border and oval border colored by black. 
After 44000 iterations I didn't get the expected response. 

I run this code line->> darknet.exe detector test data/obj.data yolo-obj.cfg yolo-obj_44000.weights

**Comment by bamwani** [comment]
IDK, but Here's a reference, https://github.com/xhuvom/darknetFaceID
and why are you cropping in oval shapes? I think you shouldn't. Give it a try without cropping

**Comment by taalaialmasova** [comment]
the same dataset was used in another project to speed up the performance. So we want to use the same dataset for yolov3

**Comment by CaptianFluffy100** [comment]
If you are using yolo3-tiny.cfg it does not work as well as the yolo3.cfg.
