### ISSUE TITLE
Can I have CUDA support for darknet on a VMware Virtual Machine that runs Ubuntu 18.04  

### ISSUE THREAD

**Issue by mrlasdt** [pjreddie/darknet#1881]
Hello,

I am pretty new to Deep Learning so I would like to say sorry if this question is very basic. However, I cannot find the answer on Google.

My question is the same as the title: "Can I have CUDA support for darknet on a VMware Virtual Machine that runs Ubuntu 18.04 "

Thank you for considering my problem. Have a nice day!
With my warmest regards,
Will

Some details of my laptop configuration that you CAN SKIP, I just put it here just in case:
I am currently use a Dell Inspiron 5480 laptop with NVIDIA MX150 2GB.
Due to some reasons I need Window as my main OS. I tried to setup a dual boot configuration for Ubuntu but I couldn't, (maybe) the reason is because "Intel Octane Memory" (following some google answers). Therefore, I choose an alternative option that is installing Ubuntu 18.04 on VMware.

**Comment by AlexeyAB** [comment]
No, you can't.

There is only 1 way:
Only if you will install VMWare ESXi operation system ( https://en.wikipedia.org/wiki/VMware_ESXi ) on your laptop instead of Windows+VMWare, and then will configure pass-through way for GPU NVIDIA MX150 into the virtual machine. Also you will need to use another one PC to connect to this Virtual Machine.

**Comment by mrlasdt** [comment]
> No, you can't.
> 
> There is only 1 way:
> Only if you will install VMWare ESXi operation system ( https://en.wikipedia.org/wiki/VMware_ESXi ) on your laptop instead of Windows+VMWare, and then will configure pass-through way for GPU NVIDIA MX150 into the virtual machine. Also you will need to use another one PC to connect to this Virtual Machine.

Thank you for your detailed and quick answer. Have a nice day.
