### ISSUE TITLE
Adding new files to your YOLOv3 dataset to increase accuracy

### ISSUE THREAD

**Issue by lacwerda** [pjreddie/darknet#1883]
I just trained a model and got a decent output. However, I would like to add new images to the dataset in order to better the model. Should I use a completely new train.txt with unseen images or should I just add more images to the current one? What about the weights? Should I use the last weights or the inicial ones used to train the first dataset?

**Comment by bagminer** [comment]
You need to do the following -

>I would like to add new images to the dataset in order to better the model.
- Add images and their corresponding annotations to the training image folder

>Should I use a completely new train.txt with unseen images or should I just add more images to the current one?
- add image paths with names to train.txt and test.txt file

> Should I use the last weights or the initial ones used to train the first dataset?
- you can use the last weights

**Comment by lacwerda** [comment]
But should I train the entire dataset again + the new images or just the new images?

**Comment by bagminer** [comment]
Sorry for the late response. You should train with the entire dataset.  But if required, you can stop the training earlier. 
It doesn't make any sense to train on new images alone. 

If your issue is resolved. Please remember to close.

**Comment by lacwerda** [comment]
Thanks!
