### ISSUE TITLE
Edit the bounding box position (offset error)

### ISSUE THREAD

**Issue by merodin** [pjreddie/darknet#1884]
Hi!

I have a problem with the bounding boxes. The detection works fine, but all of my boxes have the same offset in vertical direction. I am looking for the lines in the image.c file to edit the bounding box draw coordinates. An issue similar to this this problem, but did not help: https://github.com/pjreddie/darknet/issues/1683

![yoloauto_0](https://user-images.githubusercontent.com/46922677/67410774-e4099200-f5bc-11e9-95ca-2e01db44b91c.jpg)

What lines should be edited? 

(My source files are 320x240 px, working with yolo-v3.cfg, with an 608x608 input size.)

**Comment by merodin** [comment]
I solved the problem: the image txt with the object data was corrupted, I had an offset from the real position in the Y direction. :)

**Comment by Mech-engineer** [comment]
Hey @merodin   are you suggesting the training image.txt files had the wrong coordinates? is there a way to check it. I am new to this and trying to solve this issue.

**Comment by merodin** [comment]
Hi @Mech-engineer,

Back then I was just realized that I accidentally messed up the vertical position calculation in my labeling software which I made. It was just an error in the horizontal calculation, you can check it by looking at your calculation again, based on this picture for example.

![img_0040](https://user-images.githubusercontent.com/46922677/99497846-c735be80-2976-11eb-8f46-2ed2befbc839.jpg)

**Comment by padmasreenagarajan** [comment]
Hi @merodin , I face the issue of smaller bounding boxes (YOLOV3) for my images..
Do have any idea on why is it happening?
