### ISSUE TITLE
make: /usr/bin/ld: -lcuda can't be found

### ISSUE THREAD

**Issue by fj0n** [pjreddie/darknet#1923]
Hi there,

when I try to make darknet, I get the following error:
 `d -L/usr/local/cudnn/lib64 -lcudnn -lstdc++ 
/usr/bin/ld: -lcuda kann nicht gefunden werden
collect2: error: ld returned 1 exit status
Makefile:143: recipe for target 'darknet' failed
make: *** [darknet] Error 1
`

I can execute `nvcc -V` and get:
`nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
`

I also tested it, by following the instructions from [nvidia](https://docs.nvidia.com/deeplearning/sdk/cudnn-install/index.html) on the mnist data and it worked.

In the Makefile, I have:
`GPU=1
CUDNN=1
CUDNN_HALF=0
OPENCV=0
AVX=0
OPENMP=0
LIBSO=0
ZED_CAMERA=0
`

Has someone got an idea what to do?

Thanks and greetings!

**Comment by fj0n** [comment]
I meanwhile uninstalled Cuda 10.1 and installed Cuda 10.0, like [here](https://github.com/AlexeyAB/darknet/issues/4224). Didn't work unfortunately.

**Comment by fj0n** [comment]
The issue is solved. One has to tell the Makefile where the file libcuda is.

**Comment by DangerousY** [comment]
> The issue is solved. One has to tell the Makefile where the file libcuda is.

Hello? can you tell me how to solve this problem? I meet with the same issue. And how can i tell Makefile where the file libcuda is.

**Comment by fj0n** [comment]
Hi there,

sorry for the late response. I didn't go here, since I solved the prob.

To solve it, find where your libcuda file is on your system. Here is my part of the makefile, that you should check:

`ifeq ($(GPU), 1)
COMMON+= -DGPU -I/usr/local/cuda/include/
COMMON+= -I/usr/local/cuda/lib64/stubs
CFLAGS+= -DGPU
ifeq ($(OS),Darwin) #MAC
LDFLAGS+= -L/usr/local/cuda/lib -lcuda -lcudart -lcublas -lcurand
else
LDFLAGS+= -L/usr/local/cuda/lib64 -lcuda -lcudart -lcublas -lcurand
LDFLAGS+= -L/usr/lib/x86_64-linux-gnu
LDFLAGS+= -L/usr/local/cuda/lib64/stubs
endif
endif

ifeq ($(CUDNN), 1)
COMMON+= -DCUDNN
ifeq ($(OS),Darwin) #MAC
CFLAGS+= -DCUDNN -I/usr/local/cuda/include
LDFLAGS+= -L/usr/local/cuda/lib -lcudnn
else
CFLAGS+= -DCUDNN -I/usr/local/cudnn/include
LDFLAGS+= -L/usr/local/cudnn/lib64 -lcudnn
endif
endif`
