### ISSUE TITLE
make command not found

### ISSUE THREAD

**Issue by HimTyers** [pjreddie/darknet#194]
I just started trying to use darknet/yolo and I'm trying to install darknet and whenever I try to use the 'make' command it says that the command cannot be found. Anyone know how to solve this?

> 
> Timothy MINGW64 ~
> $ cd darknet
> 
> Timothy MINGW64 ~/darknet (master)
> $ make
> bash: make: command not found

**Comment by AmirNaghibi** [comment]
Hi,
What is the solution for this issue? When I call make, I get the following error:

bash: make: command not found

I'm using Windows 10

**Comment by ahsan856jalal** [comment]
make is the linux command , for windows, try to follow AlexeyAB's darknet implementation
https://github.com/AlexeyAB/darknet
