### ISSUE TITLE
Darknet installation with Windows & AMD Ryzen 7 2700X

### ISSUE THREAD

**Issue by Mikkochu** [pjreddie/darknet#1986]
Hi,

I'm a beginner programmer trying to practice image detection. I'm having a hard time getting darknet to work. I've understood that I cannot use CUDA, because I have AMD.
https://stackoverflow.com/questions/12828268/is-it-possible-to-run-cuda-on-amd-gpus

Are there any ways around this. What is the simplest way for me to get darknet to work?

I have the following system information

OS:  Microsoft Windows 10 Pro
Processor: AMD Ryzen 7 2700X Eight-Core Processor, 3700 Mhz, 8 Core(s), 16 Logical Processor(s)
BIOS: Version/Date	American Megatrends Inc. 2.40, 6.11.2018
BaseBoard Product	X470 GAMING PRO CARBON (MS-7B78)
Total Physical Memory	32,0 GB
Dsiplay:	Radeon RX 580 Series

thank you so much

EDIT:
After some struggle I managed to install darknet with this
https://github.com/thtrieu/darkflow

However this solution doesn't support the newest version of Yolo. Any advice?

**Comment by sowson** [comment]
Hi, please check what I did at https://github.com/sowson/darknet probably you need to figured out how to use make/cmake on Windows, because I am using and testing only on GNU/Linux and macOS, but this solution works very very nice on AMD... :D. Enjoy!
