### ISSUE TITLE
Mac OS X openCV Make Error

### ISSUE THREAD

**Issue by insung3511** [pjreddie/darknet#2001]
```
$ make 
g++ -Iinclude/ -Isrc/ -DOPENCV `pkg-config --cflags opencv`  -Wall -Wno-unused-result -Wno-unknown-pragmas -Wfatal-errors -fPIC -Ofast -DOPENCV -c ./src/image_opencv.cpp -o obj/image_opencv.o
clang: fatal error: no such file or directory: 'M:/Software/opencv/build/include/opencv'
make: *** [obj/image_opencv.o] Error 1
```
I changed  /usr/local/lib/pkgconfig/opencv.pc link  to /usr/local/Cellar/opencv/4.2.0_1/./lib/pkgconfig/opencv4.pc

openCV Version = 3.4.5
Mac OS X Version = 10.15.2

**Comment by Chamchis** [comment]
/usr/local/Cellar/opencv/4.2.0_1/./lib/pkgconfig/opencv4.pc is for openCV version 4.2.0_1 not 3.4.5
Download openCV 3.x.x or lower version and follow this.
1. echo $PKG_CONFIG_PATH
2. export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:[opencv_path]
3. make
