### ISSUE TITLE
how to extract the feature of an image?

### ISSUE THREAD

**Issue by yanchao12122** [pjreddie/darknet#201]
In caffe, I can extract the last fc as the feature of an image
but in darknet, how can I get the last fc?

**Comment by Huang9495** [comment]
@yanchao12122  hey! how to extract the feature map from the darknet ? Please help me.

**Comment by AlexeyAB** [comment]
@Huang9495 Do you want to show output feature maps of each layers?

Try to use this repository: https://github.com/AlexeyAB/darknet/

Un-comment these lines: https://github.com/AlexeyAB/darknet/blob/6d44529cf93211c319813c90e0c1adb34426abe5/src/network_kernels.cu#L61-L75

And recompile

**Comment by Huang9495** [comment]
@AlexeyAB  I want to gain the output feature maps of the last layer.

**Comment by AlexeyAB** [comment]
@Huang9495 

Instead of this code: https://github.com/AlexeyAB/darknet/blob/6d44529cf93211c319813c90e0c1adb34426abe5/src/network_kernels.cu#L47-L77

Use this code:
```cpp
void forward_network_gpu(network net, network_state state)
{
    state.workspace = net.workspace;
    int i;
    for(i = 0; i < net.n; ++i){
        state.index = i;
        layer l = net.layers[i];
        if(l.delta_gpu){
            fill_ongpu(l.outputs * l.batch, 0, l.delta_gpu, 1);
        }
        l.forward_gpu(l, state);
		if(net.wait_stream)
			cudaStreamSynchronize(get_cuda_stream());
        state.input = l.output_gpu;
            if(i == (net.n-2)) {
		cuda_pull_array(l.output_gpu, l.output, l.batch*l.outputs);
		if (l.out_w >= 0 && l.out_h >= 1 && l.c >= 3) {
			int j;
			for (j = 0; j < l.out_c; ++j) {
				image img = make_image(l.out_w, l.out_h, 3);
				memcpy(img.data, l.output+ l.out_w*l.out_h*j, l.out_w*l.out_h * 1 * sizeof(float));
				char buff[256];
				sprintf(buff, "layer-%d slice-%d", i, j);
				show_image(img, buff);
			}
			cvWaitKey(0); // wait press-key in console
			cvDestroyAllWindows();
		}
            }
    }
}
```

**Comment by Huang9495** [comment]
@AlexeyAB Hi! Whether the mean of your words is that I can invoke forward_network_gpu function to gain the feature map of layer 29 ?

**Comment by ivychill** [comment]
@AlexeyAB Hi! I use your code, it always show black image. And I add the following code:
for (index = 0; index < l.out_w*l.out_h; index++)
{
    if (index > 0) printf(":");
    printf("%02X", (int)l.output[index]);
}

it show 00:00:00:00...
What is the matter?

**Comment by mhusseinsh** [comment]
> @Huang9495
> 
> Instead of this code: https://github.com/AlexeyAB/darknet/blob/6d44529cf93211c319813c90e0c1adb34426abe5/src/network_kernels.cu#L47-L77
> 
> Use this code:
> 
> ```c++
> void forward_network_gpu(network net, network_state state)
> {
>     state.workspace = net.workspace;
>     int i;
>     for(i = 0; i < net.n; ++i){
>         state.index = i;
>         layer l = net.layers[i];
>         if(l.delta_gpu){
>             fill_ongpu(l.outputs * l.batch, 0, l.delta_gpu, 1);
>         }
>         l.forward_gpu(l, state);
> 		if(net.wait_stream)
> 			cudaStreamSynchronize(get_cuda_stream());
>         state.input = l.output_gpu;
>             if(i == (net.n-2)) {
> 		cuda_pull_array(l.output_gpu, l.output, l.batch*l.outputs);
> 		if (l.out_w >= 0 && l.out_h >= 1 && l.c >= 3) {
> 			int j;
> 			for (j = 0; j < l.out_c; ++j) {
> 				image img = make_image(l.out_w, l.out_h, 3);
> 				memcpy(img.data, l.output+ l.out_w*l.out_h*j, l.out_w*l.out_h * 1 * sizeof(float));
> 				char buff[256];
> 				sprintf(buff, "layer-%d slice-%d", i, j);
> 				show_image(img, buff);
> 			}
> 			cvWaitKey(0); // wait press-key in console
> 			cvDestroyAllWindows();
> 		}
>             }
>     }
> }
> ```

@AlexeyAB can I avoid these slices ? I want to have a full image representing the feature map

**Comment by mhusseinsh** [comment]
@AlexeyAB very thanks for your quick reply

> @mhusseinsh
> 
> > And why the images are red in color ?
> 
> Update your code from this repository, and un-comment these code: https://github.com/AlexeyAB/darknet/blob/6c8642b3eb19b68a11f3fae6a55bbfd528a800d3/src/network_kernels.cu#L71-L88
> 
I copied the un-commented part of your code and put it in mine, and these are results
![layer-0 slice-9](https://user-images.githubusercontent.com/33177438/46356907-00f6be80-c664-11e8-8dfa-bed27d16716d.png)
![layer-0 slice-15](https://user-images.githubusercontent.com/33177438/46356908-00f6be80-c664-11e8-8795-4b3932e6101b.png)
I thought they will be something looking like this somehow

![example](https://user-images.githubusercontent.com/33177438/46357113-664aaf80-c664-11e8-97ad-2eff73e084ec.jpg)

> > can I avoid these slices ? I want to have a full image representing the feature map
> 
> Do you want to see all channels (images) in the one window?
> You can try to use this tool: [AlexeyAB#1608 (comment)](https://github.com/AlexeyAB/darknet/issues/1608#issuecomment-425792571)

Unfortunately, I cannot work on this, because I am running on openSuSE not windows

**ANOTHER QUESTION**

Is there a way to have these maps as feature vectors ? Actually I want to do comparison between feature maps using a clustering method like k-nearest neighbors for example, so how can I represent it as a feature vector ?

**Comment by avinashpaul2012** [comment]
> @AlexeyAB very thanks for your quick reply
> 
> > @mhusseinsh
> > > And why the images are red in color ?
> > 
> > 
> > Update your code from this repository, and un-comment these code: https://github.com/AlexeyAB/darknet/blob/6c8642b3eb19b68a11f3fae6a55bbfd528a800d3/src/network_kernels.cu#L71-L88
> 
> I copied the un-commented part of your code and put it in mine, and these are results
> ![layer-0 slice-9](https://user-images.githubusercontent.com/33177438/46356907-00f6be80-c664-11e8-8dfa-bed27d16716d.png)
> ![layer-0 slice-15](https://user-images.githubusercontent.com/33177438/46356908-00f6be80-c664-11e8-8795-4b3932e6101b.png)
> I thought they will be something looking like this somehow
> 
> ![example](https://user-images.githubusercontent.com/33177438/46357113-664aaf80-c664-11e8-97ad-2eff73e084ec.jpg)
> or this
> ![activations](https://user-images.githubusercontent.com/33177438/46358391-2fc26400-c667-11e8-9be0-2964f75bf812.png)
> 
> > > can I avoid these slices ? I want to have a full image representing the feature map
> > 
> > 
> > Do you want to see all channels (images) in the one window?
> > You can try to use this tool: [AlexeyAB#1608 (comment)](https://github.com/AlexeyAB/darknet/issues/1608#issuecomment-425792571)
> 
> Unfortunately, I cannot work on this, because I am running on openSuSE not windows
> 
> **ANOTHER QUESTION**
> 
> Is there a way to have these maps as feature vectors ? Actually I want to do comparison between feature maps using a clustering method like k-nearest neighbors for example, so how can I represent it as a feature vector ?

**Comment by avinashpaul2012** [comment]
Can you suggest how you got results as you have shown >>I copied the un-commented part of your code and put it in mine, and these are results

**Comment by avinashpaul2012** [comment]
> @AlexeyAB very thanks for your quick reply
> 
> > @mhusseinsh
> > > And why the images are red in color ?
> > 
> > 
> > Update your code from this repository, and un-comment these code: https://github.com/AlexeyAB/darknet/blob/6c8642b3eb19b68a11f3fae6a55bbfd528a800d3/src/network_kernels.cu#L71-L88
> 
> I copied the un-commented part of your code and put it in mine, and these are results
> ![layer-0 slice-9](https://user-images.githubusercontent.com/33177438/46356907-00f6be80-c664-11e8-8dfa-bed27d16716d.png)
> ![layer-0 slice-15](https://user-images.githubusercontent.com/33177438/46356908-00f6be80-c664-11e8-8795-4b3932e6101b.png)
> I thought they will be something looking like this somehow
> 
> ![example](https://user-images.githubusercontent.com/33177438/46357113-664aaf80-c664-11e8-97ad-2eff73e084ec.jpg)
> or this
> ![activations](https://user-images.githubusercontent.com/33177438/46358391-2fc26400-c667-11e8-9be0-2964f75bf812.png)
> 
> > > can I avoid these slices ? I want to have a full image representing the feature map
> > 
> > 
> > Do you want to see all channels (images) in the one window?
> > You can try to use this tool: [AlexeyAB#1608 (comment)](https://github.com/AlexeyAB/darknet/issues/1608#issuecomment-425792571)
> 
> Unfortunately, I cannot work on this, because I am running on openSuSE not windows
> 
> **ANOTHER QUESTION**
> 
> Is there a way to have these maps as feature vectors ? Actually I want to do comparison between feature maps using a clustering method like k-nearest neighbors for example, so how can I represent it as a feature vector ?

Can you suggest how you got results as you have shown >>I copied the un-commented part of your code and put it in mine, and these are results

**Comment by avinashpaul2012** [comment]
> @Huang9495 Do you want to show output feature maps of each layers?
> 
> Try to use this repository: https://github.com/AlexeyAB/darknet/
> 
> Un-comment these lines: https://github.com/AlexeyAB/darknet/blob/6d44529cf93211c319813c90e0c1adb34426abe5/src/network_kernels.cu#L61-L75
> 
> And recompile

Hey I am using colab and generating the test result using somethng like: "!./darknet detector test data/obj.data cfg/yolov4-obj.cfg /mydrive/yolov4_all/backup_yolo/yolov4-obj_5000.weights -ext_output /content/darknet/data/test/case_M_20181025095048_0U62372102595347_1_004_001-1_a11_ayy_image0070.jpg 
imShow('predictions.jpg')" . I made the changes in the kernel file as suggested. Can you suggest how I can view the maps ( i mean what command line to use)

**Comment by laplaceson** [comment]
Hi @AlexeyAB , is this code modification still works in current yolov4?
Since i replace the code forward_network_gpu and face error 
./src/network_kernels.cu(319): warning: variable "l" was declared but never referenced


319 = >layer l = net.layers[net.n - 1];
Thanks in advance.

**Comment by qiumei1101** [comment]
> @AlexeyAB I want to gain the output feature maps of the last layer.

HI, can you get the feature of each bounding box from darknet based yolov4? thanks
