### ISSUE TITLE
CUDA Error: invalid argument 

### ISSUE THREAD

**Issue by AbduazizKayumov** [pjreddie/darknet#2036]
Hey, guys, I have installed OpenCV and CUDA 10.1 properly, added necessary paths to .bashrc file compiled darknet successfully, double-checked them, , however, I keep getting this error:
```
CUDA Error: invalid argument
darknet: ./src/cuda.c:36: check_error: Assertion `0' failed.
Aborted (core dumped)
```
when I just wanted to test this:
`sudo ./darknet detect cfg/yolov3-tiny.cfg yolov3.weights data/dog.jpg
`
Everything is working in CPU, but GPU training sucks for now.
Such a pain in the ass, could not find any solution to this online, official NVIDIA forum states that it may be because of the allocation of shared memory:
https://devtalk.nvidia.com/default/topic/1047998/how-to-deal-with-quot-invalid-argument-quot-errors-when-launching-kernels-with-arguments-pointing-to-large-data-/

I am using Ubuntu 18.04 and my GPU is **Geforce RTX 2080 Super**.

What I have tried so far:
1) Counless reboots, checking if CUDA and OpenCV proper installations
2) Changed the params as min as possible:
```
batch=1
subdivisions=1
width=416
height=416
```
3) Make clean && make everytime I changed GPU arch and compute, I tried everything from 30 ~ 75.
No success for now, so any hints, links, references would be so much helpful.  

Found similar issue to mine, but total silence there as well. 
Is there anyone who can shed a light on this? Thank you.

**Comment by shubhamsy777** [comment]
Is there any update on this? I just faced this issue today.

**Comment by zenglongGH** [comment]
maybe you have installed CUDNN also,so you should enable this in makefile.

GPU=1
CUDNN=1

make 

it work in my case

**Comment by AbduazizKayumov** [comment]
It may not be the solution, but I ended up using Yolo's Pytorch version from this repo:
https://github.com/eriklindernoren/PyTorch-YOLOv3

**Comment by shubhamsy777** [comment]
@AbduazizKayumov I think I found out where the problem lies, its with nvidia's base docker of cuda_v10.1. 

I built a docker container from with cuda_v10.0 container and cuda_v10.1, and ran the containers with the exact same command. Pulled a fresh pjreddie/darknet repo as well as AlexeyAB/darknet repo. Both build got failed with same error in cuda_v10.1 but got successfully built as well as ran fine in cuda_v10.0. 
From the error it appears they changed the number of input arguments of a particular function in cuda_v10.1.

**Comment by AbduazizKayumov** [comment]
Thank you for the update @shubhamsy777, I will give Cuda v10.0 a try.

**Comment by lolpa1n** [comment]
> Thank you for the update @shubhamsy777, I will give Cuda v10.0 a try.

solved this issue? i have the same error

```
CUDA status Error: file: ./src/dark_cuda.c : () : line: 239 : build time: Apr  7 2020 - 17:15:55 

 CUDA Error: invalid argument
CUDA Error: invalid argument: File exists
darknet: ./src/utils.c:325: error: Assertion `0' failed.
```

**Comment by AbduazizKayumov** [comment]
@lolpa1n I didn't have a chance to try v10.0. Still using the Pytorch version.
