### ISSUE TITLE
Will load and detection speed reduced when I training new model with less classes?

### ISSUE THREAD

**Issue by devFallingstar** [pjreddie/darknet#2038]
As far as I know, currently, provided yolo weight trained with 80 classes.

I want to re-train weight with only 5 classes, and with this, should I get noticeable speed increasment when loading model and running detection?

My resources are limited so it would be bad if there's no changed.

**Comment by leehangyu** [comment]
There will be no dramatic speed up, because it won't change the whole layers in network but last one.

For example, all layers before last layer will be the same, and the last layer will be changed from shape (b, 80) to (b, 5).

Flops will most likely be similar
