### ISSUE TITLE
Error to train custom data at google colab

### ISSUE THREAD

**Issue by Nazrindino97** [pjreddie/darknet#2092]
The last step for data training and got error

`!./darknet detector train data/obj.data yolov3-palmoil.cfg darknet53.conv.74 -dont_show`

> CUDA Error: no CUDA-capable device is detected
> darknet: ./src/cuda.c:36: check_error: Assertion `0' failed.

Please help me.

**Comment by shouryasimha** [comment]
what are your specs? maybe change the makefile cuda=0?
I'm a noob, but that can help I guess.
