### ISSUE TITLE
mAP graph during training doesn't show

### ISSUE THREAD

**Issue by sayed797** [pjreddie/darknet#2101]
I use this command to train in colab
`!./darknet detector train data/obj.data cfg/yolov3_custom.cfg darknet53.conv.74 -dont_show -map`
and when i click on chart.png
all I see is this
[screenshoot](https://imgur.com/a/QnVBj6z)

**Comment by vfbsilva** [comment]
@sayed797 can confirm this is happening also here.
Maybe a bug?

**Comment by sayed797** [comment]
> @sayed797 can confirm this is happening also here.
> Maybe a bug?

I wass wrong after 1000 iteration it appear on the chart

**Comment by sercangokturk** [comment]
> I use this command to train in colab
> `!./darknet detector train data/obj.data cfg/yolov3_custom.cfg darknet53.conv.74 -dont_show -map`
> and when i click on chart.png
> all I see is this
> [screenshoot](https://imgur.com/a/QnVBj6z)

hi, i have the same problem. after 1000 iteration it still don't appear on the chart.png moreover, i see 0%

**Comment by sercangokturk** [comment]
> > @sayed797 can confirm this is happening also here.
> > Maybe a bug?
> 
> I wass wrong after 1000 iteration it appear on the chart

hi, so how can i appear before 1000 iteration? did you find a solution? thanks in advance

**Comment by AbdelrahamanKh** [comment]
> hi, so how can i appear before 1000 iteration? did you find a solution? thanks in advance
just comment this line
`next_map_calc = fmax(next_map_calc, net.burn_in);
in darknet/src/detector.c
`
