### ISSUE TITLE
yolov3 tiny detect issue

### ISSUE THREAD

**Issue by cuu** [pjreddie/darknet#2111]
git hash  61c9d02

just compile the darknet with no modifications in Makefile 

then run a test as the tutorial says

```
./darknet detect cfg/yolov3-tiny.cfg yolov3-tiny.weights data/dog.jpg
```

then I got this result 

![predictions](https://user-images.githubusercontent.com/523580/79073170-a5f15d80-7d17-11ea-9e92-911e7f7af83c.jpg)

I don't know what went wrong

**Comment by shaheryar1** [comment]
Same issue

**Comment by shaheryar1** [comment]
Turns out the .weights file was corrupted . I just downloaded it again and replaced . Worked fine

**Comment by cuu** [comment]
> Turns out the .weights file was corrupted . I just downloaded it again and replaced . Worked fine

great news, could you share a md5 of your tiny .weights ?

**Comment by cuu** [comment]
3bcd6b390912c18924b46b26a9e7ff53  yolov3-tiny.weights

Sun 19 Apr 2020 04:37:06 AM CST

tested, @shaheryar1  is right,close now
