### ISSUE TITLE
CSI camera with darknet

### ISSUE THREAD

**Issue by elementdl** [pjreddie/darknet#2121]
Hi,

I want to use a CSI Camera with darknet, but I don't know how he can recognize this camera.

When I try a simple "./darknet detector demo" with yolov3-tiny, I get 3 warnings telling me about cap_gstreamer.cpp :
-module v4l2src0 reported : internalt data stream error
-unable to start pipeline
-pipelin have not been created

then a million lines of :
VIDIOC_QBUF: Invalid argument.

Sincerely,

**Comment by Rajasekhar06** [comment]
I think this repository  will be your answer https://github.com/ultralytics/yolov3/

**Comment by elementdl** [comment]
Hi @Rajasekhar06 , I'm sorry I'm not sure to understand, the link you sent talk about Yolo in pytorch, not Yolo in darknet, so I don't know how it can help me to run a csi camera with darknet.

**Comment by Rajasekhar06** [comment]
in order to make darknet work as you wished you need to comile openCV so that it form the interface but while comming to pytorch implementation you need to just mention source as 0 then it will take input from camera
