### ISSUE TITLE
Yolov4 weights

### ISSUE THREAD

**Issue by loretoparisi** [pjreddie/darknet#2135]
Are you going to release the new Yolov4 weights?
Thank you.

**Comment by Scottchou7** [comment]
Yolo v4 weights:  https://drive.google.com/open?id=1cewMfusmPjYWbrnuJRuKhPMwRe_b9PaT
You can see more information in: https://github.com/AlexeyAB/darknet

**Comment by b4da** [comment]
How can I download this through terminal? wget https://pjreddie.com/media/files/yolov4.weights -- > is not working/doesn't work?

**Comment by AlexeyAB** [comment]
`wget https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v3_optimal/yolov4.weights`

**Comment by b4da** [comment]
@AlexeyAB thank you :). 

Also, will this repo https://github.com/pjreddie/darknet.git also work for YOLOv4?

Thank you for your help

**Comment by ashwini1081** [comment]
google drive link is broken, but the github link worked for me :
wget https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v3_optimal/yolov4.weights

**Comment by MiaryFanantenana** [comment]
how can I download YOLOv4.cfg and YOLOv4.weights?
