### ISSUE TITLE
Out of memory issue while training yolov4 model

### ISSUE THREAD

**Issue by shubhambaid** [pjreddie/darknet#2146]
I'm getting out of memory error while training custom yolov4 model

`nvidia-smi`

2389MiB /  4042MiB

> 608 x 608 
 Try to set subdivisions=64 in your cfg-file. 
CUDA status Error: file: ./src/dark_cuda.c : () : line: 373 : build time: Apr  1 2020 - 19:18:55

**Comment by jefflgaol** [comment]
Inside your yolov4_custom.cfg or the any cfg that you were using, you need to change the subdivisions to match your GPU performance. For example, for 32 GB GPU-VRAM, set ```subdivisions=8``` in your cfg-file. For 8-12, set ```subdivisions=32```.

**Comment by shubhambaid** [comment]
Thanks a tonn !
