### ISSUE TITLE
Error while training: Cannot load image "" Couldn't open file: data/labels/img16.bmp Couldn't open file: data/labels/img32.bmp Couldn't open file:

### ISSUE THREAD

**Issue by ruchaa01** [pjreddie/darknet#2191]
I am training on my own dataset and I keep getting the error: "cannot load image" for the .bmp files I want to train on.
My labels and images are in different folders with a structure:
data/images/img01.bmp
data/images/img02.bmp
data/images/img03.bmp
.
.
.
data/labels/img01.txt
data/labels/img02.txt
data/labels/img03.txt
.
.
.
.
.

**Comment by git3210** [comment]
i hava the same problme: "couldn't open file: data/lables/*.jpeg" .  how do you sovle the problem
