### ISSUE TITLE
CUDA status Error: file: ./src/dark_cuda.c : () : line: 239 : build time: Jun 16 2020 - 20:18:49    CUDA Error: invalid argument CUDA Error: invalid argument: File exists darknet: ./src/utils.c:326: error: Assertion `0' failed.

### ISSUE THREAD

**Issue by chinapina** [pjreddie/darknet#2192]
Hello! I'm trying to install darknet on collab in order to train a NN based on yolov3 but when running this code:!git clone https://github.com/AlexeyAB/darknet
  
!apt-get update
!apt-get upgrade
 
 
!apt-get install build-essential
!apt-get install cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
 
!apt-get install libavcodec-dev libavformat-dev libswscale-d
 
!apt-get install libopencv-dev
 
  
%cd darknet
 
!ls
!sed -i 's/OPENCV=0/OPENCV=1/g' Makefile
!sed -i 's/GPU=0/GPU=1/g' Makefile
 
 
!ls
%cd ../
!ls
 
 
!apt install g++-5
!apt install gcc-5
 
!apt update
!apt upgrade
 
import tensorflow as tf
device_name = tf.test.gpu_device_name()
print(device_name)
 
print("'sup!'")
 
!/usr/local/cuda/bin/nvcc --version
 
%cd darknet
!wget https://pjreddie.com/media/files/yolov3.weights
!make
 
!./darknet detect cfg/yolov3.cfg yolov3.weights data/person.jpg
 
def imShow(path):
  import cv2
  import matplotlib.pyplot as plt
  %matplotlib inline
 
  image = cv2.imread(path)
  height, width = image.shape[:2]
  resized_image = cv2.resize(image,(3*width, 3*height), interpolation = cv2.INTER_CUBIC)
 
  fig = plt.gcf()
  fig.set_size_inches(18, 10)
  plt.axis("off")
  #plt.rcParams['figure.figsize'] = [10, 5]
  plt.imshow(cv2.cvtColor(resized_image, cv2.COLOR_BGR2RGB))
  plt.show()
  
  
def upload():
  from google.colab import files
  uploaded = files.upload() 
  for name, data in uploaded.items():
    with open(name, 'wb') as f:
      f.write(data)
      print ('saved file', name)
def download(path):
  from google.colab import files
  files.download(path)
  
  
 
imShow('/content/drive/My Drive/face/img/bv.jpg')

it gives me this:CUDA status Error: file: ./src/dark_cuda.c : () : line: 239 : build time: Jun 16 2020 - 20:18:49 

 CUDA Error: invalid argument
CUDA Error: invalid argument: File exists
darknet: ./src/utils.c:326: error: Assertion `0' failed. 

i guess people started to face this issue on april maybe it s a new collab update? HELP PLS:(

**Comment by Nishant-DN** [comment]
If you are running yolov3 code on Google Collab, after setting GPU=1 in Makefile, you should go to Edit option on the menu and then by clicking on the Notebook Settings option, change the hardware Accelarator to GPU ( By default it will be None) and then save it.
![GPU](https://user-images.githubusercontent.com/66809558/84981480-41f17800-b152-11ea-92de-2fb6e6c1b451.JPG)
