### ISSUE TITLE
How to convert Image to IMAGE?

### ISSUE THREAD

**Issue by WhiteEyeYan** [pjreddie/darknet#2233]
I'm trying to use screenshot without save image to disk.

I am modifying darknet.py .

I use this code form Internet to get window 

> def screenShot(win_name):
    &nbsp;&nbsp;&nbsp;&nbsp;from PIL import Image
    &nbsp;&nbsp;&nbsp;&nbsp;import numpy as np
    &nbsp;&nbsp;&nbsp;&nbsp;hWnd = win32gui.FindWindow(None, win_name)
&nbsp;&nbsp;&nbsp;&nbsp;    windowcor = win32gui.GetWindowRect(hWnd)
&nbsp;&nbsp;&nbsp;&nbsp;    w=windowcor[2]-windowcor[0]
&nbsp;&nbsp;&nbsp;&nbsp;    h=windowcor[3]-windowcor[1]
&nbsp;&nbsp;&nbsp;&nbsp;    wDC = win32gui.GetWindowDC(hWnd)
&nbsp;&nbsp;&nbsp;&nbsp;    dcObj=win32ui.CreateDCFromHandle(wDC)
&nbsp;&nbsp;&nbsp;&nbsp;    cDC=dcObj.CreateCompatibleDC()
&nbsp;&nbsp;&nbsp;&nbsp;    dataBitMap = win32ui.CreateBitmap()
&nbsp;&nbsp;&nbsp;&nbsp;    dataBitMap.CreateCompatibleBitmap(dcObj, w, h)
&nbsp;&nbsp;&nbsp;&nbsp;    cDC.SelectObject(dataBitMap)
&nbsp;&nbsp;&nbsp;&nbsp;    cDC.BitBlt((0,0),(w, h) , dcObj, (0,0), win32con.SRCCOPY)
&nbsp;&nbsp;&nbsp;&nbsp;    bmpinfo = dataBitMap.GetInfo()
&nbsp;&nbsp;&nbsp;&nbsp;    bmpstr = dataBitMap.GetBitmapBits(True)
&nbsp;&nbsp;&nbsp;&nbsp;    #dataBitMap.Paint(cDC)
&nbsp;&nbsp;&nbsp;&nbsp;    #dataBitMap.SaveBitmapFile(cDC,'tmp.bmp')
&nbsp;&nbsp;&nbsp;&nbsp;    img = Image.frombuffer('RGB', (bmpinfo['bmWidth'], bmpinfo['bmHeight']), bmpstr, 'raw', 'BGRX', 0, 1)
&nbsp;&nbsp;&nbsp;&nbsp;    return img

In detect function, I change

`im = load_image(image, 0, 0)`
to

`im = screenShot('window name')`

After that, I got an error:
`ctypes.ArgumentError: argument 1: <class 'TypeError'>: expected IMAGE instance instead of Image.`

Now, I must store the image into the disk, then load image from disk.
But, it's too slow.
I want to load image from memory, instead of disk.

I have search for solving this problem for a week.
Can anyone help me?

Thanks

**Comment by WhiteEyeYan** [comment]
I have slove it.

**Comment by noelchen90** [comment]
Hi, may I ask how you solved this?
I have encountered a similar problem where I want to detect directly from an image  instead of an image path.
