### ISSUE TITLE
Generating Object Detection outputs

### ISSUE THREAD

**Issue by dhruvsheth-ai** [pjreddie/darknet#2294]
I have trained an object detection model in yolov4 with 9 classes and it runs properly. I want to generate outputs based on the class detected. Would Modifying the darknet_inages.py script help? I want to declare a random variable, say x = 0 each time it prints an individual class.
If person is detected:
     y = 0
If car is detected:
      x = 0

**Comment by panban-ux** [comment]
Im looking for a similar approach on a darknet-NNPACK, print my classes string into another variable and count each individual (same class) oblect. Did you had any success?

**Comment by dhruvsheth-ai** [comment]
Not yet, hope someone pops in this thread soon
