### ISSUE TITLE
Problem related to final results - avg IoU

### ISSUE THREAD

**Issue by Bruno-Hazard** [pjreddie/darknet#2304]
Hello guys,

When I analyze my model for an mAP (0.5) I got an average IoU = 76.87 %
However, when switched to mAP (0.75) the **average IoU** decreases to = 65.11 % 

I would like to understand the reason.
I know that changing the IoU directly interferes with the precision and recall calculations, but shouldn't the IoU/avg IoU depend only on the region of the detected object and the real object?

======== Results mAP 0.5 =========
detections_count = 4423, unique_truth_count = 3019  
class_id = 0, name = license_plate, ap = 98.51%   	 (TP = 2951, FP = 190) 

 for conf_thresh = 0.25, precision = 0.94, recall = 0.98, F1-score = 0.96 
 for conf_thresh = 0.25, TP = 2951, FP = 190, FN = 68, **average IoU = 76.87 %** 

 IoU threshold = 50 %, used Area-Under-Curve for each unique Recall 
 mean average precision (mAP@0.50) = 0.985080, or 98.51 % 
Total Detection Time: 88 Seconds

======== Results mAP 0.75 =========

detections_count = 4423, unique_truth_count = 3019  
class_id = 0, name = license_plate, ap = 74.09%   	 (TP = 2414, FP = 727) 

 for conf_thresh = 0.25, precision = 0.77, recall = 0.80, F1-score = 0.78 
 for conf_thresh = 0.25, TP = 2414, FP = 727, FN = 605, **average IoU = 65.11 %** 

 IoU threshold = 75 %, used Area-Under-Curve for each unique Recall 
 mean average precision (mAP@0.75) = 0.740856, or 74.09 %

**Comment by zylove006** [comment]
Hi,can you tell me the meaning of detections_count? Thank you!
