### ISSUE TITLE
Recall calcuation in validate_detector_recall ignores class label

### ISSUE THREAD

**Issue by kb1ooo** [pjreddie/darknet#231]
In examples/detector.c and example/yolo.c it looks like the recall calculation in validate_detector_recall and validate_yolo_recall ignores the predicted label for a box and just assumes that the box with the greatest IOU (if also above IOU threshold of .5) has the correct class label.  Am I right, and if so, why?   Excerpt of code here: 

            int num_labels = 0;
            box_label *truth = read_boxes(labelpath, &num_labels);
            for(k = 0; k < l.w*l.h*l.n; ++k){
                if(probs[k][0] > thresh){
                    ++proposals;
                }
            }
            for (j = 0; j < num_labels; ++j) {
                ++total;
                box t = {truth[j].x, truth[j].y, truth[j].w, truth[j].h};
                float best_iou = 0;
                for(k = 0; k < l.w*l.h*l.n; ++k){
                    float iou = box_iou(boxes[k], t);
                    if(probs[k][0] > thresh && iou > best_iou){
                        best_iou = iou;
                    }
                }
                avg_iou += best_iou;
                if(best_iou > iou_thresh){
                    ++correct;
                }
            }

**Comment by AlexeyAB** [comment]
> **validate_detector_recall** and validate_yolo_recall ignores the predicted label for a box and just assumes that the box with the greatest IOU (if also above IOU threshold of .5) **has the correct class label**. 

` validate_detector_recall()` doesn't check is the class label correct. It only checks:
* if **logistic_activated_scale > threshold** - `if(probs[k][0] > thresh)`
* and then if **best_iou > 0.5** - ` if(best_iou > iou_thresh)` for each ground truth object on the image (even if class on the image does not match the detected class)

More about different between `test_detector()` and `validate_detector_recall()`: https://github.com/AlexeyAB/darknet/issues/214#issuecomment-333381170

**Comment by kb1ooo** [comment]
Ok so I think the answer is that validate_detector_recall is only about **object proposal** recall, not detection recall?

**Comment by AlexeyAB** [comment]
@kb1ooo Yes, exactly.

**Comment by kb1ooo** [comment]
@AlexeyAB thank you.
