### ISSUE TITLE
opencv version error

### ISSUE THREAD

**Issue by fearless-pilgrim** [pjreddie/darknet#2329]
i just installed opencv4.4.0 and executed successfully,but when i run the darknet_images.py .something going wrong like the followings,i hope someone could help me to solve

  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libopencv_highgui.so.3.4: cannot open shared object file: No such file or directory

I want use opencv4.4.0 for some new functions

**Comment by mmaithani** [comment]
apt-get install libopencv-highgui-dev
