### ISSUE TITLE
Why should this line "assert(l.outputs == params.inputs) " in line 281 of parser.c

### ISSUE THREAD

**Issue by MaeThird** [pjreddie/darknet#236]
What's the job of this assert `assert(l.outputs == params.inputs)  `in line 281 of `parser.c` ?
In my opinion the `parse_region` is doing the assembling works of the regional proposal layer,in which the output is ordinarily as `number_of_proposes*(classes + coordinates +1)`,although in `convolutional_layer` the output is ordinarily calculated as `h*w*filters`.
I mean there is no logical equal between input size and output size of regional proposal layer.
Can any explanation ?

**Comment by jktzes** [comment]
Hi there! Did you by any chance solve the problem? @MaeThird

**Comment by ahsan856jalal** [comment]
@MaeThird  @jktzes  According to my personal experience
If you are using yolov3:
This error happens when your filter value is wrong in any of the convolution layer before [yolo] layer 
It should be = num/3*(classes+5)
If you are using yolov2:
This error happens when your filter value in convolution layer before region layer is wrong
It should be = num*(classes+5)

**Comment by dee6600** [comment]
what is "num"???

**Comment by peymanmortazavi** [comment]
@dee6600 It's set in your configuration file. For yolo3 the default the **9** but you can change this depending on your needs.

**Comment by TheMikeyR** [comment]
@dee6600  num is the amount of anchor-pairs, so if you increase the amount of anchors you should increase num as well.

**Comment by TheMikeyR** [comment]
@dee6600 
https://github.com/pjreddie/darknet/issues/568

**Comment by Dantetheash** [comment]
Hello there,
I am facing the same problem but I am using Yolo-LITE what should be my filter function?
@ahsan856jalal

**Comment by colorfuldarkgray** [comment]
I think num is the number of classes that can overlap in one window.

**Comment by KanchanIIT** [comment]
in the yolov3-voc.cfg file there are three **[yolo]** block. you have to change the filter size for each of the **[convolutional]** block filter size before all the **three [yolo]** block as follow - 
filter size=(num/3)*(classes+5)
In my case, as the classes are 1 and num=9 so the filter size is 18. 

[convolutional]
size=1
stride=1
pad=1
**filters=18**
activation=linear

[yolo]
mask = 6,7,8
anchors = 10,13,  16,30,  33,23,  30,61,  62,45,  59,119,  116,90,  156,198,  373,326
**classes=1
num=9**
jitter=.3
ignore_thresh = .5
truth_thresh = 1
random=1

**Comment by YongLAGCC** [comment]
In your .cfg make sure the "classes = num of your trained object" in each layers

**Comment by Shruthi-Sampathkumar** [comment]
> in the yolov3-voc.cfg file there are three **[yolo]** block. you have to change the filter size for each of the **[convolutional]** block filter size before all the **three [yolo]** block as follow -
> filter size=(num/3)*(classes+5)
> In my case, as the classes are 1 and num=9 so the filter size is 18.
> 
> [convolutional]
> size=1
> stride=1
> pad=1
> **filters=18**
> activation=linear
> 
> [yolo]
> mask = 6,7,8
> anchors = 10,13, 16,30, 33,23, 30,61, 62,45, 59,119, 116,90, 156,198, 373,326
> **classes=1 num=9**
> jitter=.3
> ignore_thresh = .5
> truth_thresh = 1
> random=1

Hi. I am using Yolov3. 
My number of classes is 4. So (num/3)*(number_of_classes+5) = 27. Even after this modification in thr yolov3-voc.cfg file, I am getting the error " darknet: ./src/parser.c:315: parse_yolo: Assertion `l.outputs == params.inputs' failed ". What could I do to solve this?

**Comment by ani16** [comment]
Hi..

I am facing same problem. Earlier i trained with same anchors, It went well. I am using 1 class and num=9. so filters is 18. 

But still error is darknet: ./src/parser.c:273: parse_yolo: Assertion `l.outputs == params.inputs' failed.

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
size=3
stride=1
pad=1
filters=256
activation=leaky

[convolutional]
size=1
stride=1
pad=1
filters=18
activation=linear


[yolo]
mask = 0,1,2
anchors = 0.3249,1.7335,  15.9251,25.1334,  13.4136,38.4485,  15.7293,46.2347,  15.4766,53.0312,  18.2260,59.4649,  22.3400,52.3466,  25.3848,60.4191,  22.9124,84.3554 
num=9
jitter=.3
ignore_thresh = .7
truth_thresh = 1
random=1
 

please help me, earlier it trained well. Is there problem with floating number for anchors. should I make it int.

**Comment by OctaM** [comment]
Same problem here

**Comment by OctaM** [comment]
If your try to run the training from terminal, after you've changed the filters and classes, try to exit the terminal and start it again. It may work like that. And do not forget to save the changes that you made in .cfg file
