### ISSUE TITLE
no bounding box in dog.jpg

### ISSUE THREAD

**Issue by z3rO1997** [pjreddie/darknet#2373]
i can get prediction.png but no bounding box in prediction

**My system**
window 10
cuda 10.2
cudnn for cuda 10.2
opencv 4.0.0

**running detector**
darknet.exe detect cfg/yolov3.cfg yolov3.weights data/dog.jpg
'''
'''
data/dog.jpg: Predicted in 534.353 milli-seconds

i tried to change weights file
and cuda, cudnn, darknet 
but It was useless

**Comment by z3rO1997** [comment]
Solved

**Comment by Venketaramana** [comment]
May i know how you solved it?

**Comment by Doublehes** [comment]
i have  the same problem, can you tell me how you solved it?
