### ISSUE TITLE
How do I find training and testing accuracy after training?

### ISSUE THREAD

**Issue by tamim662** [pjreddie/darknet#2447]
Here, what it shows after training
![yolo_acc](https://user-images.githubusercontent.com/34623418/121240259-f03e8200-c8bb-11eb-96d6-805b0a16bd39.png)

  The command was : 
> !./darknet detector train data/obj.data cfg/yolov3-custom.cfg /content/gdrive/MyDrive/YOLOv3/darknet53.conv.74 -dont_show -map.

From this how do I define what is the training accuracy and testing accuracy?

**Comment by nsbruce** [comment]
@tamim662 what was the answer?

**Comment by tamim662** [comment]
> @tamim662 what was the answer?

@nsbruce if you use -map end of the command, you will get results of map, recall, F1-score for validation set after end of the training.

**Comment by nsbruce** [comment]
Thanks!
