### ISSUE TITLE
What is different of Model size[MB] and BFLOPS?

### ISSUE THREAD

**Issue by ryotaro137** [pjreddie/darknet#2548]
I do not understand the difference between yolo's Modelsize and BFOLPS. 
I would appreciate it if someone could tell me the difference. 
Also, please let me know how to check  yolo's Modelsize .
Thank you in advance.

**Comment by ryotaro137** [comment]
I understand the way of model size by DL pretrained weights. 
Thank you.

**Comment by kXborg** [comment]
Hi @ryotaro137 , what is the command to change the default 416 model size? The paper says that YOLOv3 has works with 3 different sizes.

**Comment by ryotaro137** [comment]
Sorry for delay comments!

You can change model size by **width=608
height=608** in yolov3.cfg.
