### ISSUE TITLE
"Not an option: demo"

### ISSUE THREAD

**Issue by ghost** [pjreddie/darknet#2628]
When attempting to run a custom object detection using YOLOv4 in Darknet on a Windows machine, the following command was executed in the Darknet directory:

darknet.exe demo data/obj.data cfg/yolov4-obj.cfg backup/yolov4-obj_last.weights wick.mp4 -thresh 0.6
The system environment includes CUDA version 10.10 (build 12030), cuDNN version 7.6.5, and 1 GPU detected. OpenCV version 4.4.0 is installed.

However, the execution resulted in an error message stating: "Not an option: demo".

I copied this video: https://www.youtube.com/watch?v=-NEB5P-SLi0&t=33s

With the MS COCO example, i dont got any problems.

**Comment by DanyelR3199** [comment]
darknet.exe detector demo data/obj.data cfg/yolov4-obj.cfg backup/yolov4-obj_last.weights wick.mp4 -thresh 0.6

**Comment by ghost** [comment]
Solution: darknet.exe *detector*demo data/obj.data cfg/yolov4-obj.cfg backup/yolov4-obj_last.weights wick.mp4 -thresh 0.6
