### ISSUE TITLE
CUDA Error: out of memory for new bit

### ISSUE THREAD

**Issue by kwccoin** [pjreddie/darknet#275]
Another minor issue but will trick new comer is facing that one e.g. the image classification.  

Try to edit the cfg file e.g.

    vi cfg/extraction.cfg

and amend the 

    batch=128
    subdivisions=1

to 
   batch=128
   subdivisions=128

For very low memory one like old macbook with only 1G it still fail but at least run a bit.  For 950 with my Mac Pro it is ok with 2G.

**Comment by kwccoin** [comment]
Just an information I like to share

**Comment by AurusHuang** [comment]
With 1GB GPU memory, I can run such configuration successfully: 
```
batch=32
subdivisions=8
```
Higher batch size will cause insufficient memory error.
