### ISSUE TITLE
darknet.c vs darknet.py inference speed difference

### ISSUE THREAD

**Issue by ChloeEHKim** [pjreddie/darknet#282]
Hi,
I'm currently doing some research on the performance of YOLO.
I found out I wasn't able to achieve the FPS which YOLO claims in python.
I was getting 33FPS with tiny-yolo and also similar FPS with normal yolo which doesn't make sense since tiny yolo is much smaller model.
I tried the darknet executable built in C. This gives much faster inference time, almost 10 times faster than the time in python with tiny yolo. 
Is this caused by getting shared lib from python? Is there a way to get better performance in python?
Thanks in advance.

**Comment by encore2020** [comment]
Could you tell me how do you run darknet executable built in C

**Comment by ChloeEHKim** [comment]
@encore2020 Just binary executable 'darknet'
If anyone wondering about this, it was a simple mistake. 
The 'darknet' executable shows only prediction time. 
My python program measured the total time combined the image loading/preprocessing, prediction and post-processing(NMS).
