### ISSUE TITLE
Choose GPU in python interface

### ISSUE THREAD

**Issue by workingforfood** [pjreddie/darknet#291]
Hi, can u help me with python interface. I execute python/darknet.py, by default it is use 0 gpu and i can not find how to use another gpu from python. Probably i have to export some extra fuction from libdarknet.so. Help pls.

**Comment by TheMikeyR** [comment]
You could probably replace all `gpu_index = -1;` to the device id you want and recompile it, but I don't know how to select gpu to run on through the python wrapper.

**Comment by pjreddie** [comment]
huh, this would be useful, i'll add it. h/o....

**Comment by pjreddie** [comment]
ok, look in updated detector.py, can set gpu

**Comment by workingforfood** [comment]
Thanks a lot!

**Comment by liulixia1990** [comment]
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '6'

**Comment by qqish** [comment]
> 
> 
> Hi, can u help me with python interface. I execute python/darknet.py, by default it is use 0 gpu and i can not find how to use another gpu from python. Probably i have to export some extra fuction from libdarknet.so. Help pls.

sorry to disturb, I am using python/darknet.py, but I have not use gpu?
How should I do to use gpu with python/darkenet.py? Should I change some file or just change darknet.py and how?

**Comment by zabir-nabil** [comment]
with python/darknet.py you can do this to select GPU:

```
set_gpu(1) # pass the GPU id
```
