### ISSUE TITLE
Is there trained weights using imagenet net dataset?

### ISSUE THREAD

**Issue by hengshanji** [pjreddie/darknet#299]
Imagenet DET have more categories and images than COCO and VOC datasets , so the model trained by imagenet det maybe better, is yolov2 trained by imagenet det ?

**Comment by TheMikeyR** [comment]
You can read the paper [YOLO9000](https://arxiv.org/pdf/1612.08242.pdf) but to make long story short, yes yolo9000 is trained on ImageNET and 9000 classes.

**Comment by hengshanji** [comment]
I think yolo9000 is trained on the classify data of ImageNet and detection data of COCO not the 200 categories detection data of ImageNet. If yolo9000 is trained on the 200 categories detection data of ImageNet, the performance should be better ?  Is that right?

**Comment by TheMikeyR** [comment]
I can't say whether it will have a better performance or not, since it is speculation, I guess only a test will tell.

**Comment by hengshanji** [comment]
Thank you ,i will try
