### ISSUE TITLE
YOLOv2 training gives "Segmentation fault" after some iterations

### ISSUE THREAD

**Issue by xhuvom** [pjreddie/darknet#303]
I am trying to train a custom dataset using YOLOv2 on a GTX1080 card with Batch size = 64 and Subdivisions = 8. With the tiny-yolo (& any .cfg) after some iterations ( 10~100), it gives segmentation fault (core dumped). I am sure to put the images and labels properly formatted. I have tried with OPENCV = 0 but nothing improved. I also cant figure out how to use the DEBUG option. 
I have tried with different Batch and Subdivision numbers but in vein. I had trained earlier version of YOLO easily but the new version is giving me headache.
![screenshot from 2017-11-11 02-11-01](https://user-images.githubusercontent.com/8438309/32676916-98e361fa-c686-11e7-99d9-b502a89518e2.png)

Can anyone help?

**Comment by xhuvom** [comment]
I can train COCO dataset without any error. However, my own dataset gives the Segmentation fault. I had triple checked the directory structures and label formats.

**Comment by xgl1991714** [comment]
maybe there are some invalid coordinate data like zero in your label files

**Comment by xhuvom** [comment]
Yes I had figured it out. Thanks although.

**Comment by gentlebreeze1** [comment]
how to solve  coordinate data like zero in your label files？

**Comment by gentlebreeze1** [comment]
how to solve coordinate data like zero in your label files？ @

**Comment by gentlebreeze1** [comment]
how to solve coordinate data like zero in your label files？ 
@xhuvom
