### ISSUE TITLE
do not support cuda 8.0?

### ISSUE THREAD

**Issue by SniperZhao** [pjreddie/darknet#321]
compile the code under the env of cuda 8.0 and cudnn 6.0, while get the link error: "/usr/bin/ld: cannot find -lcuda". The path of cuda 8.0 had already been list on the Makefile. The same Makefile can work under the env of cuda 7.5 and cudnn 5.1.

my os: centos 7
compile switch:
    GPU=1
    CUDNN=1
    OPENCV=0
    OPENMP=0
    DEBUG=0

![image](https://user-images.githubusercontent.com/11026164/32954065-ffa8d1b6-cbec-11e7-8c7b-89a4b4e6ee87.png)

**Comment by LiraNeto** [comment]
I only use cuda 8.0, maybe you must chance the path in the Makefile. If it is only "cuda" in something like "/usr/local/cuda/", change to "cuda-8.0"

**Comment by SniperZhao** [comment]
thank you @LiraNeto . I have tried to write the path as "/usr/local/cuda-8.0/lib64/" (as you can see the gcc command on the attached image), however, it's still not work.  crying T_T....

**Comment by michaeldong** [comment]
I meet seem question.  cuda8 ,  not found lcuda

**Comment by SniperZhao** [comment]
this error is because we are using the soft link of /usr/local/cuda/lib64/stubs/libcuda.so. I fixed it by using such command: "cp ./stubs/libcuda.so ../".
