### ISSUE TITLE
Meaning of normalize weight?

### ISSUE THREAD

**Issue by RyuJunHwan** [pjreddie/darknet#327]
I decoded the file darknet19.weights and extracted the weight for
*_conv_biases.txt, *_conv_weights.txt, *_conv_normalize.txt
(ex. 0_conv_biases, 0_conv_weights, 0_conv_normalize.txt )
In my search, normalize has 2 parameters of beta and gamma.
but the extracted weight consists of three parameters.
(ex, 1.290867,-0.002321,0.001940
2.232868,-0.252970,0.026960
1.642115,0.001189,0.020758
0.001826,0.002387,0.000007
...
)
I want to know the each meaning.

**Comment by RyuJunHwan** [comment]
Self-replies. I guess the result is scale, rolling_mean, rolling_variance.

**Comment by Thilanka97** [comment]
@RyuJunHwan I experienced the same thing. I extracted yolov2 tiny-voc weights and I also have *_conv_biases.txt, *_conv_weights.txt, *_conv_normalize.txt files for each conv layer. I am trying to understand what conv_normalize means. Does original yolov2 use normalized weights or is it the normal way when it comes to conv layers in CNNs? 

In the first conv layer of yolov2 tiny, There are 16 filters. In the extracted weights for the first layer, there are 16 bias values which I understand(there are 16 output channels in the output). But in the conv_normalized file, there are 16x3 parameters. what does this mean? does this mean that these normalization parameters apply for each output channel ? 

Also in the _conv_weights.txt file, there are 432 weight values which I dont understand. the filter size is 3x3 and no of filters = 16. doest this mean that there should be 9x16 weight values? But some how there are 3x3x16x3 weight values (filter height x filter width x input depth x output depth) which I dont understand. 

could you please explain these to me. I am in really struggling to understand these matters. Would be a great help if you could help. 

Thanks in advance!
