### ISSUE TITLE
train yolo-voc.2.0 model shows NaN average loss 

### ISSUE THREAD

**Issue by lqian** [pjreddie/darknet#339]
Region Avg IOU: 0.714404, Class: 0.930685, Obj: 0.659256, No Obj: 0.004732, Avg Recall: 0.838710,  count: 31
Region Avg IOU: 0.490125, Class: 0.732451, Obj: 0.482284, No Obj: 0.003236, Avg Recall: 0.571429,  count: 35
Region Avg IOU: 0.536736, Class: 0.857706, Obj: 0.541393, No Obj: 0.003579, Avg Recall: 0.633333,  count: 30
Region Avg IOU: 0.629757, Class: 0.898300, Obj: 0.584671, No Obj: 0.004613, Avg Recall: 0.750000,  count: 32
Region Avg IOU: 0.670304, Class: 0.908461, Obj: 0.657925, No Obj: 0.005837, Avg Recall: 0.738095,  count: 42
25657: 5.307510, **-nan avg**, 0.000100 rate, 14.716343 seconds, 1642048 images

**Comment by JonDuffy** [comment]
Hey, did you get anywhere with this issue?

**Comment by lqian** [comment]
@JonDuffy 
In my experience,  the  case only happen when set **random** parameter as 1, the last row of the yolo-voc.2.0.cfg. All is ok when the parameter value is 0.
