### ISSUE TITLE
CUDA Error: __global__ function call is not configured

### ISSUE THREAD

**Issue by PushyamiKaveti** [pjreddie/darknet#348]
I have successfully compiled and executed darknet code for both training and testing yolo. Now, I am trying to do the same using GPU. I have CUDA 9.0 on ubuntu 16.04 with GTX GEFORCE 1070. I am using -gencode arch=compute_61 code=sm_61 reflecting the right architecture. The code compiles fine but when I try to run it I have the following error.

   22 conv   1024  3 x 3 / 1    13 x  13 x 512   ->    13 x  13 x1024
   23 conv   1024  3 x 3 / 1    13 x  13 x1024   ->    13 x  13 x1024
   24 conv   1024  3 x 3 / 1    13 x  13 x1024   ->    13 x  13 x1024
   25 route  16
   26 conv     64  1 x 1 / 1    26 x  26 x 512   ->    26 x  26 x  64
   27 reorg              / 2    26 x  26 x  64   ->    13 x  13 x 256
   28 route  27 24
   29 conv   1024  3 x 3 / 1    13 x  13 x1280   ->    13 x  13 x1024
   30 conv     30  1 x 1 / 1    13 x  13 x1024   ->    13 x  13 x  30
   31 detection
mask_scale: Using default '1.000000'
Loading weights from darknet19_448.conv.23...Done!
Learning Rate: 0.001, Momentum: 0.9, Decay: 0.0005
Resizing
544
Loaded: 0.000024 seconds
CUDA Error: __global__ function call is not configured
darknet: ./src/cuda.c:36: check_error: Assertion `0' failed.
Aborted (core dumped)

Can someone help me with this.

Thanks.

**Comment by PushyamiKaveti** [comment]
I was actally able to solve it by installing cuDNN library and setting it to 1 in CMakelists.txt file. In case someone has this problem in furture.

**Comment by wsyzzz** [comment]
It help me a lot! Thx!

**Comment by BDHU** [comment]
I encountered this issue recently. For some reason the cublasSgemm() inside gemm_gpu() function returns this error. It's worth mentioning that I didn't compile with cudnn but the problem still persists. Somehow the cublas library isn't included?

**Comment by snakehaihai** [comment]
![image](https://user-images.githubusercontent.com/6070995/86198463-43776300-bb8a-11ea-9bc0-4526ea5c3b21.png)

![image](https://user-images.githubusercontent.com/6070995/86198505-55590600-bb8a-11ea-8441-d928f00153b1.png)
