### ISSUE TITLE
Siamese network

### ISSUE THREAD

**Issue by workingforfood** [pjreddie/darknet#359]
Is there any way to implement siamese network in darknet? Thanks for advices.

**Comment by Fred-Erik** [comment]
Maybe this could help? https://github.com/pjreddie/darknet/blob/56be49aa4854b81b855f6a9daffce4b4ad1fbb9e/src/network.c#L607

**Comment by kb1ooo** [comment]
No, that's not siamese.  The closest thing is "compare.c"  but if you look in "data.c" at that does is stack the second image in the initial input, so your input volume is wxhx6 instead of wxhx3.
