### ISSUE TITLE
missing file  data/coco_val_5k.list for cfg/coco.data

### ISSUE THREAD

**Issue by lqian** [pjreddie/darknet#369]
classes= 80
train  = /home/pjreddie/data/coco/trainvalno5k.txt
#valid  = coco_testdev
**valid = data/coco_val_5k.list**
names = data/coco.names
backup = /home/pjreddie/backup/
eval=coco

**Comment by buaalsy2003** [comment]
coco_val_5k.list is under data/coco/ folder

**Comment by nirjack** [comment]
> coco_val_5k.list is under data/coco/ folder

Its not there!!! Is the path changed or is the file deleted?

**Comment by GiorgioSgl** [comment]
> > coco_val_5k.list is under data/coco/ folder
> 
> Its not there!!! Is the path changed or is the file deleted?

Same problem here actually
