### ISSUE TITLE
any possible to detect both class and color of object in same time?

### ISSUE THREAD

**Issue by lqian** [pjreddie/darknet#380]
In some situation application needs to detect  class and color of object. Naturally we can use two networks. One network detect object class and then another network detect object color. Finally application combines two network detection results for one object.
Hence network costs many GPU computation resource in convolutional layers. Sharing most convolutional computation can save GPU resource. Assume that object has 20 classes and 10 types of color.  Any possible to create a new  network from yolo-voc-2.0. Add color detector like this configuration snippet.

**----- the last origin convolutional layer and region for object class**
`
[convolutional]
size=1
stride=1
pad=1
filters=125
activation=linear

[region]
anchors = 1.08,1.19,  3.42,4.41,  6.63,11.38,  9.42,5.11,  16.62,10.52
bias_match=1
classes=20
coords=4
num=5
softmax=1
jitter=.2
rescore=1

object_scale=5
noobject_scale=1
class_scale=1
coord_scale=1

absolute=1
thresh = .6
random=0`

**----- add convolutional layer and region for color detector**
`[convolutional]
size=1
stride=1
pad=1
filters=75
activation=linear

[region]
anchors = 1.08,1.19,  3.42,4.41,  6.63,11.38,  9.42,5.11,  16.62,10.52
bias_match=1
classes=10
coords=4
num=5
softmax=1
jitter=.2
rescore=1

object_scale=5
noobject_scale=1
class_scale=1
coord_scale=1

absolute=1
thresh = .6
random=0`

**Comment by varmatangoit** [comment]
Is this works for you, because I also need this solution

**Comment by varmatangoit** [comment]
In such case where I need to mention color class name
