### ISSUE TITLE
No detections when using the "test_yolo" function from the "examples/yolo.c" file

### ISSUE THREAD

**Issue by MirzaBe** [pjreddie/darknet#410]
I want to analyse the following image:
![img](https://user-images.githubusercontent.com/34680279/34813231-6df34c00-f6a9-11e7-922c-a3f9e3008f94.png)
When I use the command "./darknet detect cfg/yolo.cfg yolo.weights img.png" it works fine and gives me this:
![predictions](https://user-images.githubusercontent.com/34680279/34813278-a5e32360-f6a9-11e7-8015-0207e3b1f8df.jpg)
But when I use the "test_yolo" function from the "examles/yolo.c" file it gives me nothing. It just shows me the input image. Why?

**Comment by rohitsaluja22** [comment]
hi what command exactly do you use to run examles/yolo.c?
