### ISSUE TITLE
darknet.py predicts the wrong coordinates while the c executable predicts correct ones.

### ISSUE THREAD

**Issue by true-source** [pjreddie/darknet#418]
when I plot a bounding box with the coordinates predicted using darknet.py, i get wrong results. The width and height seems to be right , however the x,y coordinates seems to be wrong.

**Comment by TheMikeyR** [comment]
Take a look here https://github.com/pjreddie/darknet/issues/243#issuecomment-349983900 and see if it can solve your issue.

**Comment by true-source** [comment]
Thanks , it worked!
