### ISSUE TITLE
OSerror: libdarknet.so:cannot open shared object file: no such file or directory

### ISSUE THREAD

**Issue by qiaoguan** [pjreddie/darknet#428]
when i tried to run darknet.py,   some error happened , and i don't know why!!!
![aaa](https://user-images.githubusercontent.com/15955127/35192898-5914557a-fed5-11e7-920e-04d40ae58836.png)

**Comment by baristahell** [comment]
Change the path of the lib in darknet.py and/or execute it from the right place and/or make sure the `make` worked.

**Comment by ashwinvk94** [comment]
It worked when I gave the complete path to libdarknet.so in darknet.py

**Comment by rsaxvc** [comment]
libdarknet.so needs to be in your library paths. You can add libdarknet.so to LD_LIBRARY_PATH, or copy it to /usr/lib/libdarknet.so, or any other path that is included in your library paths.

**Comment by bhanuchander008** [comment]
> Change the path of the lib in darknet.py and/or execute it from the right place and/or make sure the `make` worked.

i dont have libdarknet file

**Comment by ronak34** [comment]
Either keep the libdarknet.so file in the same directory as your python code, or simple give the whole path instead to the CDLL object.

**Comment by ronak34** [comment]
> > Change the path of the lib in darknet.py and/or execute it from the right place and/or make sure the `make` worked.
> 
> i dont have libdarknet file

It means that your make was not successful. Try installing it once again. Follow this instructions: https://pjreddie.com/darknet/install/

**Comment by Cartucho** [comment]
I solved this by adding `import os` on top and then replace that line with: 
`lib = CDLL(os.path.join(os.getcwd(), "libdarknet.so"), RTLD_GLOBAL)`

then should work by running normally the script: `python python/darknet.py`

**Comment by Mahamatnour** [comment]
guys I'm having the same issues, how to change the path of lib in my darknet.py 
pls can someone explain with the steps of how to change?

am just started with darknet but this error is killing me the past two days. 
Thanks.

**Comment by jhallard** [comment]
@Mahamatnour 

in darknet.py, line 48

```
lib = CDLL("libdarknet.so", RTLD_GLOBAL)
```

change this to 

```
lib = CDLL("/Users/home/Mahamatnour/darknet/libdarknet.so", RTLD_GLOBAL)
```

but replace `"/Users/home/Mahamatnour/darknet/libdarknet.so"` with the path to the `libdarknet.so` file on *your* actual machine.

If you don't know where that is, try this

```bash
find ~ -name libdarknet.so
```

that should output something like 

```bash
john@my-server:~/darknet/python$ find ~ -name libdarknet.so
/home/john/darknet/libdarknet.so
```

**Comment by lrustand** [comment]
> i dont have libdarknet file

+1.

I don't have the libdarknet.so file either. And the make worked just fine and no reported errors. I can run the darknet binary and do training, testing etc. But the python scripts fail with 
```OSError: ./libdarknet.so: cannot open shared object file: No such file or directory```

**Comment by zonasw** [comment]
If you cannot find lib.so, you can remake and change the Makefile`LIBSO=1`

**Comment by ggosiang** [comment]
Same here, can't find `libdarknet.so` after cmake
https://github.com/AlexeyAB/darknet#how-to-compile-on-linux-using-cmake

If setting `LIBSO=1` can be solved in make
Which value should be set in cmake?

**Comment by qboticslabs** [comment]
Hey @ggosiang @zonasw  @lrustand 

I had this same issue. 
Using Makefile, it doesn't generate libdarknet.so, but using CMakeLists.txt, it does.
 What I did was, I built it using CMake and got the .so as libdark.so, then I renamed and put it in the darknet.py folder, now it's working fine.

**Comment by ggosiang** [comment]
@qboticslabs 
I can get `libdarknet.so` by setting `LIBSO=1` within Makefile

**Comment by Commando-one** [comment]
> Hey @ggosiang @zonasw @lrustand
> 
> I had this same issue.
> Using Makefile, it doesn't generate libdarknet.so, but using CMakeLists.txt, it does.
> What I did was, I built it using CMake and got the .so as libdark.so, then I renamed and put it in the darknet.py folder, now it's working fine.

Can you please tell me how to make darknet with CMakeLists.txt instead of Makefile?

**Comment by qboticslabs** [comment]
Hi @Commando-one 

Can you check the following [blog post ](https://robocademy.com/2020/05/01/a-gentle-introduction-to-yolo-v4-for-object-detection-in-ubuntu-20-04/)I have written about this?

**Comment by Commando-one** [comment]
> Hi @Commando-one
> 
> Can you check the following [blog post ](https://robocademy.com/2020/05/01/a-gentle-introduction-to-yolo-v4-for-object-detection-in-ubuntu-20-04/)I have written about this?

Worked for me, thanks

**Comment by blackCmd** [comment]
> @qboticslabs
> I can get `libdarknet.so` by setting `LIBSO=1` within Makefile

Yes Thank you it works!

**Comment by abubakar0015** [comment]
Trying to load **libdarknet.so**  and facing this issue:

`Traceback (most recent call last):
  File "D:/alpr-unconstrained-master/alpr_video.py", line 6, in <module>
    import darknet.python.darknet as dn
  File "D:\alpr-unconstrained-master\darknet\python\darknet.py", line 70, in <module>
    lib = CDLL("darknet/libdarknet.so", RTLD_GLOBAL)
  File "D:\InstalledPrograms\Anaconda3\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'D:\alpr-unconstrained-master\darknet\libdarknet.so' (or one of its dependencies). Try using the full path with constructor syntax.`

Operating System:
Windows 10 64-bit
Darknet .so make using **cygwing64** terminal. 
Python Version 3.8

**Note:** If i use Ubuntu terminal for Window 10 to make **libdarknet.so**  and run python code using Ubuntu terminal, everything works fine. Please help me to resolve this issue for windows 
thanks

**Comment by sodi16** [comment]
Please i need help
I dont have libdarknet.so file and i also dont have LIBSO within Makefile
Is there a new update of the darknet or can someone help me 
Thanks

**Comment by MedAliMimouni** [comment]
> @qboticslabs
> I can get `libdarknet.so` by setting `LIBSO=1` within Makefile

Thanks, it worked

**Comment by rickkcir** [comment]
if you used "find / name libdarknet.so" command and finded it, I guess you should run "chmod 755 libdarknet.so" to change the authority.

**Comment by Flo0620** [comment]
> If you cannot find lib.so, you can remake and change the Makefile`LIBSO=1`

I had to set 'OPENCV=1' as well

**Comment by Chinmay88** [comment]
Could someone please help me to solve the following query?

4 from darknet import performDetect as scan
5 import math
 
ImportError: cannot import name 'performDetect' from 'darknet' (/content/drive/MyDrive/YOLO_v4_R2/darknet/darknet.py)

**Comment by TDiblik** [comment]
> Trying to load libdarknet.so and facing this issue

@abubakar0015 did you resolve this issue? I've done these steps on windows 11 and had the same issue as you do:

```
conda deactivate \
&& yes | conda env remove -n alpr-unconstrained \
&& yes | conda update -n base -c defaults conda \
&& yes | conda create -n alpr-unconstrained python=3.8 \
&& conda activate alpr-unconstrained \
&& yes | pip install keras==2.9.0 numpy pandas==1.4.3 tensorflow==2.9.1 cython==0.29.30 \
&& conda config --env --add channels nvidia \
&& yes | conda install -c menpo opencv=4.6.0 cuda-toolkit=11.7.0 cudnn=8.4.1.50 cuda-nvcc=11.7.64 cuda-runtime=11.7.0 cuda-libraries=11.7.0 cuda-cudart=11.7.60

cd darknet

vim ./examples/go.c

Add include to ./examples/go.c: #include <winsock2.h>

vim Makefile

Add LDflags: -L"ws2_32" -lwsock32

make

bash get-weights.sh

2to3 -W -n .

bash run.sh -i ../input/ -o ../tmp/output -c ../tmp/output/results.csv
```

I'm getting this error:
```
Traceback (most recent call last):
  File "vehicle-detection.py", line 6, in <module>
    import darknet.python.darknet as dn
  File "C:\Users\TomDibla\Downloads\pokus\alpr-unconstrained\darknet\python\darknet.py", line 49, in <module>
    lib = CDLL(os.path.join(*[os.getcwd(), "darknet", "libdarknet.so"]), RTLD_GLOBAL) // This line of code is also custom, to provide full path
  File "C:\Users\TomDibla\anaconda3\envs\alpr-unconstrained\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\TomDibla\Downloads\pokus\alpr-unconstrained\darknet\libdarknet.so' (or one of its dependencies). Try using the full path with constructor syntax.
```

I am 100% prositive that libdarknet.so IS in fact present in that path and compiled sucessfully.

Did you resolve this issue? I also tried and compiled sucessfully in WSL Ubuntu 2 (with anaconda python 2.7), however I was unable to get GPU build working there (because of the virtualization), so I'm trying to compile darknet under windows.

With GPU build in WSL, I had following runtime error:
```
CUDA Error: no kernel image is available for execution on the device
python: ./src/cuda.c:36: check_error: Assertion `0' failed.
run.sh: line 90: 15412 Aborted                 python vehicle-detection.py $input_dir $output_dir
```

**Comment by BaraaHammoud** [comment]
hi guys can anyone help me i have this error when i am trying to run darknet yolov3, my project deadline is near and i dont have a lot of time , the error is : error while loading shared libraries: opencv_core460.dll no such file or directory
