### ISSUE TITLE
Does region layer have parameter in weights model file?

### ISSUE THREAD

**Issue by ysh329** [pjreddie/darknet#430]
Thanks in advance. I converted a darknet YOLOv2 model to caffe but not sure whether region layer has parameters in `caffemodel`.  😢

**Comment by liwei46** [comment]
No. Only the convolution layer have parameters.

**Comment by baristahell** [comment]
Yeah the other parameters like inputs and region are found in the .cfg so there's no point saving those.

**Comment by ysh329** [comment]
@liwei46 @baristahell Thanks guys 😽
