### ISSUE TITLE
How to change the display language of predictions?

### ISSUE THREAD

**Issue by ycjcl868** [pjreddie/darknet#435]
I run the command
```bash
$ ./darknet detect cfg/yolo.cfg yolo.weights data/pic.jpg
```

I'd like to display other language like Chinese, What should I do ?  

![image](https://user-images.githubusercontent.com/13595509/35367666-8d5f7da4-01ba-11e8-99a7-c806ae037279.png)

**Comment by sivagnanamn** [comment]
Check this repo & commit. It supports chinese labels.

[https://github.com/PaulChongPeng/darknet](https://github.com/PaulChongPeng/darknet)

[https://github.com/PaulChongPeng/darknet/commit/798fe7cc4176d452a83d63eb261d6129e397a521](https://github.com/PaulChongPeng/darknet/commit/798fe7cc4176d452a83d63eb261d6129e397a521)

**Comment by baristahell** [comment]
Isn't it just tied to what you wrote in your .names ?

**Comment by sivagnanamn** [comment]
For using non-english class names in YOLO V1 - I had to generate the images of the class names using "make_labels.py" and place it under "data/labels" folder. I believe its the same for YOLO V2 as well. In the repo mentioned in my previous comment, I saw that the author had used "make_labels_cn.py" to generate labels with chinese characters.

**Comment by beizhengren** [comment]
hello, have you sloved the problem?

**Comment by MazharBukhari** [comment]
I want to have yolo labels in Urdu language but I have seen the chinese make_labels.py and chinese verson is also not working on my system
