### ISSUE TITLE
darknet resnet50/152 classifier on 32bit x86 ubuntu system

### ISSUE THREAD

**Issue by hiwudery** [pjreddie/darknet#442]
Hi all:
I try the imagenet classify according to the following page. 
https://pjreddie.com/darknet/imagenet/
on x64 64bit ubuntu 16.04 system, all the examples works well.
on x86 32bit ubuntu 16.04 system, resnet50 and resnet152 do not work. Resnet50 and Resnet152 run for a long time without any results.

All the compile options are default
GPU=0
CUDNN=0
OPENCV=0
OPENMP=0
DEBUG=0

What's wrong with the darknet programs?
Thank you

**Comment by shizukachan** [comment]
fix the weight file loading code like this:
https://github.com/shizukachan/darknet-nnpack/commit/fe963ca3b156ffdc30be8721e21ed016786e3dc7

**Comment by hiwudery** [comment]
Thank you shizukachan. The patch works well.
