### ISSUE TITLE
Detection works using 'darknet detector test', but fails when using Python wrapper

### ISSUE THREAD

**Issue by saihv** [pjreddie/darknet#467]
I've used Darknet to train tiny YOLO on a custom dataset and I'm trying to use it for inference. In my test dataset, I am facing a weird issue: when I run `darknet detector test`, the images that work without any problems and give reasonably accurate class/bounding box data fail to work completely using the inbuilt Python script. But the Python script doesn't fail for all the images in my test dataset, about 40% of them work okay. For the ones that fail, the output from the `detect` function in darknet.py is just a blank `[]`. 

I have tried this on various platforms: such as the Jetson TX2, Nvidia GTX 1080Ti and a GTX 960M. I am using Python 2.7 and have built Darknet with CUDA, CUDNN and OPENCV enabled. It'd be helpful to get some suggestions as to how to debug this issue further and what could be causing it. Thanks!

**Comment by saihv** [comment]
This was because in [line 114](https://github.com/pjreddie/darknet/blob/master/python/darknet.py#L114), the detect function defaults to returning classes only with a probability of more than 50%. Manually setting a threshold in this probability returned the classes and bounding boxes successfully.

**Comment by ahsan856jalal** [comment]
use this command 
`./darknet detector test data/obj.data yolo-obj.cfg yolo-obj_8000.weights data/dog.jpg -thresh 0.2
`if you want your threshold to be 0.2

**Comment by evandrix** [comment]
I don't see any additional threshold argument in the original c source code https://github.com/pjreddie/darknet/blob/master/src/network.c#L579
