### ISSUE TITLE
Custom network - Pretrained weights?

### ISSUE THREAD

**Issue by groot-1313** [pjreddie/darknet#472]
I have modified the cfg file to use a different base network. But I dont have a pretrained weights file corresponding to my base network. Is there any way for the weights to be initialized randomy so that the training command would just be:

`./darknet detector train cfg/obj.data cfg/yolo.cfg`

Because I do not have the corresponding `darknet19_448.conv.23` file for the network I am using.

**Comment by TheMikeyR** [comment]
The AlexeyAB's fork is capable of launching with randomized weights https://github.com/AlexeyAB/darknet/

**Comment by groot-1313** [comment]
Thanks
