### ISSUE TITLE
Cannot load image

### ISSUE THREAD

**Issue by antnh6** [pjreddie/darknet#478]
I'm trying to reproduce this [tutorial](https://timebutt.github.io/static/how-to-train-yolov2-to-detect-custom-objects/) to make sure I understand how things work before training on my data, so I am using his dataset and labels.
I am not very sure how to structure the files so I guess the issue has something to do with it.
I am training on an AWS EC2 [server](https://aws.amazon.com/marketplace/pp/B077GCZ4GR?qid=1518972525205&sr=0-8&ref_=srh_res_product_title)  with CUDA 8 and OpenCV 3 pre-installed.

main directory darknet
- cfg
   - obj.data 
   - yolo-obj.cfg (copied yolo-voc.2.0.cfg and changed batch to 64, subdivisions to 8, classes to 1 and filters to 30)
   - obj.names (has exactly one word 'NFPA')
- data
   - nfpa
       - all the .jpg files and their corresponding .txt files (bounding box)

I am guessing obj.data is the culprit
> classes= 1
train = data/nfpa/train.txt
valid  = data/nfpa/test.txt
names = data/obj.names
backup = backup/

Part of my Makefile
> GPU=1
CUDA=1
CUDNN=1
OPENCV=1
OPENMP=0
DEBUG=0

My issue is ![yolo](https://user-images.githubusercontent.com/12288545/36354575-9748e31c-14a4-11e8-8b11-6a43766666eb.png)
I have checked the text files and the values are normal (not infinity).

Please help. Thank you!

**Comment by TheMikeyR** [comment]
From the screenshot it seems like you have labels (.txt) and images in same folder it should be in the form of:
- datafolder/
     - images/
     - labels/

train.txt should contain paths to:
- datafolder/images/000.jpg 
- datafolder/images/001.jpg 
- datafolder/images/XXX.jpg 

and then your labels should be placed and have the structure like this:
- datafolder/labels/000.txt
- datafolder/labels/001.txt 
- datafolder/labels/XXX.txt

To be able to provide better help I would like the following:
- Post a small snippet of train.txt 
- Post all contents of cfg/yolo-obj.cfg
- Absolute path data folder
- Absolute path to darknet folder (I guess your screenshot answer this: home directory)
- Post one-three label files (their content)

**Comment by antnh6** [comment]
Sorry, I forgot to update. I downloaded the VOC dataset and set it up as instructed in the README and things are working now. Before, I got my images and labels folders all mixed up. Thank you for your help :)

**Comment by Mps24-7uk** [comment]
I am getting the same issue Cannot load image "./darknet/dataset/z1.jpg" STB Reason: can't fopen  Please help me with this @antnh6 @sachindesh @TheMikeyR

**Comment by faisalshahbaz** [comment]
i have same issue:
images *.jpg convert into *.png format.
Fixed.

**Comment by LeRoii** [comment]
> i have same issue:
> images *.jpg convert into *.png format.
> Fixed.

I have the same problem, and it worked when I used a png format, but why this happened
