### ISSUE TITLE
Train YOLO using own data set

### ISSUE THREAD

**Issue by rucsacman** [pjreddie/darknet#487]
I want retrain the yolo for only detect single class as a exmaple only want detect "STOP" sign .So i want remove all other weight files and I want only my weight file how can i do this.

**Comment by ahsan856jalal** [comment]
change the yolo-voc.cfg file ,batches=64,subdivision=8, last convolution layer's filter=30 and classes in region layer to be 1 and modify your_data.data and your_data.names files . then start training
./darknet detector train cfg/your_data.data  cfg/yolo-voc.cfg darknet19_448.conv.23 
Then use this trained model for one class detector

**Comment by rucsacman** [comment]
Can you explain bit more very new to YOLO

**Comment by drforester** [comment]
I made a document to help me and my colleagues remember how to do this. Maybe it could help you too: https://github.com/drforester/Guide_to_using_YOLOv2

**Comment by rucsacman** [comment]
Thank you !!

**Comment by mehditlili** [comment]
@rucsacman did you fork the repository containing the guide? drforester account has been deleted

**Comment by t-mullen** [comment]
It was archived: https://web.archive.org/web/20180617164046/https://github.com/drforester/Guide_to_using_YOLOv2
