### ISSUE TITLE
fish classification training

### ISSUE THREAD

**Issue by ahsan856jalal** [pjreddie/darknet#496]
When I train yolov2 on fish dataset having 20 classes, results are not as good as training on VOC or COCO dataset. Fish on average, are small in the dataset so I find the new anchors using kmeans on width and height of the ground truth boxes. Detection is still low compared to other datasets training.

**Comment by Laranto** [comment]
Do you use a partial classification weights file which has been trained on the fishes? Whats your result in plain classification?

**Comment by ahsan856jalal** [comment]
is there any classification weights trained on fishes ? I tried with pre-trained darknet19_448.conv.23 weights as well as random weights, both cases gave me poor detection. Moreover, I also tried one class fish detection but that also failed .  May be dataset is of very poor quality

**Comment by AvaniPitre** [comment]
Hi @ahsan856jalal  did find any pretrained weights on fishes? or do I have to train a fresh?I want to do fish detection with yolo.

**Comment by ahsan856jalal** [comment]
The problem was with the darknet which I cloned . Now I am using fresh copy of AlexeyAB's fork of darknet. Fish classification is running like a charm. I used darknet19_448.conv weights as the starting point.

**Comment by ahsan856jalal** [comment]
@AvaniPitre darknet19_448 weights trained on imagenet are good enough to start with.

**Comment by AvaniPitre** [comment]
thanks for reply, I will start with weights you suggested

**Comment by AvaniPitre** [comment]
@ahsan856jalal   thank you very much.. classifier is really working very well on fish data.. 
I need to do a bounding box prediction , is it not possible with darknet19_448 weights?  it supports only classification? As
./darknet detector test or ./darknet detect  command does not work on any image file  with above weights.
Can any one tell me what steps I need to follow for bounding box detection with darknet19_448 weights?

thanks in advance

**Comment by ahsan856jalal** [comment]
Actually I trained a detector using darknet19-448 weights as pretrained
model.
. /darknet detector train obj.data fish.cfg fish.weights
After training I used. /darknet detector test as well as demo, both worked
fine

**Comment by AvaniPitre** [comment]
@ahsan856jalal hello thanks for your constant feedback...
I started with training after marking objects using https://github.com/AlexeyAB/Yolo_mark I have around 600 images with only one class, I have started training with darknet19-448 weights

**Comment by ahsan856jalal** [comment]
Can I know which dataset are you using foe fish classification task

Regards
Ahsan

**Comment by AvaniPitre** [comment]
I am using some custom data from fish tanks , to be precise it is a object detection(fish) task for some specific purpose and not a fish classification problem.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by ahsan856jalal** [comment]
Thank you for the reply.
