### ISSUE TITLE
-dest and -write options not working in test mode

### ISSUE THREAD

**Issue by sowmyadvn** [pjreddie/darknet#498]
I trained YOLO model for my own dataset and could get good confidence score while running the tests.  However, I am unable to store the results into a file using the -dest option and -write option. The command I used is:

`./darknet detector test obj.data yolo-obj.cfg backyp/yolo-obj_40000.weights image1.jpg -write 1 -dest ./bbox1.txt`

When I test the command using -thresh option, it works absolutely fine. Please let me know if I didn't do anything right. Thanks for the help.

**Comment by sivagnanamn** [comment]
The `./darknet test` function does not save the output to a file.

From your command, it seems that you would like to save the predicted bounding box information to a file.

To do that, create a `test.txt` file containing the paths of all the images that you would like to test. Then edit your `obj.data` file with `valid=<path to test.txt>`. Then use the command below:

`./darknet detector valid obj.data yolo-obj.cfg backup/yolo-obj_40000.weights`

This will save all the predicted bounding boxes information in the `results` folder. Make sure `names.list` file contains your class labels.

**Comment by sowmyadvn** [comment]
@sivagnanamn 

Thanks for your quick reply. By `names.list` ,  do you mean obj.names which has list of class names?

**Comment by sivagnanamn** [comment]
Yes, the file with the class names.

**Comment by sowmyadvn** [comment]
Thank you. I was able to solve the issue.
