### ISSUE TITLE
darknet: ./src/cuda.c:36: check_error: Assertion `0' failed.

### ISSUE THREAD

**Issue by xu932** [pjreddie/darknet#499]
I got this error message when running `./darknet detect cfg/yolo.cfg yolo.weights data/dog.jpg` with GPU enabled only (no opencv or anything else):

`layer     filters    size              input                output`
`    0 CUDA Error: out of memory`
`darknet: ./src/cuda.c:36: check_error: Assertion '0' failed.`
`Aborted (core dumped)`

Here is my graphics setup:
`lshw -C display`
`WARNING: you should run this program as super-user.`
`  *-display               `
`       description: VGA compatible controller`
`       product: GM107GL [Quadro K620]`
`       vendor: NVIDIA Corporation`
`       physical id: 0`
`       bus info: pci@0000:02:00.0`
`       version: a2`
`       width: 64 bits`
`       clock: 33MHz`
`       capabilities: vga_controller bus_master cap_list rom`
`       configuration: driver=nvidia latency=0`
`       resources: irq:43 memory:f4000000-f4ffffff memory:e0000000-efffffff memory:f0000000-f1ffffff ioport:d000(size=128) memory:f5000000-f507ffff`
`  *-display`
`       description: 3D controller`
`       product: GK110BGL [Tesla K40c]`
`       vendor: NVIDIA Corporation`
`       physical id: 0`
`       bus info: pci@0000:03:00.0`
`       version: a1`
`       width: 64 bits`
`       clock: 33MHz`
`       capabilities: bus_master cap_list`
`       configuration: driver=nvidia latency=0`
`       resources: irq:50 memory:f6000000-f6ffffff memory:c0000000-cfffffff memory:d0000000-d1ffffff`
`  *-display`
`       description: VGA compatible controller`
`       product: NVIDIA Corporation`
`       vendor: NVIDIA Corporation`
`       physical id: 0`
`       bus info: pci@0000:04:00.0`
`       version: a1`
`       width: 64 bits`
`       clock: 33MHz`
`       capabilities: vga_controller bus_master cap_list rom`
`       configuration: driver=nvidia latency=0`
`       resources: irq:51 memory:f2000000-f2ffffff memory:a0000000-afffffff memory:b0000000-b1ffffff ioport:c000(size=128) memory:f3000000-f307ffff`
`WARNING: output may be incomplete or inaccurate, you should run this program as super-user.`

**Comment by gangyahaidao** [comment]
you should set CUDNN=1 in Makefile! donot only set GPU=1

**Comment by jantman** [comment]
I got this same issue... @xu932 did you figure out a fix for this?
