### ISSUE TITLE
structure image to cv::Mat conversion

### ISSUE THREAD

**Issue by komalpharate** [pjreddie/darknet#501]
Hi,
The following structure defined in darkenet.h file
`
typedef struct {
    int w;
    int h;
    int c;
    float *data;
} image;

`
I want to convert this structure image to cv::Mat type
Can I do that?

**Comment by komalpharate** [comment]
I got the solution
So closing the issue
https://stackoverflow.com/questions/22739320/how-can-i-initialize-a-cvmat-with-data-from-a-float-array

**Comment by komalpharate** [comment]
Reopening the issue as I was able to convert float[] to image.
But not bale to convert the float* data in  structure image to cv::Mat

**Comment by ou525** [comment]
@komalpharate Is this problem solved, can you provide the code?
