### ISSUE TITLE
OpenCV visualization error

### ISSUE THREAD

**Issue by mkisantal** [pjreddie/darknet#518]
I built Darknet with OpenCV without a problem, and even imtest works well:
`./darknet imtest data/eagle.jpg` opens up a number of windows without a problem.

However, when I try to run YOLO object detection, I run into the following error:
```Loading weights from yolo.weights...Done!
data/dog.jpg: Predicted in 0.215194 seconds.
dog: 82%
car: 27%
truck: 65%
bicycle: 85%
OpenCV(3.4.1-dev) Error: Assertion failed ((flags & FIXED_TYPE) != 0) in type, file /opt/opencv/modules/core/src/matrix_wrap.cpp, line 807
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(3.4.1-dev) /opt/opencv/modules/core/src/matrix_wrap.cpp:807: error: (-215) Assertion failed: (flags & FIXED_TYPE) != 0 in function type

Aborted (core dumped)
```

So the inference runs without any problem, but the program crashes when it tries to show the results... Any idea what might be causing the problems here?

**Comment by mkisantal** [comment]
This line causes the error, by commenting it out I was able to show the detection results.
https://github.com/pjreddie/darknet/blob/80d9bec20f0a44ab07616215c6eadb2d633492fe/examples/detector.c#L619

**Comment by TheMikeyR** [comment]
I can see you are using OpenCV 3.4.1, there is currently a bug in C API: https://github.com/opencv/opencv/issues/10963
Use OpenCV 3.4.0 or lower.

**Comment by mkisantal** [comment]
Thank you @TheMikeyR it solved my issue!

**Comment by maelvalais** [comment]
Same issue in https://github.com/maelvalais/homebrew-amc/issues/4. Looks like `cvSaveImage` fails but I can't find out why ☹️ Is opencv/opencv#10963 responsible for this bug?

**Comment by molyswu** [comment]
Hi,mkisantal 
How do you solved with this problem?

**Comment by maelvls** [comment]
I dropped the C headers and used the C++ bindings instead 👍
The C API is broken and isn’t maintained anymore
