### ISSUE TITLE
Yolo on Ec2

### ISSUE THREAD

**Issue by mathis94** [pjreddie/darknet#520]
Hello.
I tried to launch Yolo on a Ubuntu deep learning ec2 instance. All the installation went fine until I start the script with an external mp4 video. 
It starts to do something until I get an error that says that Yolo cant find display (normal).
Is there any work around to avoid this error knowing that I just want to search object on an external video I uploaded and download the result video (I don't need to use a webcam or such)
Thanks

**Comment by AlexeyAB** [comment]
Hi,

Try to use this fork: https://github.com/AlexeyAB/darknet
And use this command: `./darknet detector demo data/coco.data cfg/yolo.cfg yolo.weights test.mp4 -i 0 -out_filename result.avi -dont_show`

For training on EC2 using that fork, you also should use flag `-dont_show`

**Comment by mathis94** [comment]
Thx
