### ISSUE TITLE
store webcam detection in a video file

### ISSUE THREAD

**Issue by nehalb123** [pjreddie/darknet#541]
How can I store the real time detection by webcam in a `test-video.mp4` (or any other extension) file?
Is there any other way to run darknet on one machine and display it on another machine or website in real time?

**Comment by AlexeyAB** [comment]
You can use this fork: https://github.com/AlexeyAB/darknet

Using this command - result video will be saved to the file `res.avi` and will be showed in the browser (Chrome/Firefox, but doesn't supported IE) `http://127.0.0.1:8090` or from remote PC using your IP-address.

* Linux: `darknet.exe detector demo data/voc.data yolo-voc.cfg yolo-voc.weights test.mp4 -i 0 -http_port 8090 -out_filename res.avi`

* Windows: `darknet.exe detector demo data/voc.data yolo-voc.cfg yolo-voc.weights test.mp4 -i 0 -http_port 8090 -out_filename res.avi`

**Comment by nehalb123** [comment]
It worked but please remove `test.mp4` from the above commands...Thank you!

**Comment by nehalb123** [comment]
@AlexeyAB  For some reason https://github.com/AlexeyAB/darknet runs very slow on Nvidia Jetson TK1.

**Comment by nehalb123** [comment]
@AlexeyAB What protocol is being used to stream the video?

**Comment by chrisrapson** [comment]
I had a similar issue that `./darknet detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights 0000.mp4 -i 0 -out_filename 0000_out.avi` wasn't producing an output file or an error message. The AlexeyAB fork works.

Could you please explain what the difference is, and possibly merge the changes back to this repo?

**Comment by AlexeyAB** [comment]
@chrisrapson Some differences: https://github.com/AlexeyAB/darknet/issues/529#issuecomment-377204382

**Comment by sunshower76** [comment]
How take screenshot webcam when object is detected ?
I am trying but it's difficult..

**Comment by sumeet9096** [comment]
how to store webcam video in darknet?

**Comment by sumeet9096** [comment]
how to store webcam video in darknet

**Comment by sumeet9096** [comment]
how to store video of object detection when webcam starts?

**Comment by jesseddeng** [comment]
The ouput avi file I got was always 0kb.
Anyone know how to slove it?
Thank you so much!

**Comment by c2h2** [comment]
need to open a new issue @jesseddeng, I found the issue too.

**Comment by jesseddeng** [comment]
> need to open a new issue @jesseddeng, I found the issue too.

I used different decoder from demo.c file and sloved the problem!

**Comment by c2h2** [comment]
@jesseddeng which codec did you choose?
