### ISSUE TITLE
Issues making darknet with OpenCV support: undefined reference to Qt libraries

### ISSUE THREAD

**Issue by raggot** [pjreddie/darknet#543]
I have an issue when trying to compile darknet with OpenCV support. I have already tried the following things:
- make sure Qt5 is installed, and checked its version with `qtdiag`: Qt 5.5.1 
- reinstall Qt5 via `apt get`
- add the Qt5 folder (and all subfolders where lie the headers containing the functions mentioned in the error messages) to PATH, LD_LIBRARY_PATH _and_ to LIBRARY_PATH
- made sure my anaconda folder (which initially gave me trouble) is _not_ in the path. I even renamed the anaconda folder.

Here follows the outcome of `make -j4`. 

```
make -j4
gcc -Iinclude/ -Isrc/ -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -Wall -Wno-unknown-pragmas -Wfatal-errors -fPIC -Ofast -DOPENCV -DGPU obj/captcha.o obj/lsd.o obj/super.o obj/art.o obj/tag.o obj/cifar.o obj/go.o obj/rnn.o obj/segmenter.o obj/regressor.o obj/classifier.o obj/coco.o obj/yolo.o obj/detector.o obj/nightmare.o obj/attention.o obj/darknet.o libdarknet.a -o darknet -lm -pthread  `pkg-config --libs opencv`  -L/usr/local/cuda/lib64 -lcuda -lcudart -lcublas -lcurand -lstdc++  libdarknet.a
/usr/local/lib/libopencv_highgui.so: undefined reference to `QWidget::isFullScreen() const@Qt_5'
/usr/local/lib/libopencv_highgui.so: undefined reference to `QAbstractSlider::setMinimum(int)@Qt_5'
/usr/local/lib/libopencv_highgui.so: undefined reference to `non-virtual thunk to QBoxLayout::minimumSize() const@Qt_5'
/usr/local/lib/libopencv_highgui.so: undefined reference to `QWidget::hasHeightForWidth() const@Qt_5'
/usr/local/lib/libopencv_highgui.so: undefined reference to `QFrame::changeEvent(QEvent*)@Qt_5'
/usr/local/lib/libopencv_highgui.so: undefined reference to `QObject::QObject(QObject*)@Qt_5'
/usr/local/lib/libopencv_highgui.so: undefined reference to `QFutureInterfaceBase::setThreadPool(QThreadPool*)@Qt_5'
/usr/local/lib/libopencv_highgui.so: undefined reference to `QWidget::closeEvent(QCloseEvent*)@Qt_5'
/usr/local/lib/libopencv_highgui.so: undefined reference to `QWidget::hideEvent(QHideEvent*)@Qt_5'
/usr/local/lib/libopencv_highgui.so: undefined reference to `QAbstractSlider::value() const@Qt_5'
/usr/local/lib/libopencv_highgui.so: undefined reference to `QObject::connectNotify(QMetaMethod const&)@Qt_5'
/usr/local/lib/libopencv_highgui.so: undefined reference to `QPen::QPen(QBrush const&, double, Qt::PenStyle, Qt::PenCapStyle, Qt::PenJoinStyle)@Qt_5'
/usr/local/lib/libopencv_highgui.so: undefined reference to `QWaitCondition::wait(QMutex*, unsigned long)@Qt_5'

```

What version of Qt5 is actually required?
What could be the problem? 

Thanks in advance for your time.

**Comment by Hanlin1233** [comment]
I have the same problem. Have you solved it?

**Comment by raggot** [comment]
No, I haven't. I ran out of ideas and the next thing I'll try for that project will be a totally different path not involving darknet.

**Comment by raggot** [comment]
I solved it. Not sure if my personal solution will be of any use to others, but it's been summarised in these SE questions:
https://askubuntu.com/questions/1011636/opencv-undefined-references-for-libqt5core-so-5
https://stackoverflow.com/questions/49097771/issues-with-qt-trying-to-make-darknet-with-opencv-support
https://stackoverflow.com/questions/49761751/why-does-cmake-use-anacondas-python

Good luck!
