### ISSUE TITLE
YOLOv1 no use

### ISSUE THREAD

**Issue by Tshzzz** [pjreddie/darknet#544]
i follow this page,and try to run yolov1

https://pjreddie.com/darknet/yolov1/

wget http://pjreddie.com/media/files/yolov1.weights
./darknet yolo test cfg/yolov1/yolo.cfg yolov1.weights data/dog.jpg

but nothing is detected. I run yolov2 is all right

**Comment by pjreddie** [comment]
I think i had some of the weight files wrong, if you follow the current instructions it should work now. (you'll have to redownload the weights). that being said, v1 is very bad compared to the latest and greatest!
