### ISSUE TITLE
Wrong boxes when using libdarknet.so with C++

### ISSUE THREAD

**Issue by umaso** [pjreddie/darknet#546]
Hey, guys.
I've got a problem when using the generated "libdarknet.so" file in my c++ code.
I was using the method "network_detect"  to predict my image, and the result turns out to be quite big :
box.x 374.601349
box.y 336.307922
box.w 43.162476
box.h 36.782146
That's not the same answer like the official method gives me ( as persentage ).
then I checked the source code , changed the last parameter into 1
        get_region_boxes(l, im.w, im.h, net->w, net->h, thresh, probs, boxes, 0, 0, 0, hier_thresh, 0);
cause the official method " test_detector() " using it as 1.
Then I got the answer as persentage ,like below:
box.x 0.644136
box.w 0.543698
box.y 0.489502
box.h 0.547891
BUT when I was using the origin method : ./darknet detect cfg/yolo.cfg yolo.weights data/sample.jpg
the results:
box.x 0.644136
box.w 0.543698
box.y 0.481336
box.h 0.974029
Ass you can see , y and h of my results gets lower than the original one.So my box can wrap the object perfectly in X axis , but not well enough in Y axis.
I'm using Ubuntu 16.04 ,cuda 8.0 ,  darknet  compiled with OpenCV and GPU.
BTW libdarknet.a gots problem when I use it.
Undefined "getCUDAService" ,no problem occurs when I use libdarknet.so.

**Comment by umaso** [comment]
I resized the image twice  ..so stupid

**Comment by chengtingting** [comment]
hello, how can you link libdarknet.so successfully?　I have add the "link_libraries("/home/ctt/Devs/darknet/libdarknet.so") ", but I met the problem like this undefined reference to `load_network(char*, char*, int)

**Comment by maybepossible** [comment]
Have you solved this problem? @chengtingting
