### ISSUE TITLE
Error from "make" when enabling OpenCV 3

### ISSUE THREAD

**Issue by GuidoBartoli** [pjreddie/darknet#551]
Hi,
I'm using Linux Mint 18.3 64-bit (Ubuntu 16.04) with OpenCV 3.4.1 correctly configured and installed.
I just cloned the `darknet` repository and enabled OpenCV support in the Makefile setting `OPENCV=1`.
When issuing the `make` command, I receive this error: 

`
mkdir -p obj
mkdir -p results
gcc -Iinclude/ -Isrc/ -DOPENCV `pkg-config --cflags opencv`  -Wall -Wno-unknown-pragmas -Wfatal-errors -fPIC -Ofast -DOPENCV -c ./src/gemm.c -o obj/gemm.o
In file included from /usr/local/include/opencv2/core/types_c.h:59:0,
                 from /usr/local/include/opencv2/core/core_c.h:48,
                 from /usr/local/include/opencv2/highgui/highgui_c.h:45,
                 from include/darknet.h:25,
                 from ./src/utils.h:5,
                 from ./src/gemm.c:2:
/usr/local/include/opencv2/core/cvdef.h:485:1: error: unknown type name ‘namespace’
 namespace cv {
 ^
compilation terminated due to -Wfatal-errors.
Makefile:85: recipe for target 'obj/gemm.o' failed
make: *** [obj/gemm.o] Error 1
`

Which is strange, because `namespace cv` is used by almost every application based on OpenCV... What am I missing here? Is this OpenCV not compatible with Darknet? 

Thanks,
Best regards

**Comment by MaeThird** [comment]
C API is not supported by the opencv official in their 3.4 version. As cited here:https://github.com/opencv/opencv/pull/10941 and:https://github.com/opencv/opencv/issues/10963

**Comment by AlexeyAB** [comment]
@GuidoBartoli There is C API bug in OpenCV 3.4.1. 
Try to use OpenCV 3.4.0

**Comment by GuidoBartoli** [comment]
Yep, that works, thanks!

**Comment by beyhangl** [comment]
I'm using 3.4.0 but have this problem.
>>> import cv2
>>> cv2.__version__
'3.4.0'

**Comment by hikariakio** [comment]
Guys...sorry for question...how can i compile darknet with opencv 3.4.0 .. whenever I use brew install opencv , it gives me latest version of opencv (3.4.1)..

How can i use darknet with opencv3.4.0 in mac?

**Comment by evilmtv** [comment]
@hikariakio 
I'm not too familiar with this but try this:
https://stackoverflow.com/questions/3987683/homebrew-install-specific-version-of-formula

**Comment by Firststep2014** [comment]
@AlexeyAB 
Hello,I've used Opencv3.4.1,and my problem happens to be "error: unknown type name 'namespace'"
![image](https://user-images.githubusercontent.com/12171096/44003679-43476dfa-9e89-11e8-8caa-1bfb29dc8968.png)
Does this mean to be same question?

**Comment by PeterQuinn925** [comment]
This is the same issue. Use the recommended version of OpenCV.
