### ISSUE TITLE
Yolo v3 CFG file masks

### ISSUE THREAD

**Issue by ahsan856jalal** [pjreddie/darknet#561]
@pjreddie 
Hi
Can you please confirm that all yolo layers have mask values 0,1,2 multiple times at the end . Is it right or it should have different values in different yolo layers

**Comment by pjreddie** [comment]
oh shit sorry about that, fixed e4acba689c89e223636efe7dabe8f55ae019cd8a

**Comment by ahsan856jalal** [comment]
Thanks Mate !

**Comment by ahsan856jalal** [comment]
One last question , in yolo v2 , we have to set last convolutiona layer's filters like (classes+1+coords)*num
e.g for coords=4, num=5 and classes =1, filters will be 30. 
However, you have used filters to be 75 for classes=20 and num =9.
So what if I have 92 classes and five anchors ?

**Comment by pjreddie** [comment]
num is 9 but each yolo layer is only actually looking at 3 (that's what the mask thing does). so it's (20+1+4)*3 = 75. If you use a different number of anchors you have to figure out which layer you want to predict which anchors and the number of filters will depend on that distribution

**Comment by ahsan856jalal** [comment]
Thanks

**Comment by hexiangquan** [comment]
@pjreddie mask means just detect anchor masked ?
