### ISSUE TITLE
yolov3 Different outputs by using CPU and GPU 

### ISSUE THREAD

**Issue by lilong-epfl** [pjreddie/darknet#565]
Hi,

I am tried to run yolov3 by using the CPU only and then GPU, but the outputs are different.
<img width="436" alt="output1" src="https://user-images.githubusercontent.com/13543618/37897488-ddcf101e-3118-11e8-8a8f-068a825e91f6.png">
<img width="399" alt="output2" src="https://user-images.githubusercontent.com/13543618/37897503-e42974ea-3118-11e8-8688-a0e7ab37f24c.png">

Best

**Comment by pjreddie** [comment]
I had a messed up upsample layer on CPU and never tested it, fixed!

**Comment by shenyingying** [comment]
@pjreddie @lilong-epfl 
have you solved the problem?

**Comment by 0801130205** [comment]
@pjreddie cpu and gpu outputs is still not  strictly same.
