### ISSUE TITLE
Getting an error while using yolov3.cfg along with yolov3.weights on windws

### ISSUE THREAD

**Issue by visin** [pjreddie/darknet#571]
**Parsing .cfg/yolov3.cfg**
**Layer [shortcut] not implemented**

**Comment by Alexyuda** [comment]
do you have a solution to this problem?

**Comment by visin** [comment]
Nope. But i guess this issue is more suited to the darkflow repo (which i used to run earlier versions of YOLO) instead of this one so closed it.
