### ISSUE TITLE
filters=255 in the last convolutional layer before detection layer in yolov3.cfg

### ISSUE THREAD

**Issue by YL-123** [pjreddie/darknet#580]
Thanks for the amazing project! I just wondering how to calculate the filters number in the last convolutional layer before yolo detection layer in yolov3.cfg. Is it different from the YOLO V2? since num=9, then filters = num*(bounding box offsets+objectness prediction+class predictions) = 9*(4+1+80)=765, but the filters=255 in the yolov3.cfg? thanks

**Comment by ahsan856jalal** [comment]
now num= num/3 as anchors are being divided into three layers.
so 3*(4+1+80)

**Comment by Vmaxx-yinling** [comment]
Yes, I see in the paper, "we predict 3 boxes at each scale", the num is the number of boxes at each scale rather than the total number.

**Comment by ndg123** [comment]
Its probably more correct to refer to it as (num anchors in the mask)*(classes*5).  Since you don't necessarily have to have 3 anchors in every layer.
