### ISSUE TITLE
Anchors in tiny yolo for coco seem quite wrong

### ISSUE THREAD

**Issue by agirbau** [pjreddie/darknet#588]
Hello! I think the anchors in the file yolov2-tiny.cfg are a little bit off:
https://github.com/pjreddie/darknet/blob/6f6e4754ba99e42ea0870eb6ec878e48a9f7e7ae/cfg/yolov2-tiny.cfg#L123
Following yolov2.cfg (as they're both in coco and the number of maxpoolings is the same) they should be:
https://github.com/pjreddie/darknet/blob/6f6e4754ba99e42ea0870eb6ec878e48a9f7e7ae/cfg/yolov2.cfg#L242
right?

**Comment by ahsan856jalal** [comment]
in yolov3 anchors are the original pixel values, in yolov2 , values were divided by 32
