### ISSUE TITLE
How to save  weights between 1000 and 2000

### ISSUE THREAD

**Issue by jobim3d** [pjreddie/darknet#593]
Hi, YOLO saves weights by steps of 100 until 900 and of 1000 after 1000.
How can I save, for example, weights of 1400?
Thanks!

**Comment by ahsan856jalal** [comment]
Goto detector.c and search for 10000, you can change it 100 so that it saves weights on multiples of 1000

**Comment by jobim3d** [comment]
Done, thanks!
