### ISSUE TITLE
Demo needs OpenCV for webcam images.

### ISSUE THREAD

**Issue by ccs1605** [pjreddie/darknet#594]
i googled it and searched stackoverflow, and i am unable to find any solutions.

hope to hear you suggestions! 
![demo](https://user-images.githubusercontent.com/23208578/38086397-bf48fb6c-3386-11e8-8a0c-7f93d88646d4.png)

**Comment by RushNuts** [comment]
Hi. You should opencv =1 in makefile, and make again

**Comment by ccs1605** [comment]
much appreciate, i follow the readme but didnt see make it again!
it works like charm.

**Comment by namtran0110** [comment]
sorry, what do you mean by "You should opencv =1 in makefile, and make again"? what's the command line should I run here?

**Comment by AlexeyAB** [comment]
@namtran0110 You should edit this line in the `Makefile` file: https://github.com/AlexeyAB/darknet/blob/2c5e383c04655fe45f3f533eb3a69a80acbf3561/Makefile#L4

And then just run command:
`make`

**Comment by Bernardo2282** [comment]
![deepin_screenshot](https://user-images.githubusercontent.com/32619766/48522978-b3c05c00-e861-11e8-9314-0648dabc76fa.png)
I edit the line in the Makefile, but when i run make commando i get this error, and de darknet file is delted, someone help  me !!!!

**Comment by CallMeKanG** [comment]
![image](https://user-images.githubusercontent.com/39833163/48833246-ea442c80-edb5-11e8-9647-2eaabb2732e6.png)
same with @Bernardo2282  I edit the line(OPENCV=1) in the Makefile and get different error

**Comment by Xaoc000** [comment]
Same as above two, would love some more insight into this

**Comment by dcguru2016** [comment]
Hi,
I am going through the opencv installation for darknet and running into an issue. I spent few hours troubleshooting this to the point that i exhausted all my resources. please help.

*************************************************************************************************
ubuntu@ubuntu-ThinkPad-X1-Carbon:~/darknet$ make
g++ -Iinclude/ -Isrc/ -DOPENCV `pkg-config --cflags opencv`  -Wall -Wno-unused-result -Wno-unknown-pragmas -Wfatal-errors -fPIC -Ofast -DOPENCV -c ./src/image_opencv.cpp -o obj/image_opencv.o
Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found
./src/image_opencv.cpp:5:10: fatal error: opencv2/opencv.hpp: No such file or directory
 #include "opencv2/opencv.hpp"
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:86: recipe for target 'obj/image_opencv.o' failed
make: *** [obj/image_opencv.o] Error 1
ubuntu@ubuntu-ThinkPad-X1-Carbon:~/darknet$ python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> cv2.__version__
'4.0.0'
>>> quit()
ubuntu@ubuntu-ThinkPad-X1-Carbon:~/darknet$ 
****************************************************************

**Comment by yustiks** [comment]
I have got error when I changed opencv=1 and then run make command. 
"No package 'opencv' found
./src/image_opencv.cpp:15:36: fatal error: opencv2/core/version.hpp: No such file or directory
 #include <opencv2/core/version.hpp>"

**Comment by sonbkpro** [comment]
I encountered the  same error. Please give me a solution on this error. I'm so thanks you.

**Comment by ibrandiay** [comment]
je rencontre la meme dificulté avec yolov3

**Comment by MaheswariR450** [comment]
@VanessaMachi... Have you found the solution? please help me with this...I have same issue

**Comment by camillegroult** [comment]
> make

GPU=0
CUDNN=0
OPENCV=1
OPENMP=0
DEBUG=0

./darknet detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights dubai.mp4
Demo needs OpenCV for webcam images.
 still not working for me

**Comment by anthonyweiss** [comment]
> I have got error when I changed opencv=1 and then run make command.
> "No package 'opencv' found
> ./src/image_opencv.cpp:15:36: fatal error: opencv2/core/version.hpp: No such file or directory
> #include <opencv2/core/version.hpp>"
> **UPDATE:**
> Solved the problem by correctly installed opencv. It seems that the ubuntu community has completed the documentation on installing openCV, all you have to do now is to download the installation script from https://github.com/jayrambhia/Install-OpenCV/blob/master/Ubuntu/opencv_latest.sh and execute it.

When I make a .sh script and paste the code in and try to run it via "./opencv_latest.sh", it says:

"./opencv_latest.sh: line 2: ./../get_latest_version_download_file.sh: No such file or directory"

**Comment by agoineee** [comment]
I got the same error  
./darknet detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights data/no4.mp4
and show me 
Demo needs OpenCV for webcam images.
I running yoloV3 on terminal, can some one help me ,ty!

**Comment by sanazkhalili** [comment]
> Hi. You should opencv =1 in makefile, and make again

It works for me. Thanks.

**Comment by mehdico** [comment]
I've got this error on Mac:

```bash
gcc -Iinclude/ -Isrc/ -DOPENCV `pkg-config --cflags opencv`  -Wall -Wno-unused-result -Wno-unknown-pragmas -Wfatal-errors -fPIC -Ofast -DOPENCV -c ./src/gemm.c -o obj/gemm.o
Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found
```

installing opencv using homebrew won't help.
