### ISSUE TITLE
the labels of detect image still shows "person, bicycle" of voc, not my labels, why?

### ISSUE THREAD

**Issue by zzks** [pjreddie/darknet#628]
i trained a yolo v3 model by my dataset.
i changed .data, .names, and related cfg files.
the training is successful, but when i detect image by "darknet detect cfg/yolov3-obj.cfg backup/yolov3-obj.weights image.jpg"
the objects are detected successful, but the labels shows "person, bicycle" which are voc labels.
why my labels did not show? i changed the obj.names obj.data file into my setting.

**Comment by ahsan856jalal** [comment]
use 
`./darknet detector test your_own.data cfg/yolov3-obj.cfg backup/yolov3-obj.weights image.jpg`
