### ISSUE TITLE
Weight and 'cfg' files from home page may be identical.

### ISSUE THREAD

**Issue by apiszcz** [pjreddie/darknet#633]
md5sum
c84e5b99d0e52cd466ae710cadf6d84c *yolov3-320.weights
c84e5b99d0e52cd466ae710cadf6d84c *yolov3-416.weights
c84e5b99d0e52cd466ae710cadf6d84c *yolov3-608.weights

**Comment by pjreddie** [comment]
they are all the same. if you want to use it at a higher resolution just change the cfg file width and height fields
