### ISSUE TITLE
Compile error: ‘memcpy’ was not declared in this scope

### ISSUE THREAD

**Issue by kthordarson** [pjreddie/darknet#638]
I get this error message while compiling:

nvcc  -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=[sm_50,compute_50] -gencode arch=compute_52,code=[sm_52,compute_52] -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  --compiler-options "-Wall -Wno-unused-result -Wno-unknown-pragmas -Wfatal-errors -fPIC -Ofast -DGPU -DCUDNN" -c ./src/convolutional_kernels.cu -o obj/convolutional_kernels.o
/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
compilation terminated due to -Wfatal-errors.
Makefile:88: recipe for target 'obj/convolutional_kernels.o' failed
make: *** [obj/convolutional_kernels.o] Error 1

**Comment by Kenhouse** [comment]
I get this issue, too.

**Comment by Amerry-c** [comment]
hi,I also met this problem, did you solve it?

**Comment by Amerry-c** [comment]
i sloved it reference to https://github.com/pjreddie/darknet/issues/200 @Kenhouse @kthordarson

**Comment by Kenhouse** [comment]
Hi, I already solved it.
I edit the Makefile to

ifeq ($(GPU), 1)
COMMON+= -DGPU -I/usr/local/cuda/include/
CFLAGS+= -DGPU *-D_FORCE_INLINES*
LDFLAGS+= -L/usr/local/cuda/lib64 -lcuda -lcudart -lcublas -lcurand
endif

It's base on some workaround solution....
like  https://github.com/BVLC/caffe/issues/4046




2018-04-13 14:25 GMT+08:00 Amerry-c <notifications@github.com>:
