### ISSUE TITLE
Yolov2 Training Outputts : All NaN (not a number)

### ISSUE THREAD

**Issue by ZacharyForrest** [pjreddie/darknet#660]
Hey,

So trying to get a YOLOv2 network to recognise vehicles from satellite photography (using this dataset https://github.com/nikitalpopov/vedai)

I arbitrarily used the yolov2-voc.cfg file (adjusted for my 12 classes and weak graphics card( ie batch 1, sub divisions 1) and yolov2-cov.weights, and it seemed to be training okay until around the 600th iteration, when suddenly all the training output was NaN

Just retried starting completely from scratch weight-wise, and now its got to around 900 before blanking to NaN

Loss normally skyrockets just before it blanks, like this:

```
Region Avg IOU: 0.000000, Class: 0.000000, Obj: 0.000000, No Obj: 0.004019, Avg Recall: 0.000000,  count: 1
931: 86426484736.000000, 8648297472.000000 avg, 0.000751 rate, 0.089617 seconds, 931 images
Loaded: 0.000031 seconds
Region Avg IOU: 0.000000, Class: 0.000000, Obj: 0.800000, No Obj: 0.784000, Avg Recall: 0.000000,  count: 5
932: 488075076341487108096.000000, 48807505874930106368.000000 avg, 0.000755 rate, 0.272508 seconds, 932 images
Loaded: 0.000040 seconds
Region Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 1.000000, Avg Recall: -nan,  count: 0
933: inf, inf avg, 0.000758 rate, 0.270606 seconds, 933 images


```

Any thoughts? Thanks for your time

**Comment by ZacharyForrest** [comment]
Changed the .cfg to use small batches instead, and now seems to work...!

**Comment by kribby** [comment]
Hi @ZacharyForrest 
Did you change the batches or max batches parameter in the cfg? What were these variables set to before and what were they when your model stopped outputting Nan? 

Cheers
