### ISSUE TITLE
Question Yolo v1

### ISSUE THREAD

**Issue by Shiro-LK** [pjreddie/darknet#666]
Hello, I read the YOLOv1's paper but I have still some questions (regarding more the "details" of implementation).

I understand the fact that in YOLO, we divide the image per cell (7x7) and we predict a fixed number of bounding boxes (2 by default in the paper, with 4 coordinates : x, y , w, h), a confidence score and we predict also classes score for each cell. During the testing step, we can use NMS algorithm so as to remove multiples detections of an object. 

1) When did we divide the image into a grid ? In fact, when I read the paper they mentionned to divide the image, but when I look at the architecture of the network it seems that we have two part : the convolutional layers and the FC layers. Does that mean the network do it "naturally" with the bounding boxes output ? The size of the grid 7x7 is it specific to the convolution part use it the paper ? If we use for example VGG does it change the size of the grid ?

2) Why do we use 2 bounding boxes per cell ? Is it in the case we have 2 objects in a cell ? In the case, we have 0 object, which label value will it return ? Moreover, if we have 2 different objects in a cell, how can we choose the object class P class|object ? Do we have to increase the grid cell size ?

3) each bounding box is associated to a cell, so how does it manage to detect an object which is bigger than one cell ?

I thank you for the help !

**Comment by LJXLJXLJX** [comment]
"You look only once"
Obviously ,in yolo v1,there is no division  at all. 
You divide the image only when you make labels(S * S * ( B * 5 + C) dims)  for the dataset.
When you use the trained net , feed a image, the output tensor will reflects division information.

As for the 2 bounding boxes,I guess one of them is standing (h>w) ,another is lying(w>h), maybe two bounding box with different shape regress better than only one.

**Comment by Shiro-LK** [comment]
@LJXLJXLJX  Thank for the answer that seems clearer !
I was wondering, does that mean with yolo v1, we can predict at least 7x7=49 objects in an image ? Moreover, in the paper, it said that a predictor is associated to a class object. In the case that we have 2 predictors and 20 classes, I suppose that one predictor per cell is specialized on 10 classes ?

**Comment by LJXLJXLJX** [comment]
> Our system divides the input image into an S × S grid.
If the center of an object falls into a grid cell, that grid cell
is responsible for detecting that object.
Each grid cell predicts B bounding boxes and confidence
scores for those boxes

I don't understand what the predictors mean that you said.
You should focus on the output tensor.
It's with S * S * ( B * 5 + C) dims , S*S means the number of the grids you divide on the train data image. And (B*5+C) means the information of each gird. B is the number of bounding boxes , for each bounding box there are 5 features ,they are x,y,w,h and p.  C is the number of classes.
If you can understand Chinese , you can refer to this blog [https://blog.csdn.net/hrsstudy/article/details/70305791](url)

**Comment by Shiro-LK** [comment]
@LJXLJXLJX  

> YOLO predicts multiple bounding boxes per grid cell.
At training time we only want one bounding box predictor
to be responsible for each object.  We assign one predictor
to be “responsible” for predicting an object based on which
prediction  has  the  highest  current  IOU  with  the  ground
truth. This leads to specialization between the bounding box
predictors.  Each predictor gets better at predicting certain
sizes, aspect ratios, or classes of object, improving overall
recall.

I was talking about that (It is about the training part in the paper)

**Comment by LJXLJXLJX** [comment]
@Shiro-LK 
The author did not describe it in detail here, but I can make sure each predictor will predict C class instead of C/2, I guess the two bounding boxes have different constrains and they are designed for different shapes , one for standing objects and the other for lying objects.Only one box may not be easy to regress.

**Comment by Shiro-LK** [comment]
@LJXLJXLJX  I see, that seems in fact weird if it predicts C/2 class.  Thanks !

**Comment by igo312** [comment]
@LJXLJXLJX  Like @Shiro-LK said

>  we can predict at least 7x7=49 objects in an image 
But I think YOLOv1 can only find 49 obejects at most. Am I right?

**Comment by robertlugg** [comment]
Here is my understanding:

> When did we divide the image into a grid ? In fact, when I read the paper they mentioned to divide the image, but when I look at the architecture of the network it seems that we have two part : the convolutional layers and the FC layers. Does that mean the network do it "naturally" with the bounding boxes output ? The size of the grid 7x7 is it specific to the convolution part use it the paper ? If we use for example VGG does it change the size of the grid ?
No actual division is performed.  The network operates on the entire image and mostly has no understanding of this grid.  Theoretically, I believe the grid is unnecessary.  But practically I believe it is required.  I *believe* that grid size should be based on the object size.  In newer YOLOv3, it seems they use three different grids to handle multiple scales.

> Why do we use 2 bounding boxes per cell ? Is it in the case we have 2 objects in a cell ? In the case, we have 0 object, which label value will it return ? Moreover, if we have 2 different objects in a cell, how can we choose the object class P class|object ? Do we have to increase the grid cell size ?
Two BB's mean that the network can find two objects within any grid.  This could be two instances of the same object type or two different object types.  NOTE: "in" means the center of the object is inside grid; the object may extend to many grid cells, but only one has the center of the object in it.

> each bounding box is associated to a cell, so how does it manage to detect an object which is bigger than one cell ?
The network "sees" the entire image.  Objects can be bigger than a cell, but they are defined as "in" that grid cell if their centerpoint is in the cell.

I hope this helps.  I am also new to this network.

**Comment by SMS786** [comment]
For anyone reading this please note that Yolo v1 can detect or rather allows for only one class per grid. This is listed in the _Limitations of YOLO_ section in the original paper : [https://arxiv.org/pdf/1506.02640.pdf](url)
