### ISSUE TITLE
How to change the threshold of command 'detector valid' when I calculate mAP?

### ISSUE THREAD

**Issue by fxs628** [pjreddie/darknet#678]
Hi,
       when I use the command : 
 **./darknet detector valid cfg/voc.data  cfg/yolov3.cfg  backup/yolov3_40000.weights**
 I got some .txt files in 'results' folder. However, the contents in these .txt files seem that the valid threshold is 0.0.
Then I add the threshold optional in the command just like the home page did:
**./darknet detector valid cfg/voc.data  cfg/yolov3.cfg  backup/yolov3_40000.weights -thresh 0.5**
and this didn't work.
What should I do if I want to set valid threshold as 0.5?
Appreciate any help!

**Comment by ZhongyuanW** [comment]
did you solve it ? I meet the some problem...

**Comment by Emirismail** [comment]
Try to use
-iou_thresh 0.5 instead of -thresh 0.5
actually -thresh is the threshold of detection. It only affects the IoU, F1, P/R

**Comment by mohammedFnesh** [comment]
you can try 
-thresh yourValueHere
