### ISSUE TITLE
How to get number of predictions in the predicted image of yolo? 

### ISSUE THREAD

**Issue by KushajveerSingh** [pjreddie/darknet#682]
After having searched for the last 2 hours I have failed to find a method that meets my needs. So, darknet just outputs the prediction image. But what I want for my project are the number of bounding boxes in the image. For example if the image has 3 cars in it and 2 person than I want a file in any format text or jason that has this information as I have to use this information to make further inferences.
Also if you your method involves using some dependencies please provide a way of adding them to a docker image. My current docker container would run on ubuntu 16.04 and the base image for the image is python 3.6.5

**Comment by sandeeprepakula** [comment]
Refer the python script at  https://github.com/pjreddie/darknet/blob/master/examples/detector.py and modify this according to your need of writing output (inputfile, label, bbox) into a file and do required operations as per your requirement to count n1 cars, n2 persons, etc
