### ISSUE TITLE
CUDA Error: invalid device function

### ISSUE THREAD

**Issue by radislav72** [pjreddie/darknet#686]
I succesfully build darknet&yolo and test it for object detection in video. Without GPU test example work fine, but very slovly. But when I try to use GPU (NVIDIA GeForce GT 630M, 2GB) I have error:
CUDA Error: invalid device function
CUDA Error: invalid device function: No error

Maybe somebody have ideas how to fix it?

**Comment by radislav72** [comment]
It was incorrect architecture name of GPU: I change compute_50,sm_50 to compute_20,sm_20 and all work fine.

**Comment by sharoseali** [comment]
radislav72    where does i can change  arc please reply

**Comment by radislav72** [comment]
Hi! You can change it in project properties.

**Comment by sharoseali** [comment]
thanks radislav72   ....for replying... but where i got my correct GPU architecture name.??

**Comment by Lrakulka** [comment]
Hi, sharoseali. You can find it [here](https://en.wikipedia.org/wiki/CUDA) table GPUs supported, Column "Compute capability".
In Makefile you can find property ARCH= it contains configuration for gpu architectures.
arch=compute_20,code=[sm_20,sm_21] means make build for GPU with capability 2.0 or 2.1
