### ISSUE TITLE
compile failure with OPENCV=1

### ISSUE THREAD

**Issue by aimhabo** [pjreddie/darknet#717]
1、
 unknown type name ‘namespace’
：
 CC=g++#gcc

2、
invalid conversion from ‘A’ to ‘B' [-fpermissive] 
：
` (B)A(..., ..., ...);` for all arrays

3、
./src/cuda.c: In function ‘dim3 cuda_gridsize(size_t)’:
./src/cuda.c:59:22: error: in C++98 ‘d’ must be initialized by constructor, not by ‘{...}’
     dim3 d = {x, y, 1};
：
`dim3 d(x,y,1);//dim3 d = {x, y, 1};`
and` A a;//= {0};` for all structs

4、
./src/image.c: In function ‘void draw_detections(image, detection*, int, float, char**, image**, int)’:
./src/image.c:245:9: error: expected primary-expression before ‘int’
         int class = -1;
：
 awesome `class`, `new`, ...etc

5、
./src/image.c:538:47: error: ‘IplImage’ has not been declared
 void show_image_cv(image p, const char *name, IplImage *disp)
：
in darknet.h
changeTo
```
#ifdef __cplusplus
extern "C" {
#endif
    #ifdef OPENCV
    #include "opencv2/highgui/highgui_c.h"
    #include "opencv2/imgproc/imgproc_c.h"
    #include "opencv2/core/version.hpp"
    #if CV_MAJOR_VERSION == 3
    #include "opencv2/opencv.hpp"
    #include "opencv2/videoio/videoio_c.h"
    #include "opencv2/imgcodecs/imgcodecs_c.h"
    #endif
    #endif
...
...
...
#ifdef __cplusplus
}
#endif
```

6、
./src/demo.c: In function ‘void* fetch_in_thread(void*)’:
./src/demo.c:144:62: error: ‘fill_image_from_stream’ was not declared in this scope
     int status = fill_image_from_stream(cap, buff[buff_index]);
：
in image.h
changeTo
```
#ifdef __cplusplus
extern "C" {
#endif
#ifdef OPENCV
int fill_image_from_stream(CvCapture *cap, image im);
image ipl_to_image(IplImage* src);
void ipl_into_image(IplImage* src, image im);
void flush_stream_buffer(CvCapture *cap, int n);
void show_image_cv(image p, const char *name, IplImage *disp);
#endif
...
...
...
#ifdef __cplusplus
}
#endif
```

my g++version is 4.8.4, is it too low? but many course says that donot use cuda with high level g++. It's annoying...

warning list is annoying too

**Comment by aimhabo** [comment]
opencv 3.4.0 √

**Comment by drforester** [comment]
Why do you want to build Darknet with g++ instead of gcc?
The following link shows modifications I made to the Makefile to find my OpenCV 3.4.0 install and then build Darknet using gcc 6.4.0 on Ubuntu: https://github.com/drforester/Custom_YOLOv3_Detectors#build-opencv-wherever-you-want-it
Just replace my paths with your own.

**Comment by Kxuan** [comment]
same issue

**Comment by corentin87** [comment]
I am having trouble to compile/link as well because i'm using C++ to create some python biddings with boost. Any idea why this #ifndef __cplusplus was adding? it doesn't make send to me

**Comment by aimhabo** [comment]
@corentin87 This is to avoid "loading cpp sentence when gcc is compiled"
