### ISSUE TITLE
Couldn't open file: data/cifar/labels.txt

### ISSUE THREAD

**Issue by 123liluky** [pjreddie/darknet#729]
I am trying Train a Classifier on CIFAR-10, https://pjreddie.com/darknet/train-cifar/. I do the steps one by one, while I conduct: ./darknet classifier train cfg/cifar.data cfg/cifar_small.cfg, Error is Couldn't open file: data/cifar/labels.txt. But I can find the file in folder.

**Comment by cowry5** [comment]
me too!!! have you solve it??? please tell me , thank u !~!~!

**Comment by andeyeluguo** [comment]
I have the same problem. I donot know why.

**Comment by Nico1ee1995** [comment]
Me too!
Can anyone help me?
