### ISSUE TITLE
Training on Tesla V100 with CUDA 9, it stopped without any error......

### ISSUE THREAD

**Issue by wangzhe0623** [pjreddie/darknet#733]
Hi, @pjreddie
    Thx for your great job~ 
    I trained the model with yolo_v2 on Tesla V100, the session stoped when "Resizing "320". I am sure that there's nothing wrong with training data, cfg file and weights. And I used yolo_v3 instead, the same thing happened again when "Resizing XX", "XX" can be any value. But, when I turned to another machine with 1080 Ti, everything is OK. So I think darknet may not support Tesla v100, is that right?
     Many many thx~~~

**Comment by keineahnung2345** [comment]
@wangzhe0623 Have you found the reason behind this issue?
