### ISSUE TITLE
Video rendering error.

### ISSUE THREAD

**Issue by Michi-123** [pjreddie/darknet#734]
I ran command below,
$ ./darknet detector demo cfg/coco.data cfg/yolo.cfg yolo.weights ../Videos/outside-0001.mov

And I got error message like this
Loading weights from yolo.weights...Done!
video file: ../Videos/outside-0001.mov
Couldn't connect to webcam.
: Cannot allocate memory
darknet: ./src/utils.c:193: error: Assertion `0' failed.

1 year ago, the command worked correctly. Is this really caused by out of memory?

**Comment by Pattorio** [comment]
You should set batch=1, subdivisions=1 in your cfg file.

**Comment by xzessmedia** [comment]
> You should set batch=1, subdivisions=1 in your cfg file.

Result:
87 Layer before convolutional layer must output image.: Success
darknet: ./src/utils.c:256: error: Assertion `0' failed.

**Comment by Michi-123** [comment]
Thanks 4 everyone!

**Comment by Michi-123** [comment]
Attention! 
I found Darknet updates without notice.  The newest one has input layer with  over 500 x 500 images.
