### ISSUE TITLE
YOLO suppress bounding boxes

### ISSUE THREAD

**Issue by Rui96** [pjreddie/darknet#759]
Hi, I'm trying to use pre-trained YOLO model to detect cars. I'm reading video from web browser as my input, and using ./darknet detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights <web-browser-address>. However, since I'm interested in detecting only one object, is it possible to suppress the bounding boxes for other classes and only display for cars? 
I appreciate for your help!

**Comment by Flock1** [comment]
You can. I did this sometime back and in `image.c`, there is a function called `draw_detections`. There, set a condition that for `names[j]` in line 255 that it should be equal to car. I think that'll work. Exactly what's the condition I can tell you in a few hours.

**Comment by Rui96** [comment]
@Flock1 Thank you so much for the help! I managed to suppress other displays by modifying the draw_detections function.

**Comment by DennisFaucher** [comment]
@zengrj would you mind sharing your modified image.c? Thank you.
Flock1ock1 Thank you so much for the help! I managed to suppress other displays by modifying the draw_detections function.
