### ISSUE TITLE
Training with own dataset

### ISSUE THREAD

**Issue by rehmanzafar** [pjreddie/darknet#771]
Hello,
I have trained the darknet with my own dataset using the following command "./darknet detector train cfg/voc.data cfg/yolov2-voc.cfg darknet53.conv.74". Our dataset has 5 classes so in **"cfg/yolov2-voc.cfg"**  I have changed the filter size to 50 at line 237 using the following formula "filters=(classes + 5)*5".  After successful training, it is not displaying predictions probabilities and prediction boxes on the test image. I am using the following command "./darknet detector test cfg/voc.data cfg/yolov2-voc.cfg darknet53.conv.74 data/2006_1.jpg" to test the image. Can you please help me out to fix this? 
Any help would be appreciated !!
Thank you.

**Comment by AlexeyAB** [comment]
Hi,
* Did you change `classes=5` in your cfg-file?

* For detection use:
`/darknet detector test cfg/voc.data cfg/yolov2-voc.cfg backup/yolov2-voc_4000.weights data/2006_1.jpg`

* For training yolo v2 use this weights file http://pjreddie.com/media/files/darknet19_448.conv.23
     and as said here: https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects

> (to train old Yolo v2 **yolov2-voc.cfg**, yolov2-tiny-voc.cfg, yolo-voc.cfg, yolo-voc.2.0.cfg, ... [click by the link](https://github.com/AlexeyAB/darknet/tree/47c7af1cea5bbdedf1184963355e6418cb8b1b4f#how-to-train-pascal-voc-data))

**Comment by rehmanzafar** [comment]
Thank you Alexey for you response.

- yes  I had changed the classes = 5 
- It didn't created backup, is it mandatory?
- I was using the following weights, definetly, I will try these weights too http://pjreddie.com/media/files/darknet19_448.conv.23

**Comment by rehmanzafar** [comment]
> How many iterations did you train?
![image](https://user-images.githubusercontent.com/6893939/39875102-9c3394de-543d-11e8-849f-51bfeaa31990.png)

It trained for 100 iteration, and after that it stopped. Please see the attached image for reference.

**Comment by AlexeyAB** [comment]
* What repository do you use?
    These both repositories will output `Saving weights to /backup/yolov2-voc_100.weights` instead of  `Saving weights to /backup/yolov2-voc.backup` 

    1. https://github.com/pjreddie/darknet/blob/f6d861736038da22c9eb0739dca84003c5a5e275/examples/detector.c#L143
    2. https://github.com/AlexeyAB/darknet/blob/cda8171feb76bcb405350fd8341d42a0300e2f4b/src/detector.c#L195

Remove your code, download and compile Darknet again.

----

* Do you have directory `/backup` in the darknet-folder?
* Do you have permission to write files to this folder?
or try to train using 
`sudo ./darknet detector train cfg/voc.data cfg/yolov2-voc.cfg darknet53.conv.74`

**Comment by rehmanzafar** [comment]
> What repository do you use?
I am using the following repository: https://github.com/pjreddie/darknet

> Do you have directory /backup in the darknet-folder?
I got it, by default darknet repository does not contain "backup" directory and it is not creating at runtime. Now I have created it manually.

I am training it again by considering your suggestions. 
Thank you.

**Comment by rehmanzafar** [comment]
Thank you AlexeyAB for your help, it worked.

**Comment by srhtyldz** [comment]
> * What repository do you use?
>   These both repositories will output `Saving weights to /backup/yolov2-voc_100.weights` instead of  `Saving weights to /backup/yolov2-voc.backup`
>   
>   1. [darknet/examples/detector.c](https://github.com/pjreddie/darknet/blob/f6d861736038da22c9eb0739dca84003c5a5e275/examples/detector.c#L143)
>          
>          
>               Line 143
>            in
>            [f6d8617](/pjreddie/darknet/commit/f6d861736038da22c9eb0739dca84003c5a5e275)
>          
>          
>          
>          
>      
>              
>                
>                 sprintf(buff, "%s/%s_%d.weights", backup_directory, base, i);
>   2. https://github.com/AlexeyAB/darknet/blob/cda8171feb76bcb405350fd8341d42a0300e2f4b/src/detector.c#L195
> 
> Remove your code, download and compile Darknet again.
> 
> * Do you have directory `/backup` in the darknet-folder?
> * Do you have permission to write files to this folder?
>   or try to train using
>   `sudo ./darknet detector train cfg/voc.data cfg/yolov2-voc.cfg darknet53.conv.74`

How could I modify the code if I want to save in every 100 iteration until 30k iterations ?

**Comment by adriacabeza** [comment]
@srhtyldz by checking the detector.c code inside the examples folder and changing this part of the code:
```c
      if(i%10000==0 || (i < 1000 && i%100 == 0)){
#ifdef GPU
            if(ngpus != 1) sync_nets(nets, ngpus, 0);
#endif
            char buff[256];
            sprintf(buff, "%s/%s_%d.weights", backup_directory, base, i);
            save_weights(net, buff);
        }
```
to:
```c
      if(i%10000==0 || (i < 30000 && i%100 == 0)){
#ifdef GPU
            if(ngpus != 1) sync_nets(nets, ngpus, 0);
#endif
            char buff[256];
            sprintf(buff, "%s/%s_%d.weights", backup_directory, base, i);
            save_weights(net, buff);
        }
```
Please notice that with this change you will save every 100 until 30000 and after that saving every 10000 iterations. Also remember to make the project again.
