### ISSUE TITLE
Trained model on custom data is not predicting the objects correctly.

### ISSUE THREAD

**Issue by rehmanzafar** [pjreddie/darknet#779]
Hi,
I have trained YOLO on our custom dataset. In our dataset each image has 5 objects (5 classes). I am using yolov3-voc.cfg configuration file for training model. I have made a slight change at line 773 to modify the size of filter using the following formula "filters = 1 x 1 x (N x (5 + C) )" where N=3 and C=5. Also I have changed the classes = 5 at line 779. Furthermore, I have used the following weights to train the model "darknet53.conv.74". After successful training the model is predicting 25 objects instead of 5 objects. Can anyone help me to resolve this issue?
Any help would be appreciated !!
Thank you.

**Comment by bdotgradb** [comment]
@mf27 From https://github.com/pjreddie/darknet/blob/61c9d02ec461e30d55762ec7669d6a1d3c356fb2/examples/darknet.c#L437 you can see the data file where the name file is specified is hardcoded to be the coco one. If you change the names file referenced in the cfg/coco.data to point to your name file then the class names will be correct.

**Comment by S26825** [comment]
I have the same issue. I trained my custom dataset on yolov3 but it does not work on the images for prediction. Please help me.
