### ISSUE TITLE
How to feed OpenCV frame  to darknet python for detection in yolov3 ?

### ISSUE THREAD

**Issue by khiemntu** [pjreddie/darknet#792]
I read in darknet.py and maybe right now it only input image path to detect function. Anyone know the way input image read from cv2.imread() and put it into detection function in yolov3 ?

**Comment by TheMikeyR** [comment]
https://github.com/pjreddie/darknet/issues/739#issuecomment-388628792

**Comment by khiemntu** [comment]
thank you so much @TheMikeyR

**Comment by lakshpvt** [comment]
@khiemntu i used the functions he provided but i ran into this error : 

(python:5956): Gtk-ERROR **: GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported
Trace/breakpoint trap (core dumped)

Could y help??
