### ISSUE TITLE
YOLO v2/v3 loss function changes

### ISSUE THREAD

**Issue by ksanjeevan** [pjreddie/darknet#807]
The loss function in the original paper is defined as:
<img width="443" alt="screen shot 2018-05-20 at 4 36 42 pm" src="https://user-images.githubusercontent.com/12011058/40285033-0ea541c8-5c4c-11e8-9f43-ca9ea3ad5388.png">

I've seen comments talking about how it's implemented differently / changed in darknet for v2 and v3, does someone have the mathematical formula for either / both?

**Comment by hahazhky** [comment]
According to source code, The loss function in YOLOv3 seems to be

> `<a href="http://www.codecogs.com/eqnedit.php?latex=\sum_{i=0}^{S^{2}}\sum_{j=0}^{B}\mathbb{I}_{ij}^{obj}[(t_{x}&space;-&space;\hat{{t_{x}}})^{2}&plus;(t_{y}&space;-&space;\hat{{t_{y}}})^{2}&plus;(t_{w}&space;-&space;\hat{{t_{w}}})^{2}&plus;(t_{h}&space;-&space;\hat{{t_{h}}})^{2}&space;&plus;&space;(1&space;-&space;\hat{C_{i}})^{2}&space;&plus;&space;\sum_{c\epsilon&space;Classes}(p_{i}(c)-\hat{p_{i}}(c))^{2&space;}&space;]&plus;\sum_{i=0}^{S^{2}}\sum_{j=0}^{B}\mathbb{I}_{ij}^{noobj}(0&space;-&space;\hat{C_{i}})^{2}" target="_blank"><img src="http://latex.codecogs.com/gif.latex?\sum_{i=0}^{S^{2}}\sum_{j=0}^{B}\mathbb{I}_{ij}^{obj}[(t_{x}&space;-&space;\hat{{t_{x}}})^{2}&plus;(t_{y}&space;-&space;\hat{{t_{y}}})^{2}&plus;(t_{w}&space;-&space;\hat{{t_{w}}})^{2}&plus;(t_{h}&space;-&space;\hat{{t_{h}}})^{2}&space;&plus;&space;(1&space;-&space;\hat{C_{i}})^{2}&space;&plus;&space;\sum_{c\epsilon&space;Classes}(p_{i}(c)-\hat{p_{i}}(c))^{2&space;}&space;]&plus;\sum_{i=0}^{S^{2}}\sum_{j=0}^{B}\mathbb{I}_{ij}^{noobj}(0&space;-&space;\hat{C_{i}})^{2}" title="\sum_{i=0}^{S^{2}}\sum_{j=0}^{B}\mathbb{I}_{ij}^{obj}[(t_{x} - \hat{{t_{x}}})^{2}+(t_{y} - \hat{{t_{y}}})^{2}+(t_{w} - \hat{{t_{w}}})^{2}+(t_{h} - \hat{{t_{h}}})^{2} + (1 - \hat{C_{i}})^{2} + \sum_{c\epsilon Classes}(p_{i}(c)-\hat{p_{i}}(c))^{2 } ]+\sum_{i=0}^{S^{2}}\sum_{j=0}^{B}\mathbb{I}_{ij}^{noobj}(0 - \hat{C_{i}})^{2}" /></a>`

**Comment by XiaXuehai** [comment]
see[ this page](https://groups.google.com/forum/#!topic/darknet/TJ4dN9R4iJk)

**Comment by JeffersonQin** [comment]
@XiaXuehai Hi, after I open the link, it told me that I don't have access to the page. Any updates?
