### ISSUE TITLE
How to access class labels after validation ?

### ISSUE THREAD

**Issue by mahirjain25** [pjreddie/darknet#816]
After running
./darknet detector valid data/obj.data cfg/yolo-obj.cfg backup/yolo-obj_xxxx.weights
I am able to produce a file in results/
However, this file only mentions the output in a format like:
test 0.346370 177.854523 495.760406 238.847595 560.996094, with no indication of the class label identified.
How do I obtain the class labels, such that I can store them along with the box coordinates?

**Comment by saharudra** [comment]
Hi @mahirjain25, how were you able to get the class labels? Also, can you get all the class labels for a given bounding box?
Thanks.

**Comment by mahirjain25** [comment]
I realised that separate files are created for each label. In each of these files, all occurrences of the label across all test images are mentioned. So if any label is detected in an image, it's result will be stored in the respective file.

**Comment by saharudra** [comment]
Do you know where in the darknet code this is being done? Also, is there an id for which image that prediction belongs to.
