### ISSUE TITLE
`classifier valid` output

### ISSUE THREAD

**Issue by cebolan** [pjreddie/darknet#825]
I followed the CIFAR training tutorial at [https://pjreddie.com/darknet/train-cifar/](https://pjreddie.com/darknet/train-cifar/) but I don't really get the output of `./darknet classifier valid` compared to `./darknet classifier validfull`. When I run `valid`, the top-1 accuracy gets to exactly 0.1 and top-2 accuracy to exactly 0.2, while when I run `validfull` the top-1 and top-2 accuracy are, respectively, ~0.60 and ~0.78.

What does `valid` actually do?

**Comment by wxhqw** [comment]
i also face the same problem, could you tell me how do you save the problem?

**Comment by ZakiZhang168** [comment]
i also face the same problem, could you tell me how do you save the problem?
