### ISSUE TITLE
detection failed on YOLO v3 when change classes num, but training well

### ISSUE THREAD

**Issue by qd213618** [pjreddie/darknet#829]
I have test on change classes num to 1 and 5, after 11 hours on 980tx, output IOU and Class, Obj are nearly 0.98, but when i close training and run the command like: ./darknet detector test ****, I got nothing on the terminal.
I do change the class num in voc.data and yolov3-voc.cfg, so does the filters in it. And the class in label files is starts from 0.
Then i check the code of yolo_layers.c and output the detection num of box, i got 0, then i change the thres to 0.3, still got 0 boxes.
I think there must be some bug on the code.

**Comment by stskyblade** [comment]
I just have the same problem, did you find a solution?
@qd213618
