### ISSUE TITLE
yolov3 trained model fails te detection anything / 106 yolo

### ISSUE THREAD

**Issue by hyoeun27** [pjreddie/darknet#839]
93 conv     18  1 x 1 / 1    26 x  26 x 512   ->    26 x  26 x  18  0.012 BFLOPs
   94 yolo
   95 route  91
   96 conv    128  1 x 1 / 1    26 x  26 x 256   ->    26 x  26 x 128  0.044 BFLOPs
   97 upsample            2x    26 x  26 x 128   ->    52 x  52 x 128
   98 route  97 36
   99 conv    128  1 x 1 / 1    52 x  52 x 384   ->    52 x  52 x 128  0.266 BFLOPs
  100 conv    256  3 x 3 / 1    52 x  52 x 128   ->    52 x  52 x 256  1.595 BFLOPs
  101 conv    128  1 x 1 / 1    52 x  52 x 256   ->    52 x  52 x 128  0.177 BFLOPs
  102 conv    256  3 x 3 / 1    52 x  52 x 128   ->    52 x  52 x 256  1.595 BFLOPs
  103 conv    128  1 x 1 / 1    52 x  52 x 256   ->    52 x  52 x 128  0.177 BFLOPs
  104 conv    256  3 x 3 / 1    52 x  52 x 128   ->    52 x  52 x 256  1.595 BFLOPs
  105 conv     18  1 x 1 / 1    52 x  52 x 256   ->    52 x  52 x  18  0.025 BFLOPs
  106 yolo
Loading weights from darknet19_448.conv.23...Done!
Learning Rate: 5e-05, Momentum: 0.9, Decay: 0.0001
Resizing
480
Loaded: 0.000027 seconds
Region 82 Avg IOU: 0.376347, Class: 0.733719, Obj: 0.316935, No Obj: 0.455782, .5R: 0.500000, .75R: 0.166667,  count: 6
Region 94 Avg IOU: 0.414733, Class: 0.356100, Obj: 0.350064, No Obj: 0.497446, .5R: 0.000000, .75R: 0.000000,  count: 2

It appear 'yolo' instead of 'detection' in 106 layer and 94 layer.
As a result, trained model fails to detection anything.

Loading weights from backup/yolo-obj_900.weights...Done!
data/pilltest1.jpg: Predicted in 0.134480 seconds.
-> percentage does not appear!
Help me..

class = 1, filter = 18.
I use yolov3, python 2.7, ubuntu, GPU.

**Comment by ljjyxz123** [comment]
I met the same problem, when I use the weights file trained by my own data, the result only shows something like this:
Loading weights from backup/yolo-obj_900.weights...Done!
data/pilltest1.jpg: Predicted in 0.134480 seconds.

And there is no exact object detected with percentage.

Have you solved that problem?

Or should I wait till the IOU is very close to 1?

**Comment by ouyangkid** [comment]
I want to see the front part of the cfg file

**Comment by hyoeun27** [comment]
Thank you for your interest in my matter.
I solved problem.
Program was running correctly.
This is problem of the number of training.
I trained 40,000 times.
It was predicted well!

**Comment by hetthummar** [comment]
I have same problem.i use yolov2-tiny to detect object but in prediction.jpg file it predict nothing.output image is same like input image.please help me..

**Comment by hyoeun27** [comment]
I used yolov3-tiny.
How many times did you tain?
I trained  40,000 times.
Increase the number of training session.

**Comment by hyoeun27** [comment]
I've been through the same thing.
So, I changed the yolov3-thiny. When I changed it, it was trained very well.
I'm sorry, this is all I know. I hope to my answer is helpful.
If you tell me any other questions, I'll do my best to answer them.

**Comment by iibrahimli** [comment]
@hyoeun27 You said that you changed the yolov3-tiny, do you mean that you changed something in config files? If so, would you please share your steps, because I face the same issue but with the full yolov3 model. I train it on ~4k images of 1 class, would you recommend switching to yolov3-tiny?
Thanks beforehand.

**Comment by barzan-hayati** [comment]
> I used yolov3-tiny.
> How many times did you tain?
> I trained 40,000 times.
> Increase the number of training session.

@hyoeun27 I also used for training a class to object detection, but I receive this message for each line:
`
Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.000001, .5R: -nan, .75R: -nan,  count: 0`

also loss reaches to 0.1, but when I test trained weights, it could not detect any object.

**Comment by vaibhavjussspacetech** [comment]
I also have the same problem after 3000 I am getting -nan but with the use of train weights I am not getting any detection..kindly help...I think in this scenario I should not go for further iteration of training...

**Comment by GitHub4Anandh** [comment]
I trained yolov3 with 2500 images with 14 classes in google colab, the results were good but colab hangs and crashes, I am clueless about the crash. So, I created a VM instance in google cloud with 1 GPU and started training with it, the training process went well but this time the model detected nothing. 
Any help is appreciated. Thanks.
