### ISSUE TITLE
Issue with mismatch in weights file over and over again for all weights file

### ISSUE THREAD

**Issue by Geeks-Sid** [pjreddie/darknet#850]
`flow --model cfg/yolov2-tiny.cfg --load bin/yolov2-tiny.weights`
as soon as I run the above command, i got the following error.
`AssertionError: expect 44948596 bytes, found 44948600`
which means that i have loaded the correct weights, but the weights are being offset by 4 bytes, which means there is some issue with the weights file. I have tested the weights and downloaded them from darknet website but nothing seems to work.

**Comment by yoummiegao** [comment]
I face the same problem, is there any process made for this issue?

**Comment by Maik93** [comment]
For me is quite different: `yolov2-tiny` has the same error as you, but with `yolov2` or `yolov2-voc` bytes can be successfully identified. Then unfortunately I've got this error: `labels.txt and cfg/yolov2.cfg indicate inconsistent class numbers`.
I'm running flow with same arguments as you: `./flow --model cfg/yolov2.cfg --load bin/yolov2.weights`.
Any suggestion?

**Comment by Maik93** [comment]
Ok wait, I don't know why I'm here in darknet repo, but my problems are with [darkflow](https://github.com/thtrieu/darkflow), the darknet porting to TensorFlow, but I suppose you're talking of it too, there's no `flow` command in darknet.
However my solution is to rename config files, or substitute `labels.txt` content with `cfg/coco.names`, as [explained here](https://github.com/thtrieu/darkflow/issues/295#issuecomment-310146199)
