### ISSUE TITLE
Errors in running darknet.py

### ISSUE THREAD

**Issue by xuesongle** [pjreddie/darknet#857]
I intend to python wrapper function darknet.py

python darknet.py 
Traceback (most recent call last):
  File "darknet.py", line 151, in <module>
    net = load_net("cfg/yolov3-tiny.cfg", "yolov3-tiny.weights", 0)
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type

It has the those errors. What changes should I make? Thanks.

**Comment by khanh1412** [comment]
Did you run with python 3?

**Comment by xuesongle** [comment]
Yes, I did.$ python --version
Python 3.6.1 :: Anaconda custom (64-bit)

**Comment by khanh1412** [comment]
this darknet.py file was written for python 2.
There are some differences between python 2 and python 3, they are print function and string.
(You can search on google).
I have change a bit in darknet.py file to run in python 3.
https://github.com/khanh1412/darknet_python_wrap/

**Comment by xuesongle** [comment]
Yes, I realized now and download another version from https://github.com/AlexeyAB/darknet/blob/master/darknet.py. Thanks for your help.

**Comment by davidparkerhl** [comment]
found this, add a b  in front of the string may solve the problem
net = load_net(b"cfg/yolov3.cfg", b"yolov3.weights", 0)

**Comment by khanh1412** [comment]
> @khanh1412 the page you posed is already 404. would you be so kind to maybe repose somewhere

Sorry, I have deleted that repo already.
