### ISSUE TITLE
Problem while trying to run a mp4-file

### ISSUE THREAD

**Issue by katariinatuovinen** [pjreddie/darknet#859]
Hi! I'm having a problem with YOLOv3  while trying to run and detect a mp4 - file (according to this guide: https://jkjung-avt.github.io/yolov3/).
At the moment I'm using Jetson TX2 and have installed OpenCV version 3.4 (according to this guide: https://jkjung-avt.github.io/opencv3-on-tx2/). 
However, while running the detector (./darknet detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights traffic.mp4), I get the following error code:

Loading weights from yolov3.weights...Done!
video file: traffic.mp4
VIDEOIO ERROR: V4L: device traffic.mp4: Unable to query number of channels
GStreamer: Error opening bin: unexpected reference "traffic" - ignoring
Couldn't connect to webcam.
: No such file or directory
darknet: ./src/utils.c:256: error: Assertion `0' failed.

Is there something I'm missing? The traffic.mp4 - file is in my home directionary, and I don't have any working webcams. It seems that the problem is with the video detecting, pictures are working just fine. 
Thanks in advance :)

**Comment by sainisanjay** [comment]
@katariinatuovinen  do you solve this issue, as i am facing same issue.

**Comment by katariinatuovinen** [comment]
Oh yes! The problem was simple, the path of the video was simply wrong. So the easiest way to solve this is to save video-files in the darknet-directory, then you can just run:
./darknet detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights <video file>
But for example if you have the video in your home-directory, you can run:
./darknet detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights ../<videofile>
