### ISSUE TITLE
How can I redirect output image by input parameter？

### ISSUE THREAD

**Issue by lizekui** [pjreddie/darknet#87]
YOLO is indeed a great project for beginner as me , 
so... it is hard for me to find a way that redirect output image by input parameter.

For example, 
`./darknet detect cfg/yolo.cfg weights/yolo.weights data/dog.jpg`
It returns 'predictions.png' just in current path.

How can I change output path ?

Thanks a lot !

**Comment by Grabber** [comment]
It is better to send your question on the Google Group, issues are not for asking for help.

**Comment by lizekui** [comment]
Haha @Grabber , I am a newbie totally... please forgive me, I am going to Group right now~~~

**Comment by lizekui** [comment]
Finally I choose the easiest way, `cp` shell script, which written below ( Shell called by Py ):
`"cp predictions.png %s%s" % (app.config['OUTPUT_FOLDER'], filename_output)`

Haha Thanks @Grabber
