### ISSUE TITLE
issue about darknet.py

### ISSUE THREAD

**Issue by xuzhongyou** [pjreddie/darknet#879]
when i use the darknet.py,it shows Couldn't open file: data/coco.names. what happens to the load_meta

**Comment by janvib27** [comment]
hey can you please help me solve this error.
Couldn't open file: data/coco.names
Thanks in Advance !

**Comment by PeterQuinn925** [comment]
Dumb question - does the file data/coco.names exist?

**Comment by janvib27** [comment]
[https://github.com/pjreddie/darknet/blob/master/data/coco.names](url)
This is the file. The file exits and the location is as mentioned.

**Comment by PeterQuinn925** [comment]
What command are you running when you get this error? Are you using Windows, Linux or Mac? Can you try editing coco.data and putting a fully qualified path to coco.names?
