### ISSUE TITLE
Making GPU version

### ISSUE THREAD

**Issue by RyanCodes44** [pjreddie/darknet#890]
Hi all, 

I am about to make darknet with GPU support. I was wondering if the CUDA/CUDNN versions had to be anything specific? Can't find the specific version number anywhere. 
i.e. would the latest version be supported? 

Thanks

**Comment by AlexeyAB** [comment]
Hi, 

You can use cuDNN >= v5 and CUDA >= 7.5, and GPU CC >= 3.0


Also this repository supports: https://github.com/AlexeyAB/darknet

* both Windows and Linux
* both OpenCV 2.x.x and OpenCV <= 3.4.0 (3.4.1 and higher isn't supported)
* both cuDNN >= v5
* CUDA >= 7.5
* also create SO-library on Linux and DLL-library on Windows

**Comment by RyanCodes44** [comment]
@AlexeyAB thank you. Is there a reason why that repository would be preferred over this one?

**Comment by AlexeyAB** [comment]
@RyanCodes44 Only if you want some of these features: https://github.com/AlexeyAB/darknet/issues/529#issuecomment-377204382

But all new neural networks first appear in the current original repository.

**Comment by RyanCodes44** [comment]
@AlexeyAB awesome. Thank you for your responses.
