### ISSUE TITLE
Demo needs OpenCV for webcam images

### ISSUE THREAD

**Issue by hyoeun27** [pjreddie/darknet#892]
./darknet detector train cfg/obj.data cfg/yolo-tiny-obj.cfg darknet19_448.conv.23
./darknet detector test cfg/obj.data cfg/yolo-tiny-obj.cfg backup/yolo-tiny-obj_40000.weights data/test.jpg

-> It  works very well!

./darknet detector demo cfg/obj.data cfg/yolo-tiny-obj.cfg backup/yolo-tiny-obj_40000.weights data/test.jpg
./darknet detector demo cfg/obj.data cfg/yolo-tiny-obj.cfg backup/yolo-tiny-obj_40000.weights data/test.mp4

-> It does not work.

Demo needs OpenCV for webcam images.

Opencv = 2.4.8
I use GPU.
Makefile is changed .
GPU=1
Opencv=1
I connected webcam.

./darknet detector test cfg/obj.data cfg/yolo-tiny-obj.cfg backup/yolo-tiny-obj_40000.weights data/test.mp4
-> Cannot load image "data/test.mp4"
STB Reason:unknown image type

**Comment by ahsan856jalal** [comment]
if you want to test on a video then type

./darknet detector demo cfg/obj.data cfg/yolo-tiny-obj.cfg
backup/yolo-tiny-obj_40000.weights data/test.mp4

./darknet detector test     is used to test images


Regards
Ahsan

**Comment by hyoeun27** [comment]
./darknet detector demo cfg/obj.data cfg/yolo-tiny-obj.cfg
backup/yolo-tiny-obj_40000.weights data/test.mp4

-> Demo needs OpenCV for webcam images.

**Comment by ahsan856jalal** [comment]
which version of opencv do you have ?
pkg-config --modversion opencv  -> version ?
python -c import cv2;cv2.__version__  --> version ?


Regards
Ahsan

**Comment by ahsan856jalal** [comment]
can you upgrade your opencv to 3.4.0 . I have opencv 3.4.0 and everything
is working fine
Regards
Ahsan

**Comment by hyoeun27** [comment]
Thankyou!
I solved the problem. But I faced new problems...

 103 conv    128  1 x 1 / 1    52 x  52 x 256   ->    52 x  52 x 128  0.177 BFLOPs
 104 conv    256  3 x 3 / 1    52 x  52 x 128   ->    52 x  52 x 256  1.595 BFLOPs
 105 conv    255  1 x 1 / 1    52 x  52 x 256   ->    52 x  52 x 255  0.353 BFLOPs
 106 yolo
Loading weights from yolov3.weights...Done!
Couldn't connect to webcam.
: No such file or directory
darknet: ./src/utils.c:256: error: Assertion `0' failed.
Aborted (core dumped)

Webcam is Rogitech 4k brio.
Webcam is worked !

**Comment by sainisanjay** [comment]
@hyoeun27, is your setup working for video file. i am getting error for video;
```
Loading weights from yolov3.weights...Done!
video file: /data/Yo.mp4
Couldn't connect to webcam.
: No such file or directory
darknet: ./src/utils.c:256: error: Assertion `0' failed.
Aborted (core dumped)

```

**Comment by hyoeun27** [comment]
My problem was remote acceess.
I used to connect with putty.
So, I connected directly to the local and it worked fine.
If you are using remote access, opencv will not work well..

**Comment by ghugeshree** [comment]
@hyoeun27 did it work for webcam after upgrading opencv. I'm still stuck at this error "Demo needs OpenCV for webcam images."! Please help!

**Comment by NET-OF-BEING** [comment]
im stuck as well. I had in running a while ago and now i get the same error message:( Someone help!

**Comment by dreistheman** [comment]
Me too. I already changed the Makefile to have `OPENCV=1`, set the `OpenCV_DIR` variable in CMakeCache.txt to `{path to local user}\.conda\envs\tf_gpu\Library\lib` where the conda OpenCV lib is which leads to a successful cmake configuration:
![image](https://user-images.githubusercontent.com/38012974/57564950-29f3e480-73e7-11e9-80e5-fb62837aa938.png)

Since my conda environment's OpenCV has been found, I expected it to work now, STILL I receive the same error message `Demo needs OpenCV for webcam images.' :( 

Side question: How do you enable CUDA too for Darknet?

**Comment by xzessmedia** [comment]
> I solved the problem. But I faced new problems...

give the stupidity a sense and share your results

**Comment by VincentDuf** [comment]
Hi,
I'm working on JetsonTX2 and I wonder if someone did the modification on the CMakeCache.txt too ? 

I have the same issue with Demo needs OpenCV and I can't "make" darknet even with opencv=1. I checked CUDA,Opencv(3.4.0) and cudnn but nothing seems to work.

**Comment by gauravsharma-gs** [comment]
I am having the same issue !
This is the text on terminal-------------->
@LAPTOP-QBDOA8AA:/mnt/e/Darknet/2/darknet$ ./darknet detector train custom/trainer.data custom/yolov3-tiny.cfg darknet53.conv.74
yolov3-tiny
First section must be [net] or [network]: Success
darknet: ./src/utils.c:256: error: Assertion `0' failed.
Aborted (core dumped)
*************************************************************
i have followed all the steps!

**Comment by Mohammed-Bin-Mohammed** [comment]
I am having the same issue ! 
but I install more than one opencv  

could any one help
