### ISSUE TITLE
Getting make error while compiling with cuDNN

### ISSUE THREAD

**Issue by MithileshHinge** [pjreddie/darknet#92]
![screenshot from 2017-07-18 01_08_17](https://user-images.githubusercontent.com/13969214/28286488-fba348dc-6b55-11e7-89c1-dc87a3d3504a.png)
Hi, I've compiled darknet successfully with GPU=1 flag, but its running at 0.5-1.5 FPS. I have installed CUDA 8.0 and have tried compiling with cuDNN v4.0, v5.0 and v6.0 as well but I'm getting the above error. Any help appreciated!

**Comment by MithileshHinge** [comment]
For anyone having the same issue, change the line 133 in file src/convolutional_layer.c  from 
`cudnnSetConvolution2dDescriptor(l->convDesc, l->pad, l->pad, l->stride, l->stride, 1, 1, CUDNN_CROSS_CORRELATION);`
to 
`cudnnSetConvolution2dDescriptor(l->convDesc, l->pad, l->pad, l->stride, l->stride, 1, 1, CUDNN_CROSS_CORRELATION, CUDNN_DATA_FLOAT);`

**Comment by gangyahaidao** [comment]
this works, thank you!@MithileshHinge
