### ISSUE TITLE
Using Validation Data

### ISSUE THREAD

**Issue by RyanCodes44** [pjreddie/darknet#933]
Hi all, 

I am trying to train YOLO on my own dataset. My dataset is provided into 3 groups: A, B, C.
The goal is to train on A+B, test on C. Then train on A+C, test on B. Finally, train on B+C, test on A. 3-Fold cross-validation. Therefore, I am creating 3 different trained models of YOLO. However, I do not want to provide the group I am testing on during training. i.e. train on A+B, freeze weights, test on C. Repeat for other two trained models. 
 
I'm confused about whether or not the validation data provided in the path of the **.cfg** file is being used during training. 

Thanks

**Comment by Keshav-Aggarwal** [comment]
Hi @RyanCodes44 have you found the solution?

**Comment by RyanCodes44** [comment]
It does not use the .txt file provided in "valid=" during training. This file is called only during the ./darknet detector map ...

**Comment by jaelim** [comment]
@RyanCodes44 when you validate your trained model on your test dataset (unseen), what command do you use?

I tried this, but doesn't seem like the model is being used to test:

``./darknet detector map cfg/my_data cfg/my_yolov3.cfg model/my_yolov3_final.weights

**Comment by RyanCodes44** [comment]
@jaelim what is the error that is outputted? Make sure all paths are correct.

**Comment by MarStarck** [comment]
@RyanCodes44 It just end without any output.

**Comment by jaelim** [comment]
@RyanCodes44 The `map` is not implemented in this repo version. There's another repo created that has this feature.

**Comment by RyanCodes44** [comment]
@jaelim correct. My apologies. Thought I was on that repo
