### ISSUE TITLE
how do i change label's color?

### ISSUE THREAD

**Issue by YoungMiao** [pjreddie/darknet#936]
for this:
![test](https://user-images.githubusercontent.com/22539027/42266807-01f86866-7faa-11e8-955d-321ea6bf1691.png)
How can I solve it?
THX

**Comment by YoungMiao** [comment]
Using the system：Ubuntu16.04

**Comment by sharowyeh** [comment]
Here is related source code, depends on index of label in classes list.
https://github.com/pjreddie/darknet/blob/f6d861736038da22c9eb0739dca84003c5a5e275/src/image.c#L270-L272

**Comment by YoungMiao** [comment]
@sharowyeh i can find it. how can I solve it?

**Comment by sharowyeh** [comment]
float value 0.0~1.0 represent 0~255 color space

**Comment by YoungMiao** [comment]
@sharowyeh thank you
