### ISSUE TITLE
Compiling GPU = 1 on windows

### ISSUE THREAD

**Issue by skipm3** [pjreddie/darknet#938]
Hi there. I'm configuring out about how to compiling with enabled GPU and CUDA
First, i've follow this tutorial https://www.youtube.com/watch?v=7PX_H00V6RA

There's an error shows up
`In file included from ./src/gemm.c:3:0:
./src/cuda.h:28:10: fatal error: cuda_runtime.h: No such file or directory
 #include "cuda_runtime.h"
          ^~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:130: obj/gemm.o] Error 1
`
I think it's because of the CUDA include's path

`ifeq ($(GPU), 1)
COMMON+= -DGPU -I/usr/local/cuda/include/
CFLAGS+= -DGPU`

Because i'm using windows and cygwin for the terminal, i trying to edit the makefile in gpu section

`ifeq ($(GPU), 1)
COMMON+= -DGPU -I/cygdrive/c/Program\ Files/NVIDIA\ GPU\ Computing\ Toolkit/CUDA/v9.2/include
CFLAGS+= -DGPU`

And it shows error
`nvcc  -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=[sm_50,compute_50] -gencode arch=compute_52,code=[sm_52,compute_52] -gencode arch=compute_61,code=[sm_61,compute_61]  -DGPU -I/cygdrive/c/Program\ Files/NVIDIA\ GPU\ Computing\ Toolkit/CUDA/v9.2/include -DCUDNN --compiler-options "-Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DGPU -DCUDNN -I/usr/local/cudnn/include" -c ./src/convolutional_kernels.cu -o obj/convolutional_kernels.o
cl : Command line error D8021 : invalid numeric argument '/Wfatal-errors'
convolutional_kernels.cu
make: *** [Makefile:136: obj/convolutional_kernels.o] Error 2
`

I'm using GTX 1070 btw. thx

**Comment by skipm3** [comment]
@AlexeyABv hi. I actually using your repo. I've following the instruction in this https://github.com/AlexeyAB/darknet#how-to-compile-on-windows but it still processing using CPU. If i edit the make file to GPU = 1 then there's a error like i type above in my question.

**Comment by AlexeyAB** [comment]
@skipm3 
There are paths to CUDA/OpenCV for Linux in the Makefile.

So try to compile `darknet.sln` by using MSVS2015 (free version https://go.microsoft.com/fwlink/?LinkId=532606&clcid=0x409 ) instead of `Makefile` (cygwin).

**Comment by skipm3** [comment]
@AlexeyAB i see. I'm successfully compilred it using darknet.sln by using MSVS2015 but the program still using CPU. Is there any configuration?

**Comment by skipm3** [comment]
Thank you @AlexeyAB i'm not read it well.

**Comment by dreistheman** [comment]
@skipm3 Mine still processes using CPU solely. Did you put your CUDA/CUDNN windows path on the Makefile? I changed them with mine:
```
ifeq ($(GPU), 1)
COMMON+= -DGPU -I/C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/include/ #from -I/usr/local/cuda/include/
CFLAGS+= -DGPU
ifeq ($(OS),Darwin) #MAC
LDFLAGS+= C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib -lcuda -lcudart -lcublas -lcurand #from -L/usr/local/cuda/lib
else
LDFLAGS+= C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib/x64 -lcuda -lcudart -lcublas -lcurand #from -L/usr/local/cuda/lib64
endif
endif

ifeq ($(CUDNN), 1)
COMMON+= -DCUDNN
ifeq ($(OS),Darwin) #MAC
CFLAGS+= -DCUDNN -I/C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/include
LDFLAGS+= C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib -lcudnn
else
CFLAGS+= -DCUDNN -I/C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/include
LDFLAGS+= C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib/x64 -lcudnn
endif
endif
```
Take note of the comments I placed, is `-L/usr/local/cuda/lib` equivalent to `-L/C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib` with the `-L` included?

**Comment by pr0ph0z** [comment]
@dreistheman check [this](https://github.com/pjreddie/darknet/issues/938#issuecomment-402879181) comment. If you're using Windows instead of linux, build the project using Visual Studio (instead of using makefile)
