### ISSUE TITLE
image sizes for training on YOLOv3

### ISSUE THREAD

**Issue by merckxiaan** [pjreddie/darknet#941]
I don't know whether this  is the right place to ask this question, but I'm trying to wrap my head around the YOLO algorithm and I was wondering if if it's necessary to use images of the same size for training? I've read that this is recommended for batch training, but I don't find any information about how the darknet implementation works with different image sizes.
Could anyone give me some insight in the image size used to train YOLOv3?

Thanks in advance,
Jules

**Comment by AlexeyAB** [comment]
Darknet automatically resizes images to the network size (width height in your cfg-file) during training and detection.
So you can use any sizes of images.

**Comment by merckxiaan** [comment]
Ohhh, that explains it!
Thank you very much!
