### ISSUE TITLE
Label preparation for YOLO v3

### ISSUE THREAD

**Issue by merckxiaan** [pjreddie/darknet#953]
I'm trying to implement YOLO v3 from scratch in a different language and I was wondering how the labels for the coco dataset get created.
According to [this](https://blog.paperspace.com/how-to-implement-a-yolo-object-detector-in-pytorch/) article, the bounding boxes get calculated as follows:
![image](https://user-images.githubusercontent.com/31353884/42409577-7e7445fc-81dc-11e8-8c40-e15cb0b8f6bb.png)

I've got the coco dataset and I want to create the labels to use in training, does that mean that I have to calculate the inverse sigmoid and stuff for creating these? I was wondering how the darknet implementation goes about creating the labels for a dataset.

Any help would be appreciated,
Jules

**Comment by brondhaish** [comment]
I believe that for a conversion from a COCO annotation bounding box to a YOLO one requires that you make each of the annotation parameters relative to the image width and height.

Therefore, where `bbox = [x, y, w, h]` is the COCO annotation bounding box, the corresponding YOLO one would be `yoloBbox = [x / image_width, y / image_height, w / image_width, h / image_height]`.

You can find a utility which generates the label file and image list for [YOLO from COCO annotations here](https://bitbucket.org/yohji_yamamoto/coco-to-yolo/src/master/).

**Comment by merckxiaan** [comment]
Thanks!

**Comment by aidamanzano** [comment]
> I believe that for a conversion from a COCO annotation bounding box to a YOLO one requires that you make each of the annotation parameters relative to the image width and height.
> 
> Therefore, where `bbox = [x, y, w, h]` is the COCO annotation bounding box, the corresponding YOLO one would be `yoloBbox = [x / image_width, y / image_height, w / image_width, h / image_height]`.
> 
> You can find a utility which generates the label file and image list for [YOLO from COCO annotations here](https://bitbucket.org/yohji_yamamoto/coco-to-yolo/src/master/).

Hi this link no longer works could we get an update version please?
