### ISSUE TITLE
Failed tranining with CUDNN_HALF on Tesla V100

### ISSUE THREAD

**Issue by xentilzax** [pjreddie/darknet#964]
I tried training my model on AWS with Tesla V100. I set in Makefile CUDNN_HALF=1. But i have a problem, when i start training avr lost increase up to 9000 and all parameters have value NaN.
If I set CUDNN_HALF=0,  everything works fine.
What am I doing wrong?

**Comment by AlexeyAB** [comment]
* Do you use this repository https://github.com/AlexeyAB/darknet ?
* Do you use the latest version of this repository?
* Do you use `GPU=1 CUDNN=1 CUDNN_HALF=1 OPENCV=1` in the Makefile?
* Try to train first 1000 iterations with `CUDNN_HALF=0`, and then set `GPU=1 CUDNN=1 CUDNN_HALF=1 OPENCV=1`, recompile and continue training using 
`./darknet detector train obj.data yolo_obj.cfg yolo_obj_1000.weights -dont_show`

**Comment by xentilzax** [comment]
> Do you use this repository https://github.com/AlexeyAB/darknet ?Do you use the latest version of this repository?
no, few commits ago

> Do you use GPU=1 CUDNN=1 CUDNN_HALF=1 OPENCV=1 in the Makefile?
use GPU=1 CUDNN=1 CUDNN_HALF=1 OPENCV=0

> Try to train first 1000 iterations with CUDNN_HALF=0, and then set GPU=1 CUDNN=1 CUDNN_HALF=1 OPENCV=1, recompile and continue training using./darknet detector train obj.data yolo_obj.cfg yolo_obj_1000.weights -dont_show
Thank you for your advice!
