### ISSUE TITLE
Low Accuracy than older darknet code for yolov2

### ISSUE THREAD

**Issue by komalpharate** [pjreddie/darknet#965]
Hi,
I use yolo v2 older version almost 4 months older.

It's more accurate than todays yolov2. 
Any suggestions?

**Comment by titikid** [comment]
I also get only 53.97% mAP on VOC 2007 with current tiny-yolov2-voc model, which is slower than reported (57.1%)

**Comment by guantinglin** [comment]
@komalpharate  Hi, 

Can you tell me how much is the mAP difference between these two version according you experiments? 
Thank you

**Comment by AhmedMohamedBehwashi** [comment]
could you tell me how I get the accuracy using darknet???
