### ISSUE TITLE
How to convert coco/ VOC labels to yolo format?

### ISSUE THREAD

**Issue by JohnWnx** [pjreddie/darknet#969]
How can I obtain the bounding box labels from mscoco data set and convert them into labels for yolov3?

**Comment by JohnWnx** [comment]
https://github.com/matterport/Mask_RCNN/issues/155

**Comment by sarveshj** [comment]
check out this : https://bitbucket.org/yymoto/coco-to-yolo

**Comment by cindyweng** [comment]
Figured I'd share something I put together for my own use this weekend: 

I've created a single-file python script that downloads COCO images by category (e.g. "person"), converts the bounding box coordinates into YOLO format and writes them to .txt files. 

https://github.com/cindyweng/coco-to-yolo-by-category

**Comment by devrimcavusoglu** [comment]
https://github.com/devrimcavusoglu/pybboxes
